"use client";
import { useId } from "react";
import { normalizeWorkforceProfession, workforceProfessions } from "@/lib/workforce-requirements";
export type EditableCommercialLine = { key: string; profession: string; quantity: number; durationMonths: number; unitPrice: number; actualSalary: number; notes: string; sponsorshipType: "dali" | "other"; sponsorName: string; ajirContractStatus: "not_applicable" | "with_ajir" | "without_ajir" };
export const newCommercialLine = (): EditableCommercialLine => ({ key: crypto.randomUUID(), profession: "", quantity: 1, durationMonths: 12, unitPrice: 0, actualSalary: 0, notes: "", sponsorshipType: "dali", sponsorName: "", ajirContractStatus: "not_applicable" });
export default function CommercialLineItemsEditor({ lines, onChange, quantityMode, annual, workforce = true }: { lines: EditableCommercialLine[]; onChange: (lines: EditableCommercialLine[]) => void; quantityMode: "fixed" | "open"; annual: boolean; workforce?: boolean }) {
  const listId = useId();
  const update = (key: string, patch: Partial<EditableCommercialLine>) => onChange(lines.map(row => row.key === key ? { ...row, ...patch } : row));
  return <div className="commercial-line-editor span-two"><datalist id={listId}>{workforceProfessions.map(item => <option key={item.label} value={item.label}/>)}</datalist>
    <input type="hidden" name="items" value={JSON.stringify(lines.map(({ key: _key, ...row }) => { void _key; return { ...row, quantity: quantityMode === "open" ? 0 : row.quantity, durationMonths: annual && workforce ? 12 : row.durationMonths }; }))}/>
    {lines.map((row, index) => <fieldset key={row.key}><legend>البند {index + 1}</legend><div className="feature-form">
      <label>{workforce ? "المهنة" : "بند الأعمال"}<input required minLength={2} maxLength={120} list={workforce ? listId : undefined} value={row.profession} onChange={event => update(row.key, { profession: event.target.value })} onBlur={() => workforce && update(row.key, { profession: normalizeWorkforceProfession(row.profession) })}/></label>
      {quantityMode === "fixed" && <label>العدد<input required type="number" min={1} max={100000} value={row.quantity || ""} onChange={event => update(row.key, { quantity: Number(event.target.value) })}/></label>}
      <label>المدة بالأشهر<input required type="number" min={1} max={120} readOnly={annual && workforce} value={annual && workforce ? 12 : row.durationMonths || ""} onChange={event => update(row.key, { durationMonths: Number(event.target.value) })}/>{annual && workforce && <small>العقد السنوي مدته 12 شهرًا؛ تتغير المدة باختيار الموسم.</small>}</label>
      <label>سعر العميل لكل عامل<input required type="number" min={0.01} max={1000000} step="0.01" value={row.unitPrice || ""} onChange={event => update(row.key, { unitPrice: Number(event.target.value) })}/></label>
      {workforce && <><label>الراتب الفعلي للعامل<input required type="number" min={0} max={1000000} step="0.01" value={row.actualSalary} onChange={event => update(row.key, { actualSalary: Number(event.target.value) })}/></label><label>جهة الكفالة<select value={row.sponsorshipType} onChange={event => update(row.key, { sponsorshipType: event.target.value as EditableCommercialLine["sponsorshipType"], ajirContractStatus: event.target.value === "other" ? "without_ajir" : "not_applicable" })}><option value="dali">على كفالة شركة دالي</option><option value="other">على كفالة جهة أخرى</option></select></label>{row.sponsorshipType === "other" && <label>اسم الكفيل<input required maxLength={160} value={row.sponsorName} onChange={event => update(row.key, { sponsorName: event.target.value })}/></label>}<label>حالة عقد أجير<select value={row.ajirContractStatus} onChange={event => update(row.key, { ajirContractStatus: event.target.value as EditableCommercialLine["ajirContractStatus"] })}>{row.sponsorshipType === "dali" && <option value="not_applicable">لا ينطبق</option>}<option value="with_ajir">بعقد أجير</option><option value="without_ajir">بدون عقد أجير</option></select></label></>}
      <label className="span-two">ملاحظات البند<textarea maxLength={500} value={row.notes} onChange={event => update(row.key, { notes: event.target.value })}/></label>
    </div><button type="button" disabled={lines.length === 1} onClick={() => onChange(lines.filter(item => item.key !== row.key))}>حذف البند</button></fieldset>)}
    <button type="button" disabled={lines.length >= 50} onClick={() => onChange([...lines, newCommercialLine()])}>إضافة بند</button>
  </div>;
}
