"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type ActivityType = "workforce" | "construction" | "maintenance" | "seasonal";
type QuoteLine = { key: string; description: string; quantity: number; durationMonths: number; unit: string; notes: string; sponsorshipType: "dali" | "other"; sponsorName: string; ajirContractStatus: "" | "with_ajir" | "without_ajir" };
const activityOptions = [
  { value: "workforce", label: "توريد العمالة", itemLabel: "المهنة", description: "عامل عام", unit: "عامل/شهر" },
  { value: "construction", label: "المقاولات", itemLabel: "بند الأعمال", description: "أعمال إنشائية", unit: "م²" },
  { value: "maintenance", label: "التشغيل والصيانة", itemLabel: "الخدمة أو الأصل", description: "تشغيل وصيانة", unit: "شهر" },
  { value: "seasonal", label: "الخدمات الموسمية", itemLabel: "الخدمة الموسمية", description: "خدمة موسمية", unit: "عامل/موسم" },
] as const;
function newLine(activity: ActivityType): QuoteLine { const config=activityOptions.find(item=>item.value===activity)!;return{key:crypto.randomUUID(),description:config.description,quantity:1,durationMonths:activity==="seasonal"?1:12,unit:config.unit,notes:"",sponsorshipType:"dali",sponsorName:"",ajirContractStatus:""}; }

export default function QuoteRequestForm({embedded=false}:{embedded?:boolean}) {
  const[sending,setSending]=useState(false),[error,setError]=useState(""),[trackingCode,setTrackingCode]=useState(""),[submittedEmail,setSubmittedEmail]=useState("");
  const[activityType,setActivityType]=useState<ActivityType>("workforce"),[quantityMode,setQuantityMode]=useState<"fixed"|"open">("fixed"),[lines,setLines]=useState<QuoteLine[]>([newLine("workforce")]);
  const idempotencyKey=useRef(crypto.randomUUID()),formRef=useRef<HTMLFormElement>(null),activity=activityOptions.find(item=>item.value===activityType)!;
  // Restoring a browser draft intentionally hydrates controlled fields once after mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("dali-quote-draft")||"null") as null|{fields?:Record<string,string>;activityType?:ActivityType;quantityMode?:"fixed"|"open";lines?:QuoteLine[]};if(!saved)return;if(saved.activityType)setActivityType(saved.activityType);if(saved.quantityMode)setQuantityMode(saved.quantityMode);if(saved.lines?.length)setLines(saved.lines.map(line=>({...line,key:crypto.randomUUID()})));window.setTimeout(()=>{const form=formRef.current;if(!form)return;for(const[name,value]of Object.entries(saved.fields||{})){const field=form.elements.namedItem(name);if(field instanceof HTMLInputElement||field instanceof HTMLTextAreaElement||field instanceof HTMLSelectElement)field.value=value}},0)}catch{}},[]);
  function saveDraft(){const form=formRef.current;if(!form)return;const fields=Object.fromEntries([...new FormData(form).entries()].filter(([,value])=>typeof value==="string")) as Record<string,string>;delete fields.website;localStorage.setItem("dali-quote-draft",JSON.stringify({fields,activityType,quantityMode,lines}))}
  function changeActivity(next:ActivityType){setActivityType(next);setQuantityMode("fixed");setLines([newLine(next)])}
  function updateLine(key:string,patch:Partial<QuoteLine>){setLines(current=>current.map(line=>line.key===key?{...line,...patch}:line))}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError("");const form=event.currentTarget,data=new FormData(form);const payload={...Object.fromEntries(data.entries()),requestType:"quotation",activityType,quantityMode,quotationItems:lines.map(({key:_key,...line})=>({...line,quantity:quantityMode==="open"?0:line.quantity,sponsorshipType:activityType==="workforce"?line.sponsorshipType:null,sponsorName:activityType==="workforce"&&line.sponsorshipType==="other"?line.sponsorName:null,ajirContractStatus:activityType==="workforce"&&line.sponsorshipType==="other"?line.ajirContractStatus:activityType==="workforce"?"not_applicable":null})),quotationTerms:{endDate:data.get("endDate"),workingHours:data.get("workingHours"),weeklyOff:data.get("weeklyOff"),accommodationParty:data.get("accommodationParty"),transportParty:data.get("transportParty"),paymentTerms:data.get("paymentTerms"),specialTerms:data.get("specialTerms")},idempotencyKey:idempotencyKey.current};try{const response=await fetch("/api/workforce-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as{error?:string;trackingCode?:string};if(!response.ok)throw new Error(result.error||"تعذّر إرسال الطلب");setSubmittedEmail(String(data.get("email")||""));setTrackingCode(result.trackingCode||"");form.reset();setLines([newLine("workforce")]);setActivityType("workforce");setQuantityMode("fixed");localStorage.removeItem("dali-quote-draft");idempotencyKey.current=crypto.randomUUID()}catch(submitError){setError(submitError instanceof Error?submitError.message:"تعذّر إرسال الطلب حالياً.")}finally{setSending(false)}}
  if(trackingCode)return <QuoteConfirmation trackingCode={trackingCode} email={submittedEmail} onReset={()=>setTrackingCode("")}/>;
  return <><form ref={formRef} className={`public-quote-form aligned-quote-request ${embedded?"quote-request-form":""}`} onSubmit={submit} onInput={saveDraft}>
    <Section title="بيانات المنشأة والمسؤول" text="تُستخدم هذه البيانات لإنشاء ملف العميل وربط العرض والعقد به لاحقًا."/>
    <label>الاسم النظامي للمنشأة<input name="companyName" required minLength={2} maxLength={160} autoComplete="organization"/></label><label>السجل التجاري<input name="clientCr" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} placeholder="10 أرقام — اختياري"/></label><label>الرقم الضريبي<input name="clientVat" inputMode="numeric" pattern="3[0-9]{13}3" maxLength={15} placeholder="15 رقمًا — اختياري"/></label><label>العنوان الوطني<input name="clientAddress" required minLength={5} maxLength={300} placeholder="المدينة، الحي، الشارع، الرمز البريدي"/></label><label>اسم ممثل المنشأة<input name="fullName" required minLength={2} maxLength={100} autoComplete="name"/></label><label>صفة ممثل المنشأة<input name="representativeTitle" required minLength={2} maxLength={120} placeholder="مثال: المدير العام أو مدير الموارد البشرية"/></label><label>رقم الجوال<input name="mobile" required type="tel" maxLength={20} autoComplete="tel" placeholder="05xxxxxxxx"/></label><label>البريد الإلكتروني<input name="email" required type="email" maxLength={160} autoComplete="email"/></label>
    <Section title="نوع العرض ونطاق التنفيذ" text="اختر النشاط أولًا؛ ستتغير حقول البنود لتطابق نموذج عرض السعر والعقد في النظام."/>
    <label>نوع النشاط<select value={activityType} onChange={event=>changeActivity(event.target.value as ActivityType)}>{activityOptions.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>{activityType==="workforce"&&<label>نطاق العدد<select value={quantityMode} onChange={event=>setQuantityMode(event.target.value as "fixed"|"open")}><option value="fixed">عدد محدد</option><option value="open">عدد مفتوح حسب طلبات الإسناد</option></select></label>}<label>موقع العمل<input name="workSite" required minLength={2} maxLength={180} placeholder="المدينة، الحي أو موقع المشروع"/></label><label>تاريخ البداية المتوقع<input name="requiredStartDate" required type="date"/></label><label>تاريخ النهاية المتوقع<input name="endDate" type="date"/></label><label>مدة التعاقد<select name="duration" required defaultValue=""><option value="" disabled>اختر المدة</option><option>أقل من شهر</option><option>من شهر إلى 3 أشهر</option><option>من 3 إلى 6 أشهر</option><option>من 6 إلى 12 شهراً</option><option>أكثر من سنة</option><option>غير محدد</option></select></label>
    <div className="public-quote-lines span-two">{lines.map((line,index)=><article key={line.key}><header><strong>البند {index+1}</strong>{lines.length>1&&<button type="button" onClick={()=>setLines(current=>current.filter(item=>item.key!==line.key))}>حذف</button>}</header><label>{activity.itemLabel}<input required minLength={2} maxLength={160} value={line.description} onChange={event=>updateLine(line.key,{description:event.target.value})}/></label>{quantityMode==="fixed"&&<label>{activityType==="workforce"?"العدد":"الكمية"}<input required type="number" min={1} max={100000} value={line.quantity} onChange={event=>updateLine(line.key,{quantity:Number(event.target.value)})}/></label>}<label>المدة بالأشهر<input required type="number" min={1} max={120} value={line.durationMonths} onChange={event=>updateLine(line.key,{durationMonths:Number(event.target.value)})}/></label><label>الوحدة<input required maxLength={40} value={line.unit} onChange={event=>updateLine(line.key,{unit:event.target.value})}/></label>{activityType==="workforce"&&<><label>جهة الكفالة<select value={line.sponsorshipType} onChange={event=>updateLine(line.key,{sponsorshipType:event.target.value as "dali"|"other",sponsorName:"",ajirContractStatus:""})}><option value="dali">على كفالة شركة دالي</option><option value="other">على كفالة جهة أخرى</option></select></label>{line.sponsorshipType==="other"&&<><label>اسم الكفيل<input required minLength={2} maxLength={160} value={line.sponsorName} onChange={event=>updateLine(line.key,{sponsorName:event.target.value})}/></label><label>حالة عقد أجير<select required value={line.ajirContractStatus} onChange={event=>updateLine(line.key,{ajirContractStatus:event.target.value as QuoteLine["ajirContractStatus"]})}><option value="" disabled>اختر الحالة</option><option value="with_ajir">بعقد أجير</option><option value="without_ajir">بدون عقد أجير</option></select></label></>}</>}<label className="line-notes">ملاحظات البند<input maxLength={500} value={line.notes} onChange={event=>updateLine(line.key,{notes:event.target.value})}/></label></article>)}</div><button className="public-add-quote-line span-two" type="button" onClick={()=>setLines(current=>[...current,newLine(activityType)])}>+ إضافة {activity.itemLabel}</button>
    <Section title="شروط التشغيل والتعاقد" text="تنتقل هذه البيانات إلى مراجعة العرض ثم إلى العقد عند اعتماده."/>
    <label>ساعات أو ورديات العمل<input name="workingHours" maxLength={120} placeholder="مثال: 8 ساعات — وردية واحدة"/></label><label>الراحة الأسبوعية<input name="weeklyOff" maxLength={120} placeholder="مثال: يوم الجمعة"/></label><label>السكن على<select name="accommodationParty" defaultValue="client"><option value="client">العميل</option><option value="dali">شركة دالي</option><option value="not_applicable">لا ينطبق</option></select></label><label>النقل على<select name="transportParty" defaultValue="client"><option value="client">العميل</option><option value="dali">شركة دالي</option><option value="not_applicable">لا ينطبق</option></select></label><label>طريقة التواصل المفضلة<select name="preferredContact" defaultValue="either"><option value="either">الهاتف أو البريد</option><option value="phone">الهاتف</option><option value="email">البريد</option></select></label><label>شروط الدفع المقترحة<input name="paymentTerms" maxLength={500} placeholder="مثال: دفعات شهرية"/></label><label className="span-two">نطاق العمل والتفاصيل<textarea name="details" required minLength={10} maxLength={2000} rows={5} placeholder="اشرح نطاق الخدمة، المواقع، المسؤوليات والنتائج المطلوبة."/></label><label className="span-two">اشتراطات خاصة<textarea name="specialTerms" maxLength={1000} rows={3}/></label><label className="public-honeypot" aria-hidden="true">الموقع<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="form-consent span-two">بإرسال الطلب تقر بأنك اطلعت على <a href="/privacy">سياسة الخصوصية</a>، وأن البيانات ستستخدم لمراجعة الاحتياج وإعداد العرض والتواصل معك.</p>{error&&<p className="public-form-error span-two" role="alert">{error}</p>}<button className="btn primary span-two" disabled={sending}>{sending?"جارٍ الإرسال...":"إرسال طلب عرض السعر"}</button>
  </form>{!embedded&&<QuoteStatusLookup/>}</>;
}
function Section({title,text}:{title:string;text:string}){return <div className="quote-request-section span-two"><strong>{title}</strong><p>{text}</p></div>}
function QuoteConfirmation({trackingCode,email,onReset}:{trackingCode:string;email:string;onReset:()=>void}){const[message,setMessage]=useState("");async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);data.set("trackingCode",trackingCode);data.set("email",email);setMessage("جارٍ رفع المرفق...");const response=await fetch("/api/quote-requests",{method:"POST",body:data});const result=await response.json() as{error?:string};setMessage(response.ok?"تم ربط المرفق بالطلب بأمان.":result.error||"تعذّر رفع المرفق");if(response.ok)form.reset()}return <div className="public-form-success quote-confirmation" role="status"><span>✓</span><h3>استلمنا طلب عرض السعر</h3><p>رقم المتابعة: <strong dir="ltr">{trackingCode}</strong></p><form onSubmit={upload}><label>أرفق نطاق العمل أو جدول الكميات أو المخططات<input name="file" type="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg"/></label><button className="btn secondary">رفع المرفق</button></form>{message&&<small>{message}</small>}<button type="button" onClick={onReset}>إرسال طلب آخر</button></div>}
function QuoteStatusLookup(){const[result,setResult]=useState(""),[error,setError]=useState("");async function lookup(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setError("");const response=await fetch(`/api/quote-requests?trackingCode=${encodeURIComponent(String(data.get("trackingCode")||""))}&email=${encodeURIComponent(String(data.get("email")||""))}`,{cache:"no-store"});const body=await response.json() as{statusLabel?:string;attachments?:unknown[];error?:string};if(!response.ok){setError(body.error||"تعذّر التحقق");return}setResult(`${body.statusLabel} · ${body.attachments?.length||0} مرفق`)}return <details className="quote-status-lookup"><summary>لديك طلب سابق؟ تابع حالته</summary><form onSubmit={lookup}><input name="trackingCode" required dir="ltr" placeholder="DAL-..."/><input name="email" required type="email" placeholder="البريد المستخدم في الطلب"/><button>عرض الحالة</button></form>{error&&<p role="alert">{error}</p>}{result&&<strong role="status">{result}</strong>}</details>}
