"use client";
import { useState } from "react";
import type { SeasonType } from "@/lib/payment-schedules";

export default function RequestedPaymentSchedule({ defaults }: { defaults?: { seasonType?: SeasonType; paymentSchedule?: Array<{title:string;titleEn:string;dueDate:string;percentage:number}> } }) {
  const [season, setSeason] = useState<SeasonType>(defaults?.seasonType || "regular");
  const [rows, setRows] = useState<Array<{ title: string; titleEn: string; dueDate: string; percentage: number }>>((defaults?.paymentSchedule || []).map(row=>({...row,percentage:row.percentage ?? Number((row as unknown as {percentageBps?:number}).percentageBps||0)/100})));
  return <div className="span-two"><label>نوع المدة والفوترة<select name="seasonType" value={season} onChange={event => setSeason(event.target.value as SeasonType)}><option value="regular">عقود سنوية بدفعات شهرية</option><option value="ramadan">موسم رمضان — دفعات بالنسب</option><option value="hajj">موسم الحج — دفعات بالنسب</option></select></label><input name="paymentSchedule" type="hidden" value={JSON.stringify(season === "regular" ? [] : rows)}/>{season !== "regular" && <details><summary>جدول دفعات مقترح — اختياري</summary>{rows.map((row, index) => <fieldset key={index}><legend>الدفعة {index + 1}</legend>{([['title', 'اسم الدفعة'], ['titleEn', 'اسم الدفعة بالإنجليزية'], ['dueDate', 'تاريخ الاستحقاق']] as const).map(([key, label]) => <label key={key}>{label}<input required type={key === "dueDate" ? "date" : "text"} value={row[key]} onChange={event => setRows(current => current.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item))}/></label>)}<label>النسبة %<input required type="number" min="0.01" max="100" step="0.01" value={row.percentage} onChange={event => setRows(current => current.map((item, i) => i === index ? { ...item, percentage: Number(event.target.value) } : item))}/></label><button type="button" onClick={() => setRows(current => current.filter((_, i) => i !== index))}>حذف الدفعة</button></fieldset>)}<button type="button" onClick={() => setRows(current => [...current, { title: "", titleEn: "", dueDate: "", percentage: 0 }])}>إضافة دفعة مقترحة</button></details>}</div>;
}
