"use client";
import { useState } from "react";
import { parsePaymentSchedule, type SeasonType } from "@/lib/payment-schedules";

export default function RequestedPaymentSchedule({ defaults, required = false, onSeasonChange }: { defaults?: unknown; required?: boolean; onSeasonChange?: (season: SeasonType) => void }) {
  let initial = defaults;
  if (typeof initial === "string") { try { initial = JSON.parse(initial); } catch { initial = {}; } }
  const record = initial && typeof initial === "object" ? initial as Record<string, unknown> : {};
  const [season, setSeason] = useState<SeasonType>(record.seasonType === "hajj" || record.seasonType === "ramadan" ? record.seasonType : "regular");
  const [rows, setRows] = useState(() => parsePaymentSchedule(record.paymentSchedule).map(row => ({ title: row.title, titleEn: row.titleEn || "", dueDate: row.dueDate, percentage: row.percentageBps / 100 })));
  const total = rows.reduce((sum, row) => sum + Math.round(row.percentage * 100), 0);
  return <div className="span-two commercial-payment-schedule"><label>نوع المدة والفوترة<select name="seasonType" value={season} onChange={event => { const value = event.target.value as SeasonType; setSeason(value); onSeasonChange?.(value); }}><option value="regular">عقود سنوية بدفعات شهرية</option><option value="ramadan">موسم رمضان — دفعات بالنسب</option><option value="hajj">موسم الحج — دفعات بالنسب</option></select></label><input name="paymentSchedule" type="hidden" value={JSON.stringify(season === "regular" ? [] : rows)}/>{season !== "regular" && <fieldset><legend>{required ? "جدول الدفعات" : "جدول دفعات مقترح — اختياري"}</legend>{rows.map((row, index) => <div className="commercial-payment-row" key={index}><strong>الدفعة {index + 1}</strong>{([['title', 'اسم الدفعة'], ['titleEn', 'اسم الدفعة بالإنجليزية'], ['dueDate', 'تاريخ الاستحقاق']] as const).map(([key, label]) => <label key={key}>{label}<input required={key !== "titleEn"} maxLength={key === "dueDate" ? 10 : 160} type={key === "dueDate" ? "date" : "text"} value={row[key]} onChange={event => setRows(current => current.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item))}/></label>)}<label>النسبة %<input required type="number" min="0.01" max="100" step="0.01" value={row.percentage || ""} onChange={event => setRows(current => current.map((item, i) => i === index ? { ...item, percentage: Number(event.target.value) } : item))}/></label><button type="button" onClick={() => setRows(current => current.filter((_, i) => i !== index))}>حذف الدفعة</button></div>)}<p role="status">مجموع النسب: {total / 100}%</p><button type="button" onClick={() => setRows(current => [...current, { title: "", titleEn: "", dueDate: "", percentage: 0 }])}>إضافة دفعة مقترحة</button>{required && !rows.length && <p>أضف جدول دفعات مجموع نسبه 100% قبل الحفظ.</p>}</fieldset>}</div>;
}
