import { and, asc, eq, inArray, lte } from "drizzle-orm";
import { getDb } from "@/db";
import { bankAccounts, chartOfAccounts, clientContacts, companyAssets, companyDocuments, contractPaymentSchedules, financialRecords, journalEntries, legalRecords, workforceContracts } from "@/db/schema";
import { createDraftJournal } from "@/lib/accounting";
import { auditPortalAction } from "@/lib/audit";
import { cleanText, makeReference, objectKey } from "@/lib/company-documents";
import { generateIssuedPdf } from "@/lib/pdf-generator";
import { hasPortalPermission, requirePortalApiRole } from "@/lib/portal-access";
import { emitPortalNotification } from "@/lib/portal-notifications";
import { issueDueContractInvoice } from "@/lib/contract-payment-invoicing";
import { getRuntimeEnv } from "@/lib/runtime-env";
import { jsonNoStore, readLimitedJson, rejectCrossSiteRequest, requestCorrelationId } from "@/lib/security";

const positiveId=(value:unknown)=>{const id=Number(value);return Number.isInteger(id)&&id>0?id:0};
const owner=(access:NonNullable<Awaited<ReturnType<typeof requirePortalApiRole>>>)=>access.role==="admin"||access.functionalRoles.includes("system_owner")||access.functionalRoles.includes("system_admin");

export async function GET(){
  const access=await requirePortalApiRole(["admin","manager","employee"]);
  if(!access||!(await hasPortalPermission(access,"contracts","read"))&&!(await hasPortalPermission(access,"finance","read")))return jsonNoStore({error:"غير مصرح"},{status:403});
  const db=getDb();const today=new Date().toISOString().slice(0,10);
  await db.update(contractPaymentSchedules).set({status:"due",updatedAt:new Date().toISOString()}).where(and(eq(contractPaymentSchedules.status,"scheduled"),lte(contractPaymentSchedules.dueDate,today)));
  const due=await db.select().from(contractPaymentSchedules).where(and(eq(contractPaymentSchedules.status,"due"),lte(contractPaymentSchedules.dueDate,today)));
  for(const payment of due)await issueDueContractInvoice(payment.id,"system@dally-corporation.com").catch(async error=>{await emitPortalNotification({eventType:"contract-payment-auto-invoice-failed",title:"تعذر إنشاء فاتورة دفعة مستحقة",message:`الدفعة ${payment.id} — ${error instanceof Error?error.message:"خطأ غير معروف"}`,severity:"critical",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"operations",targetDepartment:"finance",dedupeKey:`auto-invoice-failed:${payment.id}:${payment.dueDate}`}).catch(()=>undefined)});
  const [contracts,payments,contacts,banks,paymentAccounts]=await Promise.all([db.select().from(workforceContracts).orderBy(asc(workforceContracts.startDate)),db.select().from(contractPaymentSchedules).orderBy(asc(contractPaymentSchedules.dueDate),asc(contractPaymentSchedules.installmentNumber)),db.select().from(clientContacts),db.select().from(bankAccounts).where(eq(bankAccounts.status,"active")).orderBy(asc(bankAccounts.bankName)),db.select().from(chartOfAccounts).where(and(eq(chartOfAccounts.status,"active"),eq(chartOfAccounts.accountType,"asset"),eq(chartOfAccounts.isPosting,true))).orderBy(asc(chartOfAccounts.code))]);
  const clientMobiles=Object.fromEntries(contacts.filter(item=>item.mobile).sort((a,b)=>Number(b.isPrimary)-Number(a.isPrimary)).map(item=>[item.clientId,item.mobile]));
  return jsonNoStore({contracts,payments,clientMobiles,banks,paymentAccounts,canManageContracts:owner(access)||await hasPortalPermission(access,"contracts","write"),canApproveContracts:owner(access),canRefer:owner(access),canInvoice:await hasPortalPermission(access,"finance","write"),canRecordPayment:await hasPortalPermission(access,"finance","approve")||await hasPortalPermission(access,"finance","write"),canReferLegal:owner(access)});
}

export async function POST(request:Request){
  if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});
  const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access||!(await hasPortalPermission(access,"finance","write")))return jsonNoStore({error:"غير مصرح بإنشاء الفاتورة"},{status:403});
  const parsed=await readLimitedJson(request,6000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const paymentId=positiveId(body.paymentId);if(!paymentId)return jsonNoStore({error:"الدفعة غير صحيحة"},{status:400});
  const db=getDb();const payment=await db.query.contractPaymentSchedules.findFirst({where:eq(contractPaymentSchedules.id,paymentId)});if(!payment)return jsonNoStore({error:"الدفعة غير موجودة"},{status:404});if(payment.status!=="referred"||payment.invoiceDocumentId)return jsonNoStore({error:"الدفعة لم تُحل للمحاسبة أو سبق إصدار فاتورتها"},{status:409});
  const contract=await db.query.workforceContracts.findFirst({where:eq(workforceContracts.id,payment.contractId)});if(!contract)return jsonNoStore({error:"العقد غير موجود"},{status:404});
  const assets=await db.select().from(companyAssets);if(!assets.some(a=>a.slot==="stamp")||!assets.some(a=>a.slot==="signature"))return jsonNoStore({error:"يجب اعتماد الختم والتوقيع قبل إصدار الفاتورة"},{status:409});
  const absenceDeductionHalalas=payment.absenceDeductionHalalas||0;const netSubtotalHalalas=Math.max(0,payment.subtotalHalalas-absenceDeductionHalalas);const netVatHalalas=Math.round(netSubtotalHalalas*payment.vatRateBps/10000);const netAmountHalalas=netSubtotalHalalas+netVatHalalas;
  const purchaser=contract.contractDirection==="dali_purchaser";const referenceCode=makeReference(purchaser?"PAY":"INV");const documentType=purchaser?"payment_voucher":"invoice";const documentTitle=purchaser?`استحقاق مورّد ${payment.title}`:`فاتورة ${payment.title}`;const bytes=await generateIssuedPdf({documentType,referenceCode,clientName:contract.clientName,clientCr:contract.clientCr||undefined,clientVat:contract.clientVat||undefined,title:`${documentTitle} - ${contract.referenceCode}`,issueDate:new Date().toISOString().slice(0,10),expiryDate:payment.dueDate,amountHalalas:netAmountHalalas,subtotalHalalas:netSubtotalHalalas,vatHalalas:netVatHalalas,vatRateBps:payment.vatRateBps,details:`خصم غياب العمالة قبل الضريبة: ${(absenceDeductionHalalas/100).toFixed(2)} ر.س.\n`+(purchaser?`استحقاق المورد للدفعة رقم ${payment.installmentNumber} (${payment.title}) من عقد شراء العمالة ${contract.referenceCode}.`:`فاتورة الدفعة رقم ${payment.installmentNumber} (${payment.title}) من العقد ${contract.referenceCode}.`)},assets.map(a=>({slot:a.slot as "stamp"|"signature",storageKey:a.storageKey,contentType:a.contentType})));
  const fileName=`${referenceCode}.pdf`;const storageKey=objectKey("issued-pdfs",fileName);await getRuntimeEnv().BUCKET.put(storageKey,bytes,{httpMetadata:{contentType:"application/pdf"},customMetadata:{issuedBy:access.user.email,referenceCode,contractPaymentId:String(payment.id)}});
  try{
    const result=await db.transaction(async tx=>{const[document]=await tx.insert(companyDocuments).values({referenceCode,title:documentTitle,category:"finance",documentType,counterparty:contract.clientName,fileName,storageKey,contentType:"application/pdf",sizeBytes:bytes.byteLength,expiryDate:payment.dueDate,source:"generated",metadataJson:JSON.stringify({clientId:contract.clientId,supplierId:contract.supplierId,contractDirection:contract.contractDirection,contractId:contract.id,contractReference:contract.referenceCode,paymentScheduleId:payment.id,installmentNumber:payment.installmentNumber,billingBasis:payment.billingBasis,servicePeriod:payment.servicePeriod,absenceDeductionHalalas,netSubtotalHalalas,netVatHalalas,netAmountHalalas}),createdBy:access.user.email}).returning();const[financial]=await tx.insert(financialRecords).values({referenceCode:makeReference("FIN"),category:purchaser?"workforce_supplier_payable":"workforce_invoice",description:`${documentTitle} - ${contract.referenceCode} - ${contract.clientName}`,amountHalalas:netAmountHalalas,subtotalHalalas:netSubtotalHalalas,vatHalalas:netVatHalalas,vatRateBps:payment.vatRateBps,dueDate:payment.dueDate,periodMonth:payment.servicePeriod,contractId:contract.id,documentId:document.id,status:"pending",postingStatus:"unposted"}).returning();const[updated]=await tx.update(contractPaymentSchedules).set({status:"invoiced",invoiceDocumentId:document.id,financialRecordId:financial.id,invoicedBy:access.user.email,invoicedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).where(and(eq(contractPaymentSchedules.id,payment.id),eq(contractPaymentSchedules.status,"referred"))).returning();if(!updated)throw new Error("تمت معالجة الدفعة من مستخدم آخر");return{document,financial,payment:updated}});
    await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-invoiced",entityType:"contract-payment",entityId:payment.id,before:payment,after:result.payment,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"contract-payment-invoiced",title:"أُصدرت فاتورة دفعة عقد",message:`${referenceCode} - ${contract.clientName} - ${payment.title}`,severity:"success",module:"finance",entityType:"company-document",entityId:result.document.id,actionView:"documents",targetRole:"admin"}).catch(()=>undefined);return jsonNoStore(result,{status:201});
  }catch(error){await getRuntimeEnv().BUCKET.delete(storageKey).catch(()=>undefined);return jsonNoStore({error:error instanceof Error?error.message:"تعذر إصدار الفاتورة"},{status:409})}
}

export async function PATCH(request:Request){
  if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});const parsed=await readLimitedJson(request,8000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const action=cleanText(body.action,40);const paymentId=positiveId(body.paymentId);const db=getDb();const payment=paymentId?await db.query.contractPaymentSchedules.findFirst({where:eq(contractPaymentSchedules.id,paymentId)}):null;if(!payment)return jsonNoStore({error:"الدفعة غير موجودة"},{status:404});const contract=await db.query.workforceContracts.findFirst({where:eq(workforceContracts.id,payment.contractId)});if(!contract)return jsonNoStore({error:"العقد غير موجود"},{status:404});const now=new Date().toISOString();
  if(action==="refer-accounting"){
    if(!owner(access))return jsonNoStore({error:"إحالة الدفعة للمحاسبة من صلاحيات المالك فقط"},{status:403});if(!["due","scheduled"].includes(payment.status)||payment.dueDate>now.slice(0,10))return jsonNoStore({error:"لا يمكن إحالة دفعة لم يحن موعدها أو تمت معالجتها"},{status:409});const[updated]=await db.update(contractPaymentSchedules).set({status:"referred",referredBy:access.user.email,referredAt:now,updatedAt:now}).where(and(eq(contractPaymentSchedules.id,payment.id),inArray(contractPaymentSchedules.status,["scheduled","due"]))).returning();if(!updated)return jsonNoStore({error:"تغيرت حالة الدفعة"},{status:409});await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-referred",entityType:"contract-payment",entityId:payment.id,before:payment,after:updated,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"contract-payment-referred",title:"دفعة عقد محالة لإصدار فاتورة",message:`${contract.referenceCode} - ${contract.clientName} - ${payment.title}`,severity:"warning",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"finance",targetDepartment:"finance"}).catch(()=>undefined);return jsonNoStore({payment:updated});
  }
  if(action==="reschedule"){
    if(!(await hasPortalPermission(access,"finance","write")))return jsonNoStore({error:"تعديل موعد الدفعة يتطلب صلاحية مالية"},{status:403});
    if(!["scheduled","due"].includes(payment.status)||payment.invoiceDocumentId||payment.financialRecordId)return jsonNoStore({error:"لا يمكن تعديل الموعد بعد الإحالة أو إصدار الفاتورة أو تسجيل السداد"},{status:409});
    const dueDate=cleanText(body.dueDate,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(dueDate))return jsonNoStore({error:"تاريخ الاستحقاق غير صحيح"},{status:400});
    const[updated]=await db.update(contractPaymentSchedules).set({dueDate,status:dueDate<=now.slice(0,10)?"due":"scheduled",servicePeriod:payment.billingBasis==="monthly_salary"?dueDate.slice(0,7):payment.servicePeriod,updatedAt:now}).where(and(eq(contractPaymentSchedules.id,payment.id),inArray(contractPaymentSchedules.status,["scheduled","due"]))).returning();
    if(!updated)return jsonNoStore({error:"تغيرت حالة الدفعة قبل الحفظ"},{status:409});
    await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-rescheduled",entityType:"contract-payment",entityId:payment.id,before:payment,after:updated,correlationId:requestCorrelationId(request)});
    await emitPortalNotification({eventType:"contract-payment-rescheduled",title:"عُدّل موعد استحقاق دفعة",message:`${contract.referenceCode} - ${payment.title}: ${payment.dueDate} ← ${dueDate}`,severity:"warning",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"finance",targetRole:"admin"}).catch(()=>undefined);
    return jsonNoStore({payment:updated});
  }
  if(action==="mark-paid"){
    if(!(await hasPortalPermission(access,"finance","approve"))&&!(await hasPortalPermission(access,"finance","write")))return jsonNoStore({error:"غير مصرح بتسجيل السداد"},{status:403});
    if(payment.status!=="invoiced"||!payment.financialRecordId||payment.paymentJournalEntryId)return jsonNoStore({error:"لا يمكن تسجيل السداد قبل إصدار الاستحقاق أو سبق تسجيله"},{status:409});
    const financial=await db.query.financialRecords.findFirst({where:eq(financialRecords.id,payment.financialRecordId)});
    if(!financial)return jsonNoStore({error:"السجل المالي المرتبط غير موجود"},{status:404});
    if(contract.contractDirection!=="dali_purchaser")return jsonNoStore({error:"تحصيل عقد البيع يُسجّل من مسار سند القبض، وليس كسداد مورّد"},{status:409});
    if(financial.postingStatus!=="posted")return jsonNoStore({error:"يجب اعتماد وترحيل قيد استحقاق المورد قبل تسجيل السداد البنكي"},{status:409});
    const paymentMethod=cleanText(body.paymentMethod,30);if(!["bank_transfer","cash","cheque"].includes(paymentMethod))return jsonNoStore({error:"اختر طريقة دفع صحيحة"},{status:400});
    const paymentReference=cleanText(body.paymentReference,180);
    const bankAccountId=positiveId(body.bankAccountId);const paymentAccountId=positiveId(body.paymentAccountId);
    const bank=paymentMethod==="cash"?null:await db.query.bankAccounts.findFirst({where:and(eq(bankAccounts.id,bankAccountId),eq(bankAccounts.status,"active"))});
    if(paymentMethod!=="cash"&&!bank)return jsonNoStore({error:"اختر الحساب البنكي المرتبط بطريقة الدفع"},{status:409});
    const cashAccount=paymentMethod==="cash"?await db.query.chartOfAccounts.findFirst({where:and(eq(chartOfAccounts.id,paymentAccountId),eq(chartOfAccounts.status,"active"),eq(chartOfAccounts.accountType,"asset"),eq(chartOfAccounts.isPosting,true))}):null;
    if(paymentMethod==="cash"&&!cashAccount)return jsonNoStore({error:"اختر حساب الصندوق النقدي من دليل الحسابات"},{status:409});
    const payable=await db.query.chartOfAccounts.findFirst({where:and(eq(chartOfAccounts.code,"2100"),eq(chartOfAccounts.status,"active"))});
    if(!payable||!payable.isPosting)return jsonNoStore({error:"حساب ذمم الموردين 2100 غير مهيأ للترحيل"},{status:409});
    const creditAccountId=bank?.ledgerAccountId||cashAccount!.id;const methodLabel=paymentMethod==="bank_transfer"?"تحويل بنكي":paymentMethod==="cheque"?"شيك":"نقدي";
    const journal=await createDraftJournal({entryDate:now.slice(0,10),description:`سداد مورد (${methodLabel}) — ${contract.referenceCode} — ${payment.title}`,sourceType:"contract-payment-settlement",sourceId:String(payment.id),actorEmail:access.user.email,lines:[
      {accountId:payable.id,debitHalalas:financial.amountHalalas,description:`تسوية ذمة المورد — ${contract.clientName}`,contractId:contract.id},
      {accountId:creditAccountId,bankAccountId:bank?.id||null,creditHalalas:financial.amountHalalas,description:`سداد ${methodLabel}${bank?` من ${bank.bankName} — ${bank.accountCode}`:" من الصندوق"}${paymentReference?` — المرجع: ${paymentReference}`:""}`,contractId:contract.id},
    ]});
    try{
      const [updated]=await db.update(contractPaymentSchedules).set({status:"paid",paymentJournalEntryId:journal.entry.id,paidAt:now,updatedAt:now}).where(and(eq(contractPaymentSchedules.id,payment.id),eq(contractPaymentSchedules.status,"invoiced"))).returning();
      if(!updated)throw new Error("تغيرت حالة الدفعة");
      await db.update(financialRecords).set({status:"paid",paymentMethod,bankAccountId:bank?.id||null,notes:[financial.notes,paymentReference?`مرجع السداد: ${paymentReference}`:""].filter(Boolean).join("\n")||null,updatedAt:now}).where(eq(financialRecords.id,payment.financialRecordId));
      await auditPortalAction({actorEmail:access.user.email,action:"supplier-contract-payment-recorded",entityType:"contract-payment",entityId:payment.id,before:payment,after:{...updated,paymentMethod,bankAccountId:bank?.id||null,paymentAccountId:cashAccount?.id||null,paymentReference,paymentJournalEntryId:journal.entry.id},correlationId:requestCorrelationId(request)});
      await emitPortalNotification({eventType:"supplier-contract-payment-recorded",title:"سُجل سداد مستحق مورّد",message:`${contract.referenceCode} - ${contract.clientName} - ${payment.title} - ${methodLabel}${bank?` - ${bank.bankName}`:""}. القيد بانتظار الاعتماد والترحيل.`,severity:"info",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"finance",targetDepartment:"finance"}).catch(()=>undefined);
      return jsonNoStore({payment:updated,journal:journal.entry,bank,paymentMethod,paymentAccount:cashAccount});
    }catch(error){await db.delete(journalEntries).where(eq(journalEntries.id,journal.entry.id)).catch(()=>undefined);throw error}
  }
  if(action==="refer-legal"){
    if(contract.contractDirection==="dali_purchaser")return jsonNoStore({error:"عقد شراء العمالة لا يحال كملف عميل متأخر؛ عالج التزام المورد من المشتريات أو الشؤون القانونية"},{status:409});
    if(!owner(access))return jsonNoStore({error:"إحالة ملف العميل للشؤون القانونية من صلاحيات المالك فقط"},{status:403});if(payment.status==="paid"||payment.dueDate>=now.slice(0,10))return jsonNoStore({error:"لا يمكن الإحالة القانونية قبل التأخر الفعلي في السداد"},{status:409});const reason=cleanText(body.reason,1000);if(reason.length<10)return jsonNoStore({error:"اكتب سبب إحالة واضحاً لا يقل عن 10 أحرف"},{status:400});const referenceCode=`LGL-${contract.referenceCode}`.slice(0,120);let[legal]=await db.insert(legalRecords).values({referenceCode,category:"case",title:`تحصيل متأخر - ${contract.referenceCode}`,counterparty:contract.clientName,expiryDate:null,status:"reviewing"}).onConflictDoNothing().returning();if(!legal)legal=(await db.query.legalRecords.findFirst({where:eq(legalRecords.referenceCode,referenceCode)}))!;await auditPortalAction({actorEmail:access.user.email,action:"client-file-referred-legal",entityType:"legal-record",entityId:legal.id,after:{...legal,contractId:contract.id,paymentId:payment.id,reason},reason,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"client-file-referred-legal",title:"أُحيل ملف عميل متأخر للشؤون القانونية",message:`${contract.clientName} - ${contract.referenceCode}: ${reason}`,severity:"critical",module:"legal",entityType:"legal-record",entityId:legal.id,actionView:"legal",targetDepartment:"legal"}).catch(()=>undefined);return jsonNoStore({legalRecord:legal});
  }
  return jsonNoStore({error:"الإجراء غير معروف"},{status:400});
}