import { and, asc, eq, inArray, lte } from "drizzle-orm";
import { getDb } from "@/db";
import { companyAssets, companyDocuments, contractPaymentSchedules, financialRecords, legalRecords, workforceContracts } from "@/db/schema";
import { auditPortalAction } from "@/lib/audit";
import { cleanText, makeReference, objectKey } from "@/lib/company-documents";
import { generateIssuedPdf } from "@/lib/pdf-generator";
import { hasPortalPermission, requirePortalApiRole } from "@/lib/portal-access";
import { emitPortalNotification } from "@/lib/portal-notifications";
import { getRuntimeEnv } from "@/lib/runtime-env";
import { jsonNoStore, readLimitedJson, rejectCrossSiteRequest, requestCorrelationId } from "@/lib/security";

const positiveId=(value:unknown)=>{const id=Number(value);return Number.isInteger(id)&&id>0?id:0};
const owner=(access:NonNullable<Awaited<ReturnType<typeof requirePortalApiRole>>>)=>access.role==="admin"||access.functionalRoles.includes("system_owner")||access.functionalRoles.includes("system_admin");

export async function GET(){
  const access=await requirePortalApiRole(["admin","manager","employee"]);
  if(!access||!(await hasPortalPermission(access,"workforce","read"))&&!(await hasPortalPermission(access,"finance","read")))return jsonNoStore({error:"غير مصرح"},{status:403});
  const db=getDb();const today=new Date().toISOString().slice(0,10);
  await db.update(contractPaymentSchedules).set({status:"due",updatedAt:new Date().toISOString()}).where(and(eq(contractPaymentSchedules.status,"scheduled"),lte(contractPaymentSchedules.dueDate,today)));
  const [contracts,payments]=await Promise.all([db.select().from(workforceContracts).orderBy(asc(workforceContracts.startDate)),db.select().from(contractPaymentSchedules).orderBy(asc(contractPaymentSchedules.dueDate),asc(contractPaymentSchedules.installmentNumber))]);
  return jsonNoStore({contracts,payments,canApproveContracts:owner(access),canRefer:owner(access),canInvoice:await hasPortalPermission(access,"finance","write"),canRecordPayment:await hasPortalPermission(access,"finance","approve")||await hasPortalPermission(access,"finance","write"),canReferLegal:owner(access)});
}

export async function POST(request:Request){
  if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});
  const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access||!(await hasPortalPermission(access,"finance","write")))return jsonNoStore({error:"غير مصرح بإنشاء الفاتورة"},{status:403});
  const parsed=await readLimitedJson(request,6000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const paymentId=positiveId(body.paymentId);if(!paymentId)return jsonNoStore({error:"الدفعة غير صحيحة"},{status:400});
  const db=getDb();const payment=await db.query.contractPaymentSchedules.findFirst({where:eq(contractPaymentSchedules.id,paymentId)});if(!payment)return jsonNoStore({error:"الدفعة غير موجودة"},{status:404});if(payment.status!=="referred"||payment.invoiceDocumentId)return jsonNoStore({error:"الدفعة لم تُحل للمحاسبة أو سبق إصدار فاتورتها"},{status:409});
  const contract=await db.query.workforceContracts.findFirst({where:eq(workforceContracts.id,payment.contractId)});if(!contract)return jsonNoStore({error:"العقد غير موجود"},{status:404});
  const assets=await db.select().from(companyAssets);if(!assets.some(a=>a.slot==="stamp")||!assets.some(a=>a.slot==="signature"))return jsonNoStore({error:"يجب اعتماد الختم والتوقيع قبل إصدار الفاتورة"},{status:409});
  const referenceCode=makeReference("INV");const bytes=await generateIssuedPdf({documentType:"invoice",referenceCode,clientName:contract.clientName,clientCr:contract.clientCr||undefined,clientVat:contract.clientVat||undefined,title:`فاتورة ${payment.title} - ${contract.referenceCode}`,issueDate:new Date().toISOString().slice(0,10),expiryDate:payment.dueDate,amountHalalas:payment.amountHalalas,subtotalHalalas:payment.subtotalHalalas,vatHalalas:payment.vatHalalas,vatRateBps:payment.vatRateBps,details:`فاتورة الدفعة رقم ${payment.installmentNumber} (${payment.title}) من العقد ${contract.referenceCode}.`},assets.map(a=>({slot:a.slot as "stamp"|"signature",storageKey:a.storageKey,contentType:a.contentType})));
  const fileName=`${referenceCode}.pdf`;const storageKey=objectKey("issued-pdfs",fileName);await getRuntimeEnv().BUCKET.put(storageKey,bytes,{httpMetadata:{contentType:"application/pdf"},customMetadata:{issuedBy:access.user.email,referenceCode,contractPaymentId:String(payment.id)}});
  try{
    const result=await db.transaction(async tx=>{const[document]=await tx.insert(companyDocuments).values({referenceCode,title:`فاتورة ${payment.title}`,category:"finance",documentType:"invoice",counterparty:contract.clientName,fileName,storageKey,contentType:"application/pdf",sizeBytes:bytes.byteLength,expiryDate:payment.dueDate,source:"generated",metadataJson:JSON.stringify({clientId:contract.clientId,contractId:contract.id,contractReference:contract.referenceCode,paymentScheduleId:payment.id,installmentNumber:payment.installmentNumber,billingBasis:payment.billingBasis,servicePeriod:payment.servicePeriod}),createdBy:access.user.email}).returning();const[financial]=await tx.insert(financialRecords).values({referenceCode:makeReference("FIN"),category:"workforce_invoice",description:`فاتورة ${payment.title} - ${contract.referenceCode} - ${contract.clientName}`,amountHalalas:payment.amountHalalas,subtotalHalalas:payment.subtotalHalalas,vatHalalas:payment.vatHalalas,vatRateBps:payment.vatRateBps,dueDate:payment.dueDate,periodMonth:payment.servicePeriod,contractId:contract.id,documentId:document.id,status:"pending",postingStatus:"unposted"}).returning();const[updated]=await tx.update(contractPaymentSchedules).set({status:"invoiced",invoiceDocumentId:document.id,financialRecordId:financial.id,invoicedBy:access.user.email,invoicedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).where(and(eq(contractPaymentSchedules.id,payment.id),eq(contractPaymentSchedules.status,"referred"))).returning();if(!updated)throw new Error("تمت معالجة الدفعة من مستخدم آخر");return{document,financial,payment:updated}});
    await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-invoiced",entityType:"contract-payment",entityId:payment.id,before:payment,after:result.payment,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"contract-payment-invoiced",title:"أُصدرت فاتورة دفعة عقد",message:`${referenceCode} - ${contract.clientName} - ${payment.title}`,severity:"success",module:"finance",entityType:"company-document",entityId:result.document.id,actionView:"documents",targetRole:"admin"}).catch(()=>undefined);return jsonNoStore(result,{status:201});
  }catch(error){await getRuntimeEnv().BUCKET.delete(storageKey).catch(()=>undefined);return jsonNoStore({error:error instanceof Error?error.message:"تعذر إصدار الفاتورة"},{status:409})}
}

export async function PATCH(request:Request){
  if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});const parsed=await readLimitedJson(request,8000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const action=cleanText(body.action,40);const paymentId=positiveId(body.paymentId);const db=getDb();const payment=paymentId?await db.query.contractPaymentSchedules.findFirst({where:eq(contractPaymentSchedules.id,paymentId)}):null;if(!payment)return jsonNoStore({error:"الدفعة غير موجودة"},{status:404});const contract=await db.query.workforceContracts.findFirst({where:eq(workforceContracts.id,payment.contractId)});if(!contract)return jsonNoStore({error:"العقد غير موجود"},{status:404});const now=new Date().toISOString();
  if(action==="refer-accounting"){
    if(!owner(access))return jsonNoStore({error:"إحالة الدفعة للمحاسبة من صلاحيات المالك فقط"},{status:403});if(!["due","scheduled"].includes(payment.status)||payment.dueDate>now.slice(0,10))return jsonNoStore({error:"لا يمكن إحالة دفعة لم يحن موعدها أو تمت معالجتها"},{status:409});const[updated]=await db.update(contractPaymentSchedules).set({status:"referred",referredBy:access.user.email,referredAt:now,updatedAt:now}).where(and(eq(contractPaymentSchedules.id,payment.id),inArray(contractPaymentSchedules.status,["scheduled","due"]))).returning();if(!updated)return jsonNoStore({error:"تغيرت حالة الدفعة"},{status:409});await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-referred",entityType:"contract-payment",entityId:payment.id,before:payment,after:updated,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"contract-payment-referred",title:"دفعة عقد محالة لإصدار فاتورة",message:`${contract.referenceCode} - ${contract.clientName} - ${payment.title}`,severity:"warning",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"finance",targetDepartment:"finance"}).catch(()=>undefined);return jsonNoStore({payment:updated});
  }
  if(action==="mark-paid"){
    if(!(await hasPortalPermission(access,"finance","approve"))&&!(await hasPortalPermission(access,"finance","write")))return jsonNoStore({error:"غير مصرح بتسجيل السداد"},{status:403});if(payment.status!=="invoiced"||!payment.financialRecordId)return jsonNoStore({error:"لا يمكن تسجيل السداد قبل إصدار الفاتورة"},{status:409});const[updated]=await db.update(contractPaymentSchedules).set({status:"paid",paidAt:now,updatedAt:now}).where(and(eq(contractPaymentSchedules.id,payment.id),eq(contractPaymentSchedules.status,"invoiced"))).returning();if(!updated)return jsonNoStore({error:"تغيرت حالة الدفعة"},{status:409});await db.update(financialRecords).set({status:"paid",updatedAt:now}).where(eq(financialRecords.id,payment.financialRecordId));await auditPortalAction({actorEmail:access.user.email,action:"contract-payment-paid",entityType:"contract-payment",entityId:payment.id,before:payment,after:updated,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"contract-payment-paid",title:"تم تسجيل سداد دفعة عقد",message:`${contract.referenceCode} - ${contract.clientName} - ${payment.title}`,severity:"success",module:"finance",entityType:"contract-payment",entityId:payment.id,actionView:"finance",targetRole:"admin"}).catch(()=>undefined);return jsonNoStore({payment:updated});
  }
  if(action==="refer-legal"){
    if(!owner(access))return jsonNoStore({error:"إحالة ملف العميل للشؤون القانونية من صلاحيات المالك فقط"},{status:403});if(payment.status==="paid"||payment.dueDate>=now.slice(0,10))return jsonNoStore({error:"لا يمكن الإحالة القانونية قبل التأخر الفعلي في السداد"},{status:409});const reason=cleanText(body.reason,1000);if(reason.length<10)return jsonNoStore({error:"اكتب سبب إحالة واضحاً لا يقل عن 10 أحرف"},{status:400});const referenceCode=`LGL-${contract.referenceCode}`.slice(0,120);let[legal]=await db.insert(legalRecords).values({referenceCode,category:"case",title:`تحصيل متأخر - ${contract.referenceCode}`,counterparty:contract.clientName,expiryDate:null,status:"reviewing"}).onConflictDoNothing().returning();if(!legal)legal=(await db.query.legalRecords.findFirst({where:eq(legalRecords.referenceCode,referenceCode)}))!;await auditPortalAction({actorEmail:access.user.email,action:"client-file-referred-legal",entityType:"legal-record",entityId:legal.id,after:{...legal,contractId:contract.id,paymentId:payment.id,reason},reason,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"client-file-referred-legal",title:"أُحيل ملف عميل متأخر للشؤون القانونية",message:`${contract.clientName} - ${contract.referenceCode}: ${reason}`,severity:"critical",module:"legal",entityType:"legal-record",entityId:legal.id,actionView:"legal",targetDepartment:"legal"}).catch(()=>undefined);return jsonNoStore({legalRecord:legal});
  }
  return jsonNoStore({error:"الإجراء غير معروف"},{status:400});
}
