import type { Metadata } from "next";
import PublicPageShell from "@/app/components/PublicPageShell";
import DataSubjectRequestForm from "@/app/components/DataSubjectRequestForm";
import PrivacyStatusLookup from "@/app/components/PrivacyStatusLookup";

export const metadata: Metadata = { title: "سياسة الخصوصية", description: "سياسة خصوصية شركة دالي للتشغيل والصيانة وحقوق أصحاب البيانات ووسيلة تقديم طلبات الوصول والتصحيح والحذف.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <PublicPageShell><section className="inner-hero governance-hero"><p className="eyebrow light"><span/>حماية البيانات</p><h1>سياسة الخصوصية</h1><p>توضح هذه الصفحة البيانات التي نجمعها من الموقع والبوابات، وأغراض استخدامها وحقوق أصحابها.</p></section><article className="inner-content policy-content"><p className="policy-version">آخر تحديث: 14 أغسطس 2026</p><h2>نطاق السياسة</h2><p>تسري على زوار الموقع، ومستخدمي المحادثة وطلبات عروض الأسعار، والعملاء، ومستخدمي البوابات، وملفات الموظفين والعمال التي تعالجها الشركة ضمن أعمالها.</p><h2>البيانات والأغراض</h2><div className="policy-table"><div><b>طلبات الأسعار والتواصل</b><span>الاسم والجوال والبريد والمنشأة والاحتياج؛ لمراجعة الطلب والتواصل وإعداد العرض.</span></div><div><b>المحادثة المباشرة</b><span>بيانات التواصل والرسائل ومعلومات تقنية مجزأة؛ لتقديم الدعم ومنع الإساءة.</span></div><div><b>العملاء والعقود</b><span>بيانات المنشأة وجهات الاتصال والعروض والعقود وأوامر التشغيل؛ لتنفيذ العلاقة التجارية.</span></div><div><b>العمال والموظفون</b><span>الهوية والإقامة والصورة والمهنة والشهادات والبيانات التشغيلية؛ لإدارة القوى العاملة والامتثال.</span></div></div><h2>تقليل البيانات والاحتفاظ</h2><p>نجمع القدر اللازم للغرض المحدد. تُراجع مدد الاحتفاظ بحسب نوع السجل والالتزام النظامي أو التعاقدي، ثم تُحذف البيانات أو تُجهّل عندما ينتفي الغرض، ما لم يلزم الاحتفاظ بها لإثبات حق أو التزام.</p><h2>المشاركة والحماية</h2><p>يقتصر الوصول على المستخدمين المخولين بحسب الدور والقسم. قد تُعالج البيانات عبر مزودي الاستضافة والتخزين والبريد اللازمين لتشغيل الخدمة، مع تطبيق ضوابط وصول وتسجيل ومشاركة مؤقتة للمستندات.</p><h2>حقوقك</h2><p>يمكنك تقديم طلب للوصول أو التصحيح أو الحذف أو سحب الموافقة أو الشكوى. سنطلب تحققًا مناسبًا من الهوية قبل كشف البيانات أو تغييرها.</p><section className="privacy-request-section"><h2>تقديم طلب متعلق بالبيانات</h2><DataSubjectRequestForm/><h3>متابعة طلب سابق</h3><PrivacyStatusLookup/></section><h2>التواصل</h2><p>يمكن التواصل مع الشركة من خلال <a href="/contact">صفحة التواصل</a> مع ذكر رقم الطلب إن وجد.</p></article></PublicPageShell>;
}
