import { and, asc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { legalCaseActivities, legalRecords } from "@/db/schema";
import { auditPortalAction } from "@/lib/audit";
import { emitPortalNotification } from "@/lib/portal-notifications";
import { hasPortalPermission, requirePortalApiRole } from "@/lib/portal-access";
import { jsonNoStore, readLimitedJson, rejectCrossSiteRequest } from "@/lib/security";
const clean=(value:unknown,max=1000)=>typeof value==="string"?value.trim().slice(0,max):"";
async function access(write=false){const actor=await requirePortalApiRole(["admin","manager","employee"]);return actor&&await hasPortalPermission(actor,"legal",write?"write":"read")?actor:null}
export async function GET(){const actor=await access();if(!actor)return jsonNoStore({error:"غير مصرح"},{status:403});const db=getDb();const[cases,activities]=await Promise.all([db.select().from(legalRecords).orderBy(asc(legalRecords.status),asc(legalRecords.createdAt)),db.select().from(legalCaseActivities).orderBy(asc(legalCaseActivities.dueAt),asc(legalCaseActivities.createdAt))]);return jsonNoStore({cases,activities,canWrite:await hasPortalPermission(actor,"legal","write"),canApprove:await hasPortalPermission(actor,"legal","approve")})}
export async function POST(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const actor=await access(true);if(!actor)return jsonNoStore({error:"غير مصرح"},{status:403});const parsed=await readLimitedJson(request,10000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const legalRecordId=Number(body.legalRecordId);const activityType=clean(body.activityType,30);const title=clean(body.title,180);const details=clean(body.details,5000);const priority=clean(body.priority,20)||"medium";const dueAt=clean(body.dueAt,30)||null;const assignedTo=clean(body.assignedTo,180)||null;if(!Number.isInteger(legalRecordId)||legalRecordId<1||title.length<3||!["task","deadline","note","communication","hearing","settlement"].includes(activityType)||!["low","medium","high","critical"].includes(priority))return jsonNoStore({error:"بيانات نشاط القضية غير مكتملة"},{status:400});const db=getDb();const matter=await db.query.legalRecords.findFirst({where:eq(legalRecords.id,legalRecordId)});if(!matter)return jsonNoStore({error:"الملف القانوني غير موجود"},{status:404});const now=new Date().toISOString();const[saved]=await db.insert(legalCaseActivities).values({legalRecordId,activityType,title,details:details||null,priority,dueAt,assignedTo,createdBy:actor.user.email,updatedAt:now}).returning();await auditPortalAction({actorEmail:actor.user.email,action:"legal-case-activity-created",entityType:"legal-case-activity",entityId:saved.id,after:saved});await emitPortalNotification({eventType:"legal-case-activity-created",title:activityType==="deadline"?"أضيف موعد قانوني":"أضيف إجراء إلى قضية",message:`${matter.referenceCode} — ${title}`,severity:priority==="critical"?"critical":priority==="high"?"warning":"info",module:"legal",entityType:"legal-record",entityId:legalRecordId,actionView:"legal",targetDepartment:"legal",targetEmail:assignedTo}).catch(()=>undefined);return jsonNoStore({activity:saved},{status:201})}
export async function PATCH(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const actor=await access(true);if(!actor)return jsonNoStore({error:"غير مصرح"},{status:403});const parsed=await readLimitedJson(request,5000);if(!parsed.ok)return parsed.response;const body=parsed.value as Record<string,unknown>;const id=Number(body.id);const status=clean(body.status,20);if(!Number.isInteger(id)||id<1||!["open","in_progress","completed","cancelled"].includes(status))return jsonNoStore({error:"الحالة غير صحيحة"},{status:400});const db=getDb();const before=await db.query.legalCaseActivities.findFirst({where:eq(legalCaseActivities.id,id)});if(!before)return jsonNoStore({error:"الإجراء غير موجود"},{status:404});const now=new Date().toISOString();const[updated]=await db.update(legalCaseActivities).set({status,completedAt:status==="completed"?now:null,updatedAt:now}).where(and(eq(legalCaseActivities.id,id),eq(legalCaseActivities.status,before.status))).returning();if(!updated)return jsonNoStore({error:"تغير الإجراء قبل الحفظ"},{status:409});await auditPortalAction({actorEmail:actor.user.email,action:"legal-case-activity-updated",entityType:"legal-case-activity",entityId:id,before,after:updated});return jsonNoStore({activity:updated})}
