import type { Metadata } from "next";
import PublicPageShell from "@/app/components/PublicPageShell";
import StructuredData from "@/app/components/StructuredData";
import ConstructionRequestForm from "./ConstructionRequestForm";
import ConstructionSectionNav from "./ConstructionSectionNav";
import Link from "next/link";
import { absoluteUrl, SITE } from "@/lib/site";

export const metadata:Metadata={title:"شركة مقاولات وأعمال إنشائية في السعودية | دالي",description:"تنفيذ وإدارة أعمال المباني والتشطيبات والترميم والأعمال المدنية والكهروميكانيكية للمشروعات في مدن المملكة، بعد دراسة النطاق والموقع والبرنامج.",alternates:{canonical:"/construction"},openGraph:{title:"خدمات المقاولات وإدارة المشروعات في السعودية | دالي",description:"مسار واضح من دراسة النطاق والمعاينة والتسعير إلى التنفيذ وضبط الجودة والتسليم.",url:"/construction",locale:"ar_SA",type:"website"}};

const services=["إنشاء وتنفيذ المباني","التشطيبات الداخلية والخارجية","الترميم وإعادة التأهيل","الأعمال المدنية والبنية التحتية","الأعمال الكهربائية والميكانيكية","إدارة المقاولين والبرنامج والتكلفة"];
const schema={"@context":"https://schema.org","@type":"Service",name:"خدمات المقاولات وإدارة المشروعات",serviceType:"مقاولات عامة وأعمال إنشائية",provider:{"@id":`${SITE.url}/#organization`},areaServed:{"@type":"Country",name:"Saudi Arabia"},url:absoluteUrl("/construction"),description:"دراسة وتنفيذ وإدارة أعمال المقاولات للمشروعات في مدن المملكة العربية السعودية بحسب النطاق والجاهزية."};

export default function ConstructionPage(){return <PublicPageShell><StructuredData data={schema}/><ConstructionSectionNav/>
  <section className="inner-hero construction-public-hero"><p className="eyebrow light"><span/>المقاولات وإدارة المشروعات</p><h1>نبني نطاقاً واضحاً،<br/><em>ثم ندير التنفيذ حتى التسليم.</em></h1><p>نبدأ بفهم الموقع والمخرجات والبرنامج والميزانية. بعد ذلك نحدد أسلوب التنفيذ والموارد ونقاط الفحص؛ لأن المشروع الجيد لا يبدأ بوعد عام، بل بنطاق يمكن قياسه وإدارته.</p><a className="btn primary" href="#construction-request">اطلب دراسة مشروع ←</a></section>
  <section className="inner-content construction-public-content"><div className="inner-heading"><p className="eyebrow"><span/>ما الذي ننفذه؟</p><h2>خدمات مقاولات مترابطة، لا أعمال متفرقة بلا مسؤولية</h2><p>نراجع كل طلب بحسب المدينة وطبيعة الموقع والتراخيص والبرنامج. التغطية على مستوى المملكة تعني استقبال ودراسة الطلبات في جميع المناطق، بينما يُؤكد موعد التعبئة والتنفيذ بعد التحقق التشغيلي.</p></div><div className="construction-service-grid">{services.map((service,index)=><article key={service}><span>{String(index+1).padStart(2,"0")}</span><h3>{service}</h3><p>{index===5?"تقارير تقدم، ضبط تغييرات، متابعة تكلفة ومخاطر، ومحاضر استلام واضحة.":"تحديد الكميات والمواصفات ونقاط الجودة والسلامة قبل اعتماد خطة التنفيذ."}</p></article>)}</div></section>
  <section className="construction-method"><div><p className="eyebrow light"><span/>منهج التنفيذ</p><h2>قرار أدق في كل مرحلة</h2></div><ol><li><b>01</b><strong>دراسة أولية</strong><span>الموقع، النطاق، القيود، والموعد المستهدف.</span></li><li><b>02</b><strong>معاينة وتسعير</strong><span>كميات وافتراضات واستثناءات قابلة للمراجعة.</span></li><li><b>03</b><strong>تجهيز وتنفيذ</strong><span>برنامج وموارد وسلامة ونقاط فحص.</span></li><li><b>04</b><strong>ضبط وتسليم</strong><span>تقدم وتغييرات وملاحظات ووثائق إقفال.</span></li></ol></section>
  <section className="construction-hub-links"><Link href="/construction/services"><strong>التخصصات</strong><span>النطاقات والمدخلات والمخرجات</span></Link><Link href="/construction/methodology"><strong>منهج التنفيذ</strong><span>من التأهيل حتى الإقفال</span></Link><Link href="/construction/quality-safety"><strong>الجودة والسلامة</strong><span>الفحوص والمخاطر والإغلاق</span></Link><Link href="/construction/regions"><strong>مناطق الخدمة</strong><span>التغطية في المملكة بضوابط واضحة</span></Link></section>
  <section className="inner-content construction-request-section" id="construction-request"><div className="inner-heading"><p className="eyebrow"><span/>طلب دراسة مشروع</p><h2>أرسل ما تعرفه الآن، وسنحدد ما نحتاجه لاحقاً</h2><p>لا يلزم أن تكون وثائق المشروع مكتملة. اذكر النطاق المتاح والمدينة والموعد، وسيبدأ الفريق بمراجعة أولية قبل طلب المخططات أو جدول الكميات.</p><Link href="/construction/request">فتح صفحة الطلب المستقلة ←</Link></div><ConstructionRequestForm/></section>
  </PublicPageShell>}
