export const supportedLocales = ["ar", "en", "ur"] as const;
export type AppLocale = typeof supportedLocales[number];
export const localeCookieName = "dali_locale";
export function isAppLocale(value: unknown): value is AppLocale { return typeof value === "string" && supportedLocales.includes(value as AppLocale); }
export function localeDirection(locale: AppLocale) { return locale === "en" ? "ltr" : "rtl"; }
export const localeNames: Record<AppLocale,string> = { ar: "العربية", en: "English", ur: "اردو" };

type Translation = { en: string; ur: string };
export const uiTranslations: Record<string,Translation> = {
  "الرئيسية":{en:"Home",ur:"مرکزی صفحہ"},"من نحن":{en:"About us",ur:"ہمارے بارے میں"},"خدماتنا":{en:"Services",ur:"ہماری خدمات"},"المقاولات":{en:"Contracting",ur:"تعمیرات"},"القطاعات":{en:"Sectors",ur:"شعبے"},"مناطق الخدمة":{en:"Service areas",ur:"خدمات کے علاقے"},"رمضان والحج":{en:"Ramadan & Hajj",ur:"رمضان اور حج"},"المعرفة":{en:"Insights",ur:"معلومات"},"اطلب عرض سعر":{en:"Request a quotation",ur:"قیمت کی پیشکش طلب کریں"},"ابحث في الموقع":{en:"Search the website",ur:"ویب سائٹ میں تلاش کریں"},
  "النظام الإداري الداخلي":{en:"Internal Administration System",ur:"اندرونی انتظامی نظام"},"تسجيل الدخول الآمن":{en:"Secure sign in",ur:"محفوظ لاگ اِن"},"رقم الهوية / الإقامة":{en:"National ID / Iqama",ur:"قومی شناخت / اقامہ"},"كلمة المرور":{en:"Password",ur:"پاس ورڈ"},"دخول آمن":{en:"Sign in securely",ur:"محفوظ لاگ اِن"},"نسيت كلمة المرور؟":{en:"Forgot password?",ur:"پاس ورڈ بھول گئے؟"},"تسجيل الخروج":{en:"Sign out",ur:"لاگ آؤٹ"},
  "نظرة عامة":{en:"Overview",ur:"جائزہ"},"إدارة الموظفين":{en:"Employee Management",ur:"ملازمین کا انتظام"},"الإدارة المالية":{en:"Financial Management",ur:"مالی انتظام"},"الشؤون القانونية":{en:"Legal Affairs",ur:"قانونی امور"},"شؤون العمالة":{en:"Workforce Affairs",ur:"افرادی قوت کے امور"},"المبيعات والتشغيل":{en:"Sales & Operations",ur:"فروخت اور آپریشنز"},"المقاولات والمشروعات":{en:"Contracting & Projects",ur:"تعمیرات اور منصوبے"},"المحادثات المباشرة":{en:"Live Conversations",ur:"براہ راست گفتگو"},"مركز المستندات":{en:"Document Center",ur:"دستاویزات مرکز"},"إدارة الموقع الإلكتروني":{en:"Website Management",ur:"ویب سائٹ انتظام"},"إدارة المستخدمين":{en:"User Management",ur:"صارفین کا انتظام"},"إدارة المناديب":{en:"Representative Management",ur:"نمائندگان کا انتظام"},"الإشعارات":{en:"Notifications",ur:"اطلاعات"},"البحث":{en:"Search",ur:"تلاش"},
  "لوحة المتابعة":{en:"Dashboard",ur:"ڈیش بورڈ"},"مركز الإشعارات":{en:"Notification Center",ur:"اطلاعات مرکز"},"الهوية البصرية":{en:"Brand Identity",ur:"برانڈ شناخت"},"إدارة الموقع":{en:"Website Management",ur:"ویب سائٹ انتظام"},"المستخدمون والصلاحيات":{en:"Users & Permissions",ur:"صارفین اور اجازتیں"},"النظام الإداري":{en:"Administration System",ur:"انتظامی نظام"},"أقسام النظام":{en:"System sections",ur:"نظام کے حصے"},"اتصال محمي":{en:"Secure connection",ur:"محفوظ کنکشن"},"تُطبّق الصلاحيات من جهة الخادم.":{en:"Permissions are enforced by the server.",ur:"اجازتیں سرور کی جانب سے نافذ ہوتی ہیں۔"},"إغلاق القائمة":{en:"Close menu",ur:"مینو بند کریں"},"فتح القائمة":{en:"Open menu",ur:"مینو کھولیں"},"فتح مركز الإشعارات":{en:"Open notification center",ur:"اطلاعات مرکز کھولیں"},"شركة دالي للتشغيل والصيانة":{en:"Dally Operation & Maintenance Co.",ur:"ڈالی آپریشن اینڈ مینٹیننس کمپنی"},
  "إضافة":{en:"Add",ur:"شامل کریں"},"حفظ":{en:"Save",ur:"محفوظ کریں"},"إلغاء":{en:"Cancel",ur:"منسوخ کریں"},"حذف":{en:"Delete",ur:"حذف کریں"},"تعديل":{en:"Edit",ur:"ترمیم کریں"},"اعتماد":{en:"Approve",ur:"منظور کریں"},"رفض":{en:"Reject",ur:"مسترد کریں"},"تنزيل":{en:"Download",ur:"ڈاؤن لوڈ"},"مشاركة":{en:"Share",ur:"شیئر کریں"},"إغلاق":{en:"Close",ur:"بند کریں"},"عرض الحالة":{en:"View status",ur:"حالت دیکھیں"},"جارٍ التحميل...":{en:"Loading...",ur:"لوڈ ہو رہا ہے..."},"لا توجد نتائج":{en:"No results",ur:"کوئی نتائج نہیں"},"غير محدد":{en:"Not specified",ur:"متعین نہیں"},"نشط":{en:"Active",ur:"فعال"},"غير نشط":{en:"Inactive",ur:"غیر فعال"},"معتمد":{en:"Approved",ur:"منظور شدہ"},"مسودة":{en:"Draft",ur:"مسودہ"},"مرفوض":{en:"Rejected",ur:"مسترد"},"ملغى":{en:"Cancelled",ur:"منسوخ"},
  "بحث":{en:"Search",ur:"تلاش"},"تحديث البيانات":{en:"Refresh data",ur:"ڈیٹا تازہ کریں"},"التفاصيل":{en:"Details",ur:"تفصیلات"},"الإجراءات":{en:"Actions",ur:"کارروائیاں"},"الحالة":{en:"Status",ur:"حالت"},"الاسم":{en:"Name",ur:"نام"},"البريد الإلكتروني":{en:"Email",ur:"ای میل"},"رقم الجوال":{en:"Mobile number",ur:"موبائل نمبر"},"التاريخ":{en:"Date",ur:"تاریخ"},"ملاحظات":{en:"Notes",ur:"نوٹس"},"التالي":{en:"Next",ur:"اگلا"},"السابق":{en:"Previous",ur:"پچھلا"},"تأكيد":{en:"Confirm",ur:"تصدیق کریں"},"إرسال":{en:"Send",ur:"بھیجیں"},"طباعة":{en:"Print",ur:"پرنٹ"},"معاينة":{en:"Preview",ur:"پیش منظر"},
  "العملاء والفرص":{en:"Clients & Opportunities",ur:"گاہک اور مواقع"},"عروض الأسعار":{en:"Quotations",ur:"قیمت کی پیشکشیں"},"العقود والدفعات":{en:"Contracts & Payments",ur:"معاہدے اور ادائیگیاں"},"أوامر التشغيل":{en:"Work Orders",ur:"کام کے احکامات"},"الدوام":{en:"Attendance",ur:"حاضری"},"إنشاء عقد":{en:"Create contract",ur:"معاہدہ بنائیں"},"إنشاء عرض سعر":{en:"Create quotation",ur:"قیمت کی پیشکش بنائیں"},"اعتماد عرض السعر":{en:"Approve quotation",ur:"قیمت کی پیشکش منظور کریں"},"مشاركة واتساب":{en:"Share on WhatsApp",ur:"واٹس ایپ پر شیئر کریں"},"تحويل إلى عقد":{en:"Convert to contract",ur:"معاہدے میں تبدیل کریں"},
  "إدارة المناديب والطلبات":{en:"Representatives & Requests",ur:"نمائندگان اور درخواستیں"},"مناديب المبيعات":{en:"Sales representatives",ur:"فروخت کے نمائندے"},"مناديب المشتريات":{en:"Purchasing representatives",ur:"خریداری کے نمائندے"},"صندوق طلبات المناديب":{en:"Representative Request Inbox",ur:"نمائندہ درخواست ان باکس"},"إرسال طلب مندوب":{en:"Submit representative request",ur:"نمائندہ درخواست بھیجیں"},"إضافة مندوب":{en:"Add representative",ur:"نمائندہ شامل کریں"},"طلب تعديل":{en:"Request changes",ur:"ترمیم طلب کریں"},"رفض نهائي":{en:"Final rejection",ur:"حتمی مسترد"},
  "اللغة":{en:"Language",ur:"زبان"},"اختيار اللغة":{en:"Choose language",ur:"زبان منتخب کریں"},"تغيير اللغة":{en:"Change language",ur:"زبان تبدیل کریں"},"حفظ اللغة":{en:"Save language",ur:"زبان محفوظ کریں"},"العربية":{en:"Arabic",ur:"عربی"},"الإنجليزية":{en:"English",ur:"انگریزی"},"الأوردية":{en:"Urdu",ur:"اردو"},
  "جميع الحقوق محفوظة.":{en:"All rights reserved.",ur:"جملہ حقوق محفوظ ہیں۔"},"الشروط والأحكام":{en:"Terms & Conditions",ur:"شرائط و ضوابط"},"سياسة الخصوصية":{en:"Privacy Policy",ur:"رازداری کی پالیسی"},"الأسئلة الشائعة":{en:"FAQ",ur:"عمومی سوالات"},"الوظائف":{en:"Careers",ur:"ملازمتیں"},"الشركة":{en:"Company",ur:"کمپنی"},"الخدمات":{en:"Services",ur:"خدمات"},"التواصل والحوكمة":{en:"Contact & Governance",ur:"رابطہ اور گورننس"}
};
Object.assign(uiTranslations,{
  "العميل":{en:"Client",ur:"گاہک"},"العملاء":{en:"Clients",ur:"گاہک"},"النوع":{en:"Type",ur:"قسم"},"المرجع":{en:"Reference",ur:"حوالہ"},"الإجراء":{en:"Action",ur:"کارروائی"},"المسؤول":{en:"Owner",ur:"ذمہ دار"},"المبلغ":{en:"Amount",ur:"رقم"},"القيمة":{en:"Value",ur:"قدر"},"البيان":{en:"Description",ur:"تفصیل"},"الملف":{en:"File",ur:"فائل"},"المستند":{en:"Document",ur:"دستاویز"},"نوع المستند":{en:"Document type",ur:"دستاویز کی قسم"},"نوع الملف":{en:"File type",ur:"فائل کی قسم"},
  "العامل":{en:"Worker",ur:"کارکن"},"الموظف":{en:"Employee",ur:"ملازم"},"موظف":{en:"Employee",ur:"ملازم"},"المهنة":{en:"Profession",ur:"پیشہ"},"الجنسية":{en:"Nationality",ur:"قومیت"},"القسم":{en:"Department",ur:"شعبہ"},"الإدارة":{en:"Management",ur:"انتظامیہ"},"الدور":{en:"Role",ur:"کردار"},"المسمى":{en:"Title",ur:"عہدہ"},"المسمى الوظيفي":{en:"Job title",ur:"ملازمت کا عنوان"},"الرقم الوظيفي":{en:"Employee number",ur:"ملازم نمبر"},"البريد الوظيفي":{en:"Work email",ur:"دفتری ای میل"},"تاريخ الالتحاق":{en:"Joining date",ur:"شمولیت کی تاریخ"},
  "العقد":{en:"Contract",ur:"معاہدہ"},"عقد":{en:"Contract",ur:"معاہدہ"},"العقد المرتبط":{en:"Related contract",ur:"متعلقہ معاہدہ"},"نهاية العقد":{en:"Contract end",ur:"معاہدے کا اختتام"},"الدفعة":{en:"Installment",ur:"قسط"},"الاستحقاق":{en:"Due",ur:"واجب الادا"},"تاريخ الاستحقاق":{en:"Due date",ur:"واجب الادا تاریخ"},"تاريخ الإصدار":{en:"Issue date",ur:"اجراء کی تاریخ"},"نسبة الضريبة %":{en:"Tax rate %",ur:"ٹیکس کی شرح %"},"تطبيق الضريبة":{en:"Apply tax",ur:"ٹیکس لاگو کریں"},"بدون ضريبة":{en:"Tax exempt",ur:"بغیر ٹیکس"},
  "الحساب البنكي":{en:"Bank account",ur:"بینک اکاؤنٹ"},"الحسابات البنكية":{en:"Bank accounts",ur:"بینک اکاؤنٹس"},"البنك":{en:"Bank",ur:"بینک"},"اسم البنك":{en:"Bank name",ur:"بینک کا نام"},"رقم الآيبان":{en:"IBAN",ur:"آئی بان"},"نقدي":{en:"Cash",ur:"نقد"},"سند قبض":{en:"Receipt voucher",ur:"وصولی واؤچر"},"سند صرف":{en:"Payment voucher",ur:"ادائیگی واؤچر"},"دليل الحسابات":{en:"Chart of accounts",ur:"اکاؤنٹس چارٹ"},"ميزان المراجعة":{en:"Trial balance",ur:"ٹرائل بیلنس"},"مركز التكلفة":{en:"Cost center",ur:"لاگت مرکز"},"الإيرادات":{en:"Revenue",ur:"آمدنی"},
  "المدينة":{en:"City",ur:"شہر"},"المنطقة":{en:"Region",ur:"علاقہ"},"العنوان":{en:"Address",ur:"پتہ"},"موقع العمل":{en:"Work location",ur:"کام کی جگہ"},"موقع تقديم الخدمة":{en:"Service location",ur:"خدمت کی جگہ"},"المشروع":{en:"Project",ur:"منصوبہ"},"مدير المشروع":{en:"Project manager",ur:"پروجیکٹ مینیجر"},"نوع المشروع":{en:"Project type",ur:"منصوبے کی قسم"},"اختر المشروع":{en:"Select project",ur:"منصوبہ منتخب کریں"},"اختر المدينة":{en:"Select city",ur:"شہر منتخب کریں"},
  "الجهة":{en:"Entity",ur:"ادارہ"},"الجهة المستفيدة":{en:"Beneficiary",ur:"فائدہ اٹھانے والا ادارہ"},"قطاع الأعمال":{en:"Business sector",ur:"کاروباری شعبہ"},"الفرصة":{en:"Opportunity",ur:"موقع"},"المندوب":{en:"Representative",ur:"نمائندہ"},"نوع المندوب":{en:"Representative type",ur:"نمائندے کی قسم"},"دون مندوب":{en:"No representative",ur:"بغیر نمائندہ"},
  "نشط":{en:"Active",ur:"فعال"},"موقوف":{en:"Suspended",ur:"معطل"},"معلق":{en:"Pending",ur:"زیر التوا"},"جارية":{en:"In progress",ur:"جاری"},"مغلقة":{en:"Closed",ur:"بند"},"منشور":{en:"Published",ur:"شائع شدہ"},"عالية":{en:"High",ur:"اعلیٰ"},"حاضر":{en:"Present",ur:"حاضر"},"غائب":{en:"Absent",ur:"غیر حاضر"},"إجازة":{en:"Leave",ur:"رخصت"},"مرضي":{en:"Sick leave",ur:"بیماری کی رخصت"},
  "اختر الموظف":{en:"Select employee",ur:"ملازم منتخب کریں"},"اختر العامل":{en:"Select worker",ur:"کارکن منتخب کریں"},"إلزامي":{en:"Required",ur:"لازمی"},"أخرى":{en:"Other",ur:"دیگر"},"من":{en:"From",ur:"سے"},"إلى":{en:"To",ur:"تک"},"الوحدة":{en:"Unit",ur:"اکائی"},"التصنيف":{en:"Category",ur:"زمرہ"},"رقم الجوال":{en:"Mobile number",ur:"موبائل نمبر"},"الجوال":{en:"Mobile",ur:"موبائل"},"الاسم الكامل":{en:"Full name",ur:"مکمل نام"},"تنزيل PDF":{en:"Download PDF",ur:"پی ڈی ایف ڈاؤن لوڈ"},"تعليم الكل كمقروء":{en:"Mark all as read",ur:"سب کو پڑھا ہوا نشان زد کریں"},"تنتظر الرد":{en:"Awaiting reply",ur:"جواب کا انتظار"},"يحتاج إجراء":{en:"Action required",ur:"کارروائی درکار"}
});
export function translateUi(value:string,locale:AppLocale){if(locale==="ar")return value;return uiTranslations[value]?.[locale]||value;}
