export const supportedLocales = ["ar", "en", "ur"] as const;
export type AppLocale = typeof supportedLocales[number];
export const localeCookieName = "dali_locale";
export function isAppLocale(value: unknown): value is AppLocale { return typeof value === "string" && supportedLocales.includes(value as AppLocale); }
export function localeDirection(locale: AppLocale) { return locale === "en" ? "ltr" : "rtl"; }
export const localeNames: Record<AppLocale,string> = { ar: "العربية", en: "English", ur: "اردو" };

type Translation = { en: string; ur: string };
export const uiTranslations: Record<string,Translation> = {
  "الرئيسية":{en:"Home",ur:"مرکزی صفحہ"},"من نحن":{en:"About us",ur:"ہمارے بارے میں"},"خدماتنا":{en:"Services",ur:"ہماری خدمات"},"المقاولات":{en:"Contracting",ur:"تعمیرات"},"القطاعات":{en:"Sectors",ur:"شعبے"},"مناطق الخدمة":{en:"Service areas",ur:"خدمات کے علاقے"},"رمضان والحج":{en:"Ramadan & Hajj",ur:"رمضان اور حج"},"المعرفة":{en:"Insights",ur:"معلومات"},"اطلب عرض سعر":{en:"Request a quotation",ur:"قیمت کی پیشکش طلب کریں"},"ابحث في الموقع":{en:"Search the website",ur:"ویب سائٹ میں تلاش کریں"},
  "النظام الإداري الداخلي":{en:"Internal Administration System",ur:"اندرونی انتظامی نظام"},"تسجيل الدخول الآمن":{en:"Secure sign in",ur:"محفوظ لاگ اِن"},"رقم الهوية / الإقامة":{en:"National ID / Iqama",ur:"قومی شناخت / اقامہ"},"كلمة المرور":{en:"Password",ur:"پاس ورڈ"},"دخول آمن":{en:"Sign in securely",ur:"محفوظ لاگ اِن"},"نسيت كلمة المرور؟":{en:"Forgot password?",ur:"پاس ورڈ بھول گئے؟"},"تسجيل الخروج":{en:"Sign out",ur:"لاگ آؤٹ"},
  "نظرة عامة":{en:"Overview",ur:"جائزہ"},"إدارة الموظفين":{en:"Employee Management",ur:"ملازمین کا انتظام"},"الإدارة المالية":{en:"Financial Management",ur:"مالی انتظام"},"الشؤون القانونية":{en:"Legal Affairs",ur:"قانونی امور"},"شؤون العمالة":{en:"Workforce Affairs",ur:"افرادی قوت کے امور"},"المبيعات والتشغيل":{en:"Sales & Operations",ur:"فروخت اور آپریشنز"},"المقاولات والمشروعات":{en:"Contracting & Projects",ur:"تعمیرات اور منصوبے"},"المحادثات المباشرة":{en:"Live Conversations",ur:"براہ راست گفتگو"},"مركز المستندات":{en:"Document Center",ur:"دستاویزات مرکز"},"إدارة الموقع الإلكتروني":{en:"Website Management",ur:"ویب سائٹ انتظام"},"إدارة المستخدمين":{en:"User Management",ur:"صارفین کا انتظام"},"إدارة المناديب":{en:"Representative Management",ur:"نمائندگان کا انتظام"},"الإشعارات":{en:"Notifications",ur:"اطلاعات"},"البحث":{en:"Search",ur:"تلاش"},
  "لوحة المتابعة":{en:"Dashboard",ur:"ڈیش بورڈ"},"مركز الإشعارات":{en:"Notification Center",ur:"اطلاعات مرکز"},"الهوية البصرية":{en:"Brand Identity",ur:"برانڈ شناخت"},"إدارة الموقع":{en:"Website Management",ur:"ویب سائٹ انتظام"},"المستخدمون والصلاحيات":{en:"Users & Permissions",ur:"صارفین اور اجازتیں"},"النظام الإداري":{en:"Administration System",ur:"انتظامی نظام"},"أقسام النظام":{en:"System sections",ur:"نظام کے حصے"},"اتصال محمي":{en:"Secure connection",ur:"محفوظ کنکشن"},"تُطبّق الصلاحيات من جهة الخادم.":{en:"Permissions are enforced by the server.",ur:"اجازتیں سرور کی جانب سے نافذ ہوتی ہیں۔"},"إغلاق القائمة":{en:"Close menu",ur:"مینو بند کریں"},"فتح القائمة":{en:"Open menu",ur:"مینو کھولیں"},"فتح مركز الإشعارات":{en:"Open notification center",ur:"اطلاعات مرکز کھولیں"},"شركة دالي للتشغيل والصيانة":{en:"Dally Operation & Maintenance Co.",ur:"ڈالی آپریشن اینڈ مینٹیننس کمپنی"},
  "إضافة":{en:"Add",ur:"شامل کریں"},"حفظ":{en:"Save",ur:"محفوظ کریں"},"إلغاء":{en:"Cancel",ur:"منسوخ کریں"},"حذف":{en:"Delete",ur:"حذف کریں"},"تعديل":{en:"Edit",ur:"ترمیم کریں"},"اعتماد":{en:"Approve",ur:"منظور کریں"},"رفض":{en:"Reject",ur:"مسترد کریں"},"تنزيل":{en:"Download",ur:"ڈاؤن لوڈ"},"مشاركة":{en:"Share",ur:"شیئر کریں"},"إغلاق":{en:"Close",ur:"بند کریں"},"عرض الحالة":{en:"View status",ur:"حالت دیکھیں"},"جارٍ التحميل...":{en:"Loading...",ur:"لوڈ ہو رہا ہے..."},"لا توجد نتائج":{en:"No results",ur:"کوئی نتائج نہیں"},"غير محدد":{en:"Not specified",ur:"متعین نہیں"},"نشط":{en:"Active",ur:"فعال"},"غير نشط":{en:"Inactive",ur:"غیر فعال"},"معتمد":{en:"Approved",ur:"منظور شدہ"},"مسودة":{en:"Draft",ur:"مسودہ"},"مرفوض":{en:"Rejected",ur:"مسترد"},"ملغى":{en:"Cancelled",ur:"منسوخ"},
  "بحث":{en:"Search",ur:"تلاش"},"تحديث البيانات":{en:"Refresh data",ur:"ڈیٹا تازہ کریں"},"التفاصيل":{en:"Details",ur:"تفصیلات"},"الإجراءات":{en:"Actions",ur:"کارروائیاں"},"الحالة":{en:"Status",ur:"حالت"},"الاسم":{en:"Name",ur:"نام"},"البريد الإلكتروني":{en:"Email",ur:"ای میل"},"رقم الجوال":{en:"Mobile number",ur:"موبائل نمبر"},"التاريخ":{en:"Date",ur:"تاریخ"},"ملاحظات":{en:"Notes",ur:"نوٹس"},"التالي":{en:"Next",ur:"اگلا"},"السابق":{en:"Previous",ur:"پچھلا"},"تأكيد":{en:"Confirm",ur:"تصدیق کریں"},"إرسال":{en:"Send",ur:"بھیجیں"},"طباعة":{en:"Print",ur:"پرنٹ"},"معاينة":{en:"Preview",ur:"پیش منظر"},
  "العملاء والفرص":{en:"Clients & Opportunities",ur:"گاہک اور مواقع"},"عروض الأسعار":{en:"Quotations",ur:"قیمت کی پیشکشیں"},"العقود والدفعات":{en:"Contracts & Payments",ur:"معاہدے اور ادائیگیاں"},"أوامر التشغيل":{en:"Work Orders",ur:"کام کے احکامات"},"الدوام":{en:"Attendance",ur:"حاضری"},"إنشاء عقد":{en:"Create contract",ur:"معاہدہ بنائیں"},"إنشاء عرض سعر":{en:"Create quotation",ur:"قیمت کی پیشکش بنائیں"},"اعتماد عرض السعر":{en:"Approve quotation",ur:"قیمت کی پیشکش منظور کریں"},"مشاركة واتساب":{en:"Share on WhatsApp",ur:"واٹس ایپ پر شیئر کریں"},"تحويل إلى عقد":{en:"Convert to contract",ur:"معاہدے میں تبدیل کریں"},
  "إدارة المناديب والطلبات":{en:"Representatives & Requests",ur:"نمائندگان اور درخواستیں"},"مناديب المبيعات":{en:"Sales representatives",ur:"فروخت کے نمائندے"},"مناديب المشتريات":{en:"Purchasing representatives",ur:"خریداری کے نمائندے"},"صندوق طلبات المناديب":{en:"Representative Request Inbox",ur:"نمائندہ درخواست ان باکس"},"إرسال طلب مندوب":{en:"Submit representative request",ur:"نمائندہ درخواست بھیجیں"},"إضافة مندوب":{en:"Add representative",ur:"نمائندہ شامل کریں"},"طلب تعديل":{en:"Request changes",ur:"ترمیم طلب کریں"},"رفض نهائي":{en:"Final rejection",ur:"حتمی مسترد"},
  "اللغة":{en:"Language",ur:"زبان"},"اختيار اللغة":{en:"Choose language",ur:"زبان منتخب کریں"},"تغيير اللغة":{en:"Change language",ur:"زبان تبدیل کریں"},"حفظ اللغة":{en:"Save language",ur:"زبان محفوظ کریں"},"العربية":{en:"Arabic",ur:"عربی"},"الإنجليزية":{en:"English",ur:"انگریزی"},"الأوردية":{en:"Urdu",ur:"اردو"},
  "جميع الحقوق محفوظة.":{en:"All rights reserved.",ur:"جملہ حقوق محفوظ ہیں۔"},"الشروط والأحكام":{en:"Terms & Conditions",ur:"شرائط و ضوابط"},"سياسة الخصوصية":{en:"Privacy Policy",ur:"رازداری کی پالیسی"},"الأسئلة الشائعة":{en:"FAQ",ur:"عمومی سوالات"},"الوظائف":{en:"Careers",ur:"ملازمتیں"},"الشركة":{en:"Company",ur:"کمپنی"},"الخدمات":{en:"Services",ur:"خدمات"},"التواصل والحوكمة":{en:"Contact & Governance",ur:"رابطہ اور گورننس"}
};
export function translateUi(value:string,locale:AppLocale){if(locale==="ar")return value;return uiTranslations[value]?.[locale]||value;}
