"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Line = { id: number; code: string; nameAr: string; publicStatus: string };
type Region = { id: number; nameAr: string };
type City = { id: number; regionId: number; nameAr: string; seoStatus: string };
type Coverage = { id: number; cityId: number; businessLineId: number; availability: string; capacityLevel: string; mobilizationDays: number | null; publicApproved: boolean; updatedAt: string };
type Opportunity = { id: number; opportunityCode: string; clientName: string; title: string; cityId: number | null; projectType: string; scopeSummary: string; estimatedValueHalalas: number | null; bidDueDate: string | null; stage: string; probabilityBps: number; ownerEmail: string; updatedAt: string };
type Project = { id: number; projectCode: string; opportunityId: number | null; clientName: string; title: string; cityId: number | null; projectType: string; contractValueHalalas: number; budgetHalalas: number; startDate: string; plannedEndDate: string; progressBps: number; status: string; riskLevel: string; managerEmail: string; costCenterCode: string };
type Data = { lines: Line[]; regions: Region[]; cities: City[]; coverage: Coverage[]; opportunities: Opportunity[]; projects: Project[]; canWrite: boolean };
type Tab = "dashboard" | "opportunities" | "projects" | "coverage";

const stageLabels: Record<string,string> = { new:"جديدة", qualified:"مؤهلة", survey:"معاينة", estimating:"تسعير", review:"مراجعة", submitted:"مقدمة", negotiation:"تفاوض", won:"فوز", lost:"خسارة", declined:"اعتذار" };
const projectStatusLabels: Record<string,string> = { mobilizing:"تجهيز", active:"نشط", on_hold:"موقوف مؤقتًا", substantial_completion:"إنجاز جوهري", defects_liability:"فترة ضمان", closed:"مغلق", cancelled:"ملغى" };
const availabilityLabels: Record<string,string> = { available:"متاحة", conditional:"مشروطة", unavailable:"غير متاحة" };
const money = (halalas: number | null) => new Intl.NumberFormat("ar-SA", { style:"currency", currency:"SAR", maximumFractionDigits:0 }).format((halalas || 0) / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("ar-SA", { day:"numeric", month:"short", year:"numeric" }).format(new Date(`${value}T00:00:00`)) : "غير محدد";

export default function ConstructionWorkspace() {
  const [data,setData] = useState<Data | null>(null);
  const [tab,setTab] = useState<Tab>("dashboard");
  const [loading,setLoading] = useState(true);
  const [busy,setBusy] = useState("");
  const [notice,setNotice] = useState("");
  const [error,setError] = useState("");
  const [query,setQuery] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response=await fetch("/api/portal/construction",{cache:"no-store"}); const result=await response.json() as Data & {error?:string}; if(!response.ok) throw new Error(result.error||"تعذر التحميل"); setData(result); }
    catch (e) { setError(e instanceof Error?e.message:"تعذر التحميل"); }
    finally { setLoading(false); }
  },[]);
  useEffect(()=>{let active=true;fetch("/api/portal/construction",{cache:"no-store"}).then(async response=>{const result=await response.json() as Data & {error?:string};if(!response.ok)throw new Error(result.error||"تعذر التحميل");if(active)setData(result)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"تعذر التحميل")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  async function act(action:string,payload:Record<string,unknown>,key:string) {
    setBusy(key); setError(""); setNotice("");
    try { const response=await fetch("/api/portal/construction",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,payload})}); const result=await response.json() as {error?:string}; if(!response.ok) throw new Error(result.error||"تعذر الحفظ"); setNotice("تم الحفظ وتحديث السجل بنجاح."); await load(); return true; }
    catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ"); return false;} finally{setBusy("");}
  }
  const citiesById=useMemo(()=>new Map((data?.cities||[]).map(item=>[item.id,item])),[data]);
  const regionsById=useMemo(()=>new Map((data?.regions||[]).map(item=>[item.id,item])),[data]);
  const q=query.trim().toLowerCase();
  const opportunities=(data?.opportunities||[]).filter(item=>!q||`${item.opportunityCode} ${item.title} ${item.clientName} ${item.projectType}`.toLowerCase().includes(q));
  const projects=(data?.projects||[]).filter(item=>!q||`${item.projectCode} ${item.title} ${item.clientName} ${item.projectType}`.toLowerCase().includes(q));
  const activeProjects=(data?.projects||[]).filter(item=>["mobilizing","active","on_hold"].includes(item.status));
  const pipeline=(data?.opportunities||[]).filter(item=>!["won","lost","declined"].includes(item.stage)).reduce((sum,item)=>sum+(item.estimatedValueHalalas||0),0);
  const contractValue=activeProjects.reduce((sum,item)=>sum+item.contractValueHalalas,0);
  const budget=activeProjects.reduce((sum,item)=>sum+item.budgetHalalas,0);
  if(loading&&!data) return <section className="construction-shell"><div className="construction-loading">جارٍ تحميل قطاع المقاولات...</div></section>;
  if(!data) return <section className="construction-shell"><div className="construction-alert error">{error||"تعذر تحميل الوحدة"}<button onClick={()=>void load()}>إعادة المحاولة</button></div></section>;
  return <section className="construction-shell">
    <header className="construction-head"><div><p>قطاع أعمال مستقل</p><h1>إدارة المقاولات والمشروعات</h1><span>من الفرصة والمعاينة إلى المشروع ومركز التكلفة، مع تغطية تشغيلية موثقة لمدن المملكة.</span></div><div className="construction-head-badge"><strong>{activeProjects.length}</strong><span>مشروع قائم</span></div></header>
    {(error||notice)&&<div className={`construction-alert ${error?"error":"success"}`}>{error||notice}<button onClick={()=>{setError("");setNotice("")}}>×</button></div>}
    <nav className="construction-tabs" aria-label="أقسام المقاولات">{([['dashboard','لوحة المحفظة'],['opportunities','الفرص والمناقصات'],['projects','المشروعات'],['coverage','تغطية المملكة']] as [Tab,string][]).map(([value,label])=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{label}</button>)}</nav>
    {tab==="dashboard"&&<><section className="construction-metrics"><article><span>قيمة الفرص المفتوحة</span><strong>{money(pipeline)}</strong><small>{data.opportunities.filter(i=>!["won","lost","declined"].includes(i.stage)).length} فرصة</small></article><article><span>قيمة العقود القائمة</span><strong>{money(contractValue)}</strong><small>{activeProjects.length} مشروع</small></article><article><span>الميزانية المسجلة</span><strong>{money(budget)}</strong><small>مرتبطة بمراكز التكلفة</small></article><article><span>مدن ذات تغطية معتمدة</span><strong>{new Set(data.coverage.filter(i=>i.publicApproved&&i.availability!=="unavailable").map(i=>i.cityId)).size}</strong><small>لا تُنشر تغطية غير مراجعة</small></article></section><section className="construction-grid"><article className="construction-card"><header><div><h2>الفرص الأقرب للإجراء</h2><p>حسب مرحلة التقدم وموعد تقديم العرض</p></div><button onClick={()=>setTab("opportunities")}>فتح الكل</button></header><div className="construction-list">{data.opportunities.filter(i=>!["won","lost","declined"].includes(i.stage)).slice(0,6).map(i=><div key={i.id}><span className={`construction-state ${i.stage}`}>{stageLabels[i.stage]}</span><p><strong>{i.title}</strong><small>{i.clientName} · {citiesById.get(i.cityId||0)?.nameAr||"مدينة غير محددة"}</small></p><b>{money(i.estimatedValueHalalas)}</b></div>)}{!data.opportunities.length&&<p className="construction-empty">لا توجد فرص مسجلة بعد.</p>}</div></article><article className="construction-card"><header><div><h2>صحة التغطية</h2><p>سجلات تشغيلية تحتاج مراجعة قبل نشرها</p></div><button onClick={()=>setTab("coverage")}>إدارة التغطية</button></header><div className="coverage-health"><strong>{data.coverage.filter(i=>!i.publicApproved).length}</strong><p>سجل غير معتمد للنشر</p><span>يمنع النظام تحويل التغطية التشغيلية إلى ادعاء عام دون اعتماد مدير النظام.</span></div></article></section></>}
    {tab==="opportunities"&&<><WorkspaceTools query={query} setQuery={setQuery} placeholder="ابحث برقم الفرصة أو العميل أو نوع المشروع"/>{data.canWrite&&<OpportunityForm cities={data.cities} busy={busy==="create-opportunity"} onSubmit={async form=>{const ok=await act("create-opportunity",Object.fromEntries(new FormData(form).entries()),"create-opportunity");if(ok)form.reset();}}/>}<section className="construction-card"><header><div><h2>مسار الفرص والمناقصات</h2><p>{opportunities.length} سجل مطابق</p></div></header><div className="construction-table-wrap"><table className="construction-table"><thead><tr><th>الفرصة</th><th>العميل والموقع</th><th>القيمة</th><th>موعد العرض</th><th>المرحلة</th><th>الإجراء</th></tr></thead><tbody>{opportunities.map(item=><tr key={item.id}><td><strong>{item.opportunityCode}</strong><span>{item.title}</span></td><td><strong>{item.clientName}</strong><span>{citiesById.get(item.cityId||0)?.nameAr||"غير محددة"} · {item.projectType}</span></td><td>{money(item.estimatedValueHalalas)}</td><td>{date(item.bidDueDate)}</td><td><span className={`construction-state ${item.stage}`}>{stageLabels[item.stage]}</span></td><td>{data.canWrite?<select value={item.stage} disabled={busy===`stage-${item.id}`} onChange={e=>void act("update-opportunity-stage",{id:item.id,stage:e.target.value},`stage-${item.id}`)}>{Object.entries(stageLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:"قراءة فقط"}</td></tr>)}</tbody></table>{!opportunities.length&&<p className="construction-empty">لا توجد فرص مطابقة.</p>}</div></section></>}
    {tab==="projects"&&<><WorkspaceTools query={query} setQuery={setQuery} placeholder="ابحث برقم المشروع أو العميل أو النوع"/>{data.canWrite&&<ProjectForm opportunities={data.opportunities.filter(i=>i.stage==="won"&&!data.projects.some(p=>p.opportunityId===i.id))} busy={busy==="create-project"} onSubmit={async form=>{const values:Record<string,unknown>=Object.fromEntries(new FormData(form).entries()); values.contractValueHalalas=Math.round(Number(values.contractValueHalalas||0)*100); values.budgetHalalas=Math.round(Number(values.budgetHalalas||0)*100); const ok=await act("create-project-from-opportunity",values,"create-project");if(ok)form.reset();}}/>}<section className="project-cards">{projects.map(item=><article key={item.id}><header><span className={`risk ${item.riskLevel}`}>{item.riskLevel==="low"?"مخاطر منخفضة":item.riskLevel==="medium"?"مخاطر متوسطة":"مخاطر مرتفعة"}</span><b>{item.projectCode}</b></header><h2>{item.title}</h2><p>{item.clientName} · {citiesById.get(item.cityId||0)?.nameAr||"غير محددة"}</p><div className="progress"><span style={{width:`${item.progressBps/100}%`}}/></div><dl><div><dt>الإنجاز</dt><dd>{item.progressBps/100}%</dd></div><div><dt>الحالة</dt><dd>{projectStatusLabels[item.status]}</dd></div><div><dt>قيمة العقد</dt><dd>{money(item.contractValueHalalas)}</dd></div><div><dt>النهاية المخططة</dt><dd>{date(item.plannedEndDate)}</dd></div><div><dt>مركز التكلفة</dt><dd>{item.costCenterCode}</dd></div><div><dt>مدير المشروع</dt><dd>{item.managerEmail}</dd></div></dl></article>)}{!projects.length&&<p className="construction-empty">لا توجد مشروعات مطابقة.</p>}</section></>}
    {tab==="coverage"&&<><section className="coverage-summary">{data.regions.map(region=>{const regionCities=data.cities.filter(c=>c.regionId===region.id);const active=new Set(data.coverage.filter(c=>c.publicApproved&&c.availability!=="unavailable"&&regionCities.some(city=>city.id===c.cityId)).map(c=>c.cityId)).size;return <article key={region.id}><strong>{region.nameAr}</strong><span>{active}/{regionCities.length} مدن معتمدة</span></article>})}</section>{data.canWrite&&<CoverageForm cities={data.cities} lines={data.lines} busy={busy==="coverage"} onSubmit={async form=>{const raw=Object.fromEntries(new FormData(form).entries());await act("upsert-coverage",{...raw,publicApproved:raw.publicApproved==="on"},"coverage");}}/>}<section className="construction-card"><header><div><h2>سجل القدرة التشغيلية</h2><p>المنطقة والمدينة والخدمة وحالة اعتماد النشر</p></div></header><div className="construction-table-wrap"><table className="construction-table"><thead><tr><th>المدينة</th><th>المنطقة</th><th>قطاع الأعمال</th><th>القدرة</th><th>التعبئة</th><th>النشر</th></tr></thead><tbody>{data.coverage.map(item=>{const city=citiesById.get(item.cityId);return <tr key={item.id}><td><strong>{city?.nameAr}</strong></td><td>{regionsById.get(city?.regionId||0)?.nameAr}</td><td>{data.lines.find(l=>l.id===item.businessLineId)?.nameAr}</td><td>{availabilityLabels[item.availability]} · {item.capacityLevel}</td><td>{item.mobilizationDays==null?"حسب المراجعة":`${item.mobilizationDays} يوم`}</td><td><span className={`publish-state ${item.publicApproved?"yes":"no"}`}>{item.publicApproved?"معتمد":"داخلي فقط"}</span></td></tr>})}</tbody></table>{!data.coverage.length&&<p className="construction-empty">لم تُسجل تغطية تشغيلية بعد.</p>}</div></section></>}
  </section>;
}

function WorkspaceTools({query,setQuery,placeholder}:{query:string;setQuery:(v:string)=>void;placeholder:string}){return <div className="construction-tools"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label></div>}
function OpportunityForm({cities,busy,onSubmit}:{cities:City[];busy:boolean;onSubmit:(form:HTMLFormElement)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const field=e.currentTarget.elements.namedItem("estimatedValueHalalas") as HTMLInputElement|null;if(field&&field.value)field.value=String(Math.round(Number(field.value)*100));onSubmit(e.currentTarget)}return <details className="construction-form" open><summary>إضافة فرصة مقاولات فعلية</summary><form onSubmit={submit}><label>اسم الفرصة<input name="title" required minLength={3}/></label><label>العميل<input name="clientName" required minLength={2}/></label><label>المدينة<select name="cityId" required><option value="">اختر المدينة</option>{cities.map(c=><option value={c.id} key={c.id}>{c.nameAr}</option>)}</select></label><label>نوع المشروع<input name="projectType" required placeholder="مباني، تشطيبات، أعمال مدنية..."/></label><label>القيمة التقديرية (ريال)<input name="estimatedValueHalalas" type="number" min="0" step="1"/></label><label>موعد تقديم العرض<input name="bidDueDate" type="date"/></label><label>تاريخ البدء المتوقع<input name="expectedStartDate" type="date"/></label><label>مسؤول الفرصة<input name="ownerEmail" type="email"/></label><label className="wide">ملخص النطاق<textarea name="scopeSummary" required minLength={20} rows={4}/></label><button disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ الفرصة"}</button></form></details>}
function ProjectForm({opportunities,busy,onSubmit}:{opportunities:Opportunity[];busy:boolean;onSubmit:(form:HTMLFormElement)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();onSubmit(e.currentTarget)}return <details className="construction-form"><summary>تحويل فرصة فائزة إلى مشروع ومركز تكلفة</summary><form onSubmit={submit}><label>الفرصة<select name="opportunityId" required><option value="">اختر فرصة فائزة</option>{opportunities.map(o=><option value={o.id} key={o.id}>{o.opportunityCode} — {o.title}</option>)}</select></label><label>بداية المشروع<input name="startDate" type="date" required/></label><label>النهاية المخططة<input name="plannedEndDate" type="date" required/></label><label>قيمة العقد (ريال)<input name="contractValueHalalas" type="number" min="0" required/></label><label>الميزانية (ريال)<input name="budgetHalalas" type="number" min="0" required/></label><label>مدير المشروع<input name="managerEmail" type="email"/></label><button disabled={busy||!opportunities.length}>{busy?"جارٍ الإنشاء...":"إنشاء المشروع ومركز التكلفة"}</button></form></details>}
function CoverageForm({cities,lines,busy,onSubmit}:{cities:City[];lines:Line[];busy:boolean;onSubmit:(form:HTMLFormElement)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();onSubmit(e.currentTarget)}return <details className="construction-form"><summary>تحديث قدرة خدمة مدينة</summary><form onSubmit={submit}><label>المدينة<select name="cityId" required><option value="">اختر المدينة</option>{cities.map(c=><option value={c.id} key={c.id}>{c.nameAr}</option>)}</select></label><label>قطاع الأعمال<select name="businessLineId" required>{lines.map(l=><option value={l.id} key={l.id}>{l.nameAr}</option>)}</select></label><label>الإتاحة<select name="availability"><option value="conditional">مشروطة</option><option value="available">متاحة</option><option value="unavailable">غير متاحة</option></select></label><label>مستوى القدرة<select name="capacityLevel"><option value="review_required">تحتاج مراجعة</option><option value="high">عالية</option><option value="medium">متوسطة</option><option value="limited">محدودة</option></select></label><label>أيام التعبئة<input name="mobilizationDays" type="number" min="0"/></label><label>المسؤول<input name="ownerEmail" type="email"/></label><label className="wide">ملاحظات التشغيل<textarea name="operatingNotes" rows={3}/></label><label className="checkbox"><input name="publicApproved" type="checkbox"/> اعتماد ظهور التغطية في الموقع (مدير النظام فقط)</label><button disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ التغطية"}</button></form></details>}
