"use client";

import { FormEvent, useState } from "react";
import { readApiJson } from "@/lib/client-api";

type Contract = { id:number; referenceCode:string; clientName:string; clientCr:string|null; clientVat:string|null; title:string; workSite:string; issueDate:string; startDate:string; endDate:string; quantityMode:"fixed"|"open"; seasonType:string; vatRateBps:number; contractDirection:"dali_supplier"|"dali_purchaser"; accommodationParty:string|null; transportParty:string|null; details:string; showPaymentSchedule:boolean };
type Profession = { id?:number; contractId:number; profession:string; requiredCount:number; unitSalaryHalalas:number; actualSalaryHalalas:number; sponsorshipType:string|null; sponsorName:string|null; ajirContractStatus:string|null };
type SponsorshipPolicy={sponsorshipType:"dali"|"other";sponsorName:string};
type Payment={id:number;contractId:number;installmentNumber:number;title:string;dueDate:string;percentageBps:number;status:string;invoiceDocumentId:number|null};

export default function ContractFullEditDialog({contract,professions,payments,busy,onClose,onSaved}:{contract:Contract;professions:Profession[];payments:Payment[];busy:boolean;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [rows,setRows]=useState(()=>professions.length?professions.map(item=>({...item})):[{contractId:contract.id,profession:"",requiredCount:contract.quantityMode==="open"?0:1,unitSalaryHalalas:0,actualSalaryHalalas:0,sponsorshipType:"dali",sponsorName:null,ajirContractStatus:"not_applicable"}]);
  const [error,setError]=useState("");
  const [saving,setSaving]=useState(false);
  const [policies,setPolicies]=useState<SponsorshipPolicy[]>(()=>{const source=professions.length?professions:[{sponsorshipType:"dali",sponsorName:null}];return Array.from(new Map(source.map(item=>{const policy:SponsorshipPolicy={sponsorshipType:item.sponsorshipType==="other"?"other":"dali",sponsorName:item.sponsorName||""};return[`${policy.sponsorshipType}|${policy.sponsorName}`,policy]})).values())});
  const [newPolicy,setNewPolicy]=useState<SponsorshipPolicy>({sponsorshipType:"dali",sponsorName:""});
  const [schedule,setSchedule]=useState(()=>payments.map(item=>({...item})));
  const update=(index:number,changes:Partial<Profession>)=>setRows(current=>current.map((item,i)=>i===index?{...item,...changes}:item));
  const policyKey=(item:Pick<SponsorshipPolicy,"sponsorshipType"|"sponsorName">)=>`${item.sponsorshipType}|${item.sponsorName||""}`;
  const addPolicy=()=>{if(newPolicy.sponsorshipType==="other"&&!newPolicy.sponsorName.trim()){setError("اكتب اسم الكفيل الخارجي");return}if(policies.some(item=>policyKey(item)===policyKey(newPolicy))){setError("جهة الكفالة مضافة مسبقًا");return}setPolicies(current=>[...current,{...newPolicy,sponsorName:newPolicy.sponsorName.trim()}]);setNewPolicy({sponsorshipType:"dali",sponsorName:""});setError("")};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setSaving(true);const fd=new FormData(event.currentTarget);const payload={clientName:fd.get("clientName"),clientCr:fd.get("clientCr"),clientVat:fd.get("clientVat"),title:fd.get("title"),workSite:fd.get("workSite"),issueDate:fd.get("issueDate"),startDate:fd.get("startDate"),...(contract.seasonType!=="regular"?{endDate:fd.get("endDate")} :{}),contractDirection:fd.get("contractDirection"),vatRateBps:Math.round(Number(fd.get("vatRate")||0)*100),accommodationParty:fd.get("accommodationParty"),transportParty:fd.get("transportParty"),details:fd.get("details"),showPaymentSchedule:fd.get("showPaymentSchedule")==="on",paymentSchedule:contract.seasonType==="regular"?undefined:schedule.map(item=>({id:item.id,title:item.title,dueDate:item.dueDate,percentageBps:item.percentageBps})),professions:rows.map(item=>({profession:item.profession,requiredCount:contract.quantityMode==="open"?0:Number(item.requiredCount),unitSalaryHalalas:Math.round(Number(item.unitSalaryHalalas)),actualSalaryHalalas:Math.round(Number(item.actualSalaryHalalas)),sponsorshipType:item.sponsorshipType,sponsorName:item.sponsorshipType==="other"?item.sponsorName:null,ajirContractStatus:item.ajirContractStatus||"not_applicable"}))};try{const response=await fetch(`/api/portal/contracts/${contract.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await readApiJson(response)as{error?:string};if(!response.ok)throw new Error(result.error||"تعذر تعديل العقد");await onSaved();onClose()}catch(problem){setError(problem instanceof Error?problem.message:"تعذر تعديل العقد")}finally{setSaving(false)}}
  return <div className="modal-layer"><button className="drawer-backdrop" aria-label="إغلاق تعديل العقد" onClick={onClose}/><section className="record-modal contract-full-editor" role="dialog" aria-modal="true"><div className="drawer-head"><div><span>{contract.referenceCode}</span><h2>تعديل العقد بالكامل</h2></div><button type="button" onClick={onClose}>×</button></div><form className="feature-form" onSubmit={submit}>
    <label>العميل أو الجهة<input name="clientName" required defaultValue={contract.clientName}/></label><label>عنوان العقد<input name="title" required defaultValue={contract.title}/></label>
    <label>السجل التجاري<input name="clientCr" defaultValue={contract.clientCr||""}/></label><label>الرقم الضريبي<input name="clientVat" defaultValue={contract.clientVat||""}/></label>
    <label>موقع العمل<input name="workSite" required defaultValue={contract.workSite}/></label><label>اتجاه العقد<select name="contractDirection" defaultValue={contract.contractDirection}><option value="dali_supplier">دالي مورّد للعمالة</option><option value="dali_purchaser">دالي مشتري للعمالة</option></select></label>
    <label>تاريخ الإصدار<input name="issueDate" type="date" required defaultValue={contract.issueDate}/></label><label>تاريخ البداية<input name="startDate" type="date" required defaultValue={contract.startDate}/></label>{contract.seasonType!=="regular"&&<label>تاريخ النهاية<input name="endDate" type="date" required defaultValue={contract.endDate}/></label>}
    <label>الضريبة %<input name="vatRate" type="number" min="0" max="100" step="0.01" defaultValue={contract.vatRateBps/100}/></label><label>السكن<input name="accommodationParty" defaultValue={contract.accommodationParty||""}/></label><label>النقل<input name="transportParty" defaultValue={contract.transportParty||""}/></label>
    <label className="span-two">نطاق العمل والتفاصيل<textarea name="details" required rows={5} defaultValue={contract.details}/></label><label className="span-two"><input name="showPaymentSchedule" type="checkbox" defaultChecked={contract.showPaymentSchedule}/> إظهار جدول الدفعات في العقد</label>
    <section className="span-two contract-edit-professions"><header><div><h3>جدول الدفعات</h3><p>{contract.seasonType==="regular"?"العقد السنوي يعيد احتساب 12 دفعة تلقائيًا من تاريخ البداية.":"يمكن تعديل عناوين الدفعات وتواريخها ونسبها قبل بدء المعالجة المالية."}</p></div></header>{contract.seasonType!=="regular"&&schedule.map((payment,index)=><div className="profession-edit-row" key={payment.id}><input aria-label="عنوان الدفعة" value={payment.title} onChange={e=>setSchedule(items=>items.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/><input aria-label="تاريخ الاستحقاق" type="date" value={payment.dueDate} onChange={e=>setSchedule(items=>items.map((item,i)=>i===index?{...item,dueDate:e.target.value}:item))}/><input aria-label="نسبة الدفعة" type="number" min="0.01" max="100" step="0.01" value={payment.percentageBps/100} onChange={e=>setSchedule(items=>items.map((item,i)=>i===index?{...item,percentageBps:Math.round(Number(e.target.value)*100)}:item))}/></div>)}</section>
    <section className="span-two contract-sponsorship-policy"><h3>جهات الكفالة المعتمدة للعقد بالكامل</h3><p>تُعرّف الجهات هنا مرة واحدة، ثم تربط كل توزيع مهني بإحدى الجهات المعتمدة.</p><div className="policy-list">{policies.map(item=><span key={policyKey(item)}>{item.sponsorshipType==="dali"?"كفالة دالي":`كفالة ${item.sponsorName}`}</span>)}</div><div className="policy-add"><select value={newPolicy.sponsorshipType} onChange={e=>setNewPolicy(item=>({...item,sponsorshipType:e.target.value as "dali"|"other",sponsorName:e.target.value==="dali"?"":item.sponsorName}))}><option value="dali">كفالة دالي</option><option value="other">كفيل خارجي</option></select>{newPolicy.sponsorshipType==="other"&&<input placeholder="اسم الكفيل" value={newPolicy.sponsorName} onChange={e=>setNewPolicy(item=>({...item,sponsorName:e.target.value}))}/>}<button type="button" onClick={addPolicy}>إضافة جهة للعقد</button></div></section>
    <section className="span-two contract-edit-professions"><header><div><h3>المهن والأسعار</h3><p>سعر العامل للعميل منفصل عن الراتب الفعلي، وتختار جهة الكفالة من قائمة العقد.</p></div><button type="button" onClick={()=>{const policy=policies[0]||{sponsorshipType:"dali",sponsorName:""};setRows(current=>[...current,{contractId:contract.id,profession:"",requiredCount:contract.quantityMode==="open"?0:1,unitSalaryHalalas:0,actualSalaryHalalas:0,ajirContractStatus:"not_applicable",...policy}])}}>إضافة مهنة</button></header>{rows.map((row,index)=><div className="profession-edit-row" key={index}><input aria-label="المهنة" required placeholder="المهنة" value={row.profession} onChange={e=>update(index,{profession:e.target.value})}/><input aria-label="العدد" type="number" min="0" disabled={contract.quantityMode==="open"} value={row.requiredCount} onChange={e=>update(index,{requiredCount:Number(e.target.value)})}/><input aria-label="سعر العامل" type="number" min="0" step="1" value={row.unitSalaryHalalas/100} onChange={e=>update(index,{unitSalaryHalalas:Math.round(Number(e.target.value)*100)})}/><input aria-label="الراتب الفعلي" type="number" min="0" step="1" value={row.actualSalaryHalalas/100} onChange={e=>update(index,{actualSalaryHalalas:Math.round(Number(e.target.value)*100)})}/><select aria-label="جهة الكفالة المعتمدة" value={policyKey({sponsorshipType:row.sponsorshipType==="other"?"other":"dali",sponsorName:row.sponsorName||""})} onChange={e=>{const policy=policies.find(item=>policyKey(item)===e.target.value);if(policy)update(index,{...policy})}}>{policies.map(item=><option key={policyKey(item)} value={policyKey(item)}>{item.sponsorshipType==="dali"?"كفالة دالي":item.sponsorName}</option>)}</select><select aria-label="توزيع أجير في العقد" value={row.ajirContractStatus||"not_applicable"} onChange={e=>update(index,{ajirContractStatus:e.target.value})}><option value="not_applicable">أجير غير منطبق</option><option value="with_ajir">ضمن حصة بعقد أجير</option><option value="without_ajir">ضمن حصة دون عقد أجير</option></select><button type="button" className="danger-action" disabled={rows.length===1} onClick={()=>setRows(current=>current.filter((_,i)=>i!==index))}>حذف</button></div>)}</section>
    {error&&<p className="operations-notice span-two">{error}</p>}<div className="modal-actions span-two"><button type="button" onClick={onClose}>إلغاء</button><button className="admin-primary" disabled={busy||saving}>{busy||saving?"جارٍ الحفظ...":"حفظ كل التعديلات"}</button></div>
  </form></section></div>
}
