"use client";
import { useCallback, useEffect, useState } from "react";
type Contract={id:number;referenceCode:string;clientName:string;title:string;amountHalalas:number;startDate:string;endDate:string;status:string};
type Payment={id:number;contractId:number;installmentNumber:number;title:string;dueDate:string;percentageBps:number;amountHalalas:number;status:string;invoiceDocumentId:number|null};
type Data={contracts:Contract[];payments:Payment[];canRefer:boolean;canInvoice:boolean;canRecordPayment:boolean;canReferLegal:boolean};
const money=(value:number)=>new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(value/100);
const labels:Record<string,string>={scheduled:"مجدولة",due:"مستحقة",referred:"محالة للمحاسبة",invoiced:"صدرت الفاتورة",paid:"مسددة",cancelled:"ملغاة"};
export default function ContractBillingWorkspace(){const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState(0);const[notice,setNotice]=useState("");const load=useCallback(async()=>{const response=await fetch("/api/portal/contract-payments",{cache:"no-store"});const result=await response.json()as Data&{error?:string};if(!response.ok)throw new Error(result.error||"تعذر تحميل العقود والدفعات");setData(result)},[]);useEffect(()=>{let active=true;void fetch("/api/portal/contract-payments",{cache:"no-store"}).then(async response=>{const result=await response.json()as Data&{error?:string};if(!response.ok)throw new Error(result.error||"تعذر التحميل");if(active)setData(result)}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[]);
async function patch(payment:Payment,action:string){let reason="";if(action==="refer-legal"){reason=window.prompt("سبب إحالة ملف العميل للشؤون القانونية (10 أحرف على الأقل)")||"";if(!reason)return}setBusy(payment.id);setNotice("");try{const response=await fetch("/api/portal/contract-payments",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({paymentId:payment.id,action,reason})});const result=await response.json()as{error?:string};if(!response.ok)throw new Error(result.error||"تعذر تنفيذ الإجراء");await load();setNotice(action==="refer-accounting"?"أُحيلت الدفعة للمحاسبة.":action==="mark-paid"?"تم تسجيل السداد وربطه بالسجل المالي.":"أُحيل ملف العميل والعقد للشؤون القانونية.")}catch(error){setNotice(error instanceof Error?error.message:"تعذر التنفيذ")}finally{setBusy(0)}}
async function invoice(payment:Payment){setBusy(payment.id);setNotice("");try{const response=await fetch("/api/portal/contract-payments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentId:payment.id})});const result=await response.json()as{error?:string};if(!response.ok)throw new Error(result.error||"تعذر إصدار الفاتورة");await load();setNotice("أُنشئت الفاتورة المالية وملف PDF وأصبحت جاهزة للتنزيل والمشاركة.")}catch(error){setNotice(error instanceof Error?error.message:"تعذر إصدار الفاتورة")}finally{setBusy(0)}}
async function share(documentId:number){try{const response=await fetch("/api/portal/documents/share",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId,expiresInDays:7,maxDownloads:20})});const result=await response.json()as{shareUrl?:string;error?:string};if(!response.ok||!result.shareUrl)throw new Error(result.error||"تعذر إنشاء الرابط");await navigator.clipboard.writeText(result.shareUrl);setNotice("تم إنشاء رابط مشاركة آمن ونسخه، صالح 7 أيام وبحد 20 تنزيلاً.")}catch(error){setNotice(error instanceof Error?error.message:"تعذر إنشاء رابط المشاركة")}}
if(!data)return <section className="panel"><p>{notice||"جارٍ تحميل العقود والدفعات..."}</p></section>;return <>{notice&&<div className="operations-notice" role="status">{notice}</div>}<section className="panel contract-billing"><header><div><h2>العقود وجدول الدفعات</h2><p>إحالة الدفعات المستحقة، إصدار الفواتير، تسجيل السداد، والإحالة القانونية عند التأخر.</p></div><b>{data.contracts.length} عقد</b></header><div className="contract-billing-list">{data.contracts.map(contract=>{const payments=data.payments.filter(item=>item.contractId===contract.id);return <article key={contract.id}><header><div><strong>{contract.referenceCode}</strong><h3>{contract.clientName}</h3><p>{contract.title} · {money(contract.amountHalalas)}</p></div><span>{contract.status}</span></header><div className="payment-schedule-list">{payments.map(payment=><div key={payment.id}><p><strong>{payment.installmentNumber}. {payment.title}</strong><small>الاستحقاق {payment.dueDate} · {(payment.percentageBps/100).toFixed(2)}%</small></p><b>{money(payment.amountHalalas)}</b><span className={`workflow-status ${payment.status}`}>{labels[payment.status]||payment.status}</span><div className="payment-actions">{data.canRefer&&["scheduled","due"].includes(payment.status)&&payment.dueDate<=new Date().toISOString().slice(0,10)&&<button disabled={busy===payment.id} onClick={()=>void patch(payment,"refer-accounting")}>تحويل للمحاسب</button>}{data.canInvoice&&payment.status==="referred"&&<button disabled={busy===payment.id} onClick={()=>void invoice(payment)}>إصدار الفاتورة</button>}{payment.invoiceDocumentId&&<a href={`/api/portal/documents/${payment.invoiceDocumentId}`}>تنزيل PDF</a>}{payment.invoiceDocumentId&&<button onClick={()=>void share(payment.invoiceDocumentId!)}>مشاركة</button>}{data.canRecordPayment&&payment.status==="invoiced"&&<button disabled={busy===payment.id} onClick={()=>void patch(payment,"mark-paid")}>تسجيل السداد</button>}{data.canReferLegal&&payment.status!=="paid"&&payment.dueDate<new Date().toISOString().slice(0,10)&&<button className="legal-referral" disabled={busy===payment.id} onClick={()=>void patch(payment,"refer-legal")}>إحالة الملف للقانونية</button>}</div></div>)}</div></article>})}</div></section></>}
