"use client";

import { readApiJson } from "@/lib/client-api";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Policy={userEmail:string;employeeId:number|null;trackingEnabled:boolean;shiftStart:string;shiftEnd:string;requiredMinutes:number;graceMinutes:number};
type Employee={id:number;fullName:string;employeeNumber:string;portalUserEmail:string|null;baseSalaryHalalas:number;status:string};
type User={email:string;displayName:string;status:string;department:string;functionalRoles:string[];policy:Policy|null;employee:Employee|null};
type Session={sessionId:string;userEmail:string;workDate:string;loginAt:string;logoutAt:string|null;durationMinutes:number;status:string};
type Proposal={id:number;employeeId:number;employeeName:string;periodMonth:string;requiredMinutes:number;workedMinutes:number;missingMinutes:number;cappedAmountHalalas:number;status:string;writtenConsentConfirmed:boolean;legalBasis:string|null;reviewedBy:string|null};
type Review={id:number;employeeId:number;employeeName:string;periodStart:string;periodEnd:string;roleKey:string;status:string;overallScore:number;reviewerEmail:string};
type Payload={users?:User[];employees?:Employee[];sessions?:Session[];proposals?:Proposal[];reviews?:Review[];metrics?:{tracked:number;online:number;deductionReview:number;performanceReview:number;unlinked:number};error?:string};
const roleLabels:Record<string,string>={system_owner:"مالك النظام",system_admin:"مشرف النظام",accountant:"المحاسب",legal_affairs:"شؤون قانونية",sales_representative:"مندوب مبيعات",purchasing_representative:"مندوب مشتريات",administrative_assistant:"مساعد إداري"};
const proposalLabels:Record<string,string>={draft:"مسودة محاسبية",hr_review:"بانتظار الاعتماد المالي",finance_approved:"معتمد ومرتبط بالراتب",rejected:"مرفوض",posted:"مرحّل"};
const reviewLabels:Record<string,string>={draft:"مسودة",manager_review:"بانتظار المعايرة",hr_calibration:"معايرة الموارد البشرية",final:"نهائي",appealed:"محل اعتراض"};
function money(value:number){return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(value/100)}
function hours(minutes:number){return `${Math.floor(minutes/60)}س ${minutes%60}د`}

export default function ExecutivePeopleCommandCenter({isOwner,isSystemAdmin}:{isOwner:boolean;isSystemAdmin:boolean}){
  const[data,setData]=useState<Required<Omit<Payload,"error">>>({users:[],employees:[],sessions:[],proposals:[],reviews:[],metrics:{tracked:0,online:0,deductionReview:0,performanceReview:0,unlinked:0}});const[tab,setTab]=useState<"attendance"|"payroll"|"performance">("attendance");const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/portal/people-governance",{cache:"no-store"});const result=await readApiJson(response)as Payload;if(!response.ok)throw new Error(result.error||"تعذر تحميل مركز حوكمة الموظفين");setData({users:result.users||[],employees:result.employees||[],sessions:result.sessions||[],proposals:result.proposals||[],reviews:result.reviews||[],metrics:result.metrics||{tracked:0,online:0,deductionReview:0,performanceReview:0,unlinked:0}})},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(error=>setNotice(error instanceof Error?error.message:"تعذر التحميل")),0);return()=>window.clearTimeout(timer)},[load]);
  async function action(actionName:string,payload:Record<string,unknown>){setBusy(actionName);setNotice("");try{const response=await fetch("/api/portal/people-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:actionName,...payload})});const result=await readApiJson(response)as Payload;if(!response.ok)throw new Error(result.error||"تعذر تنفيذ الإجراء");setData({users:result.users||[],employees:result.employees||[],sessions:result.sessions||[],proposals:result.proposals||[],reviews:result.reviews||[],metrics:result.metrics||data.metrics});setNotice("تم تنفيذ الإجراء وتسجيله في سجل التدقيق.");return true}catch(error){setNotice(error instanceof Error?error.message:"تعذر تنفيذ الإجراء");return false}finally{setBusy("")}}
  async function toggle(user:User){const reason=window.prompt(`${user.policy?.trackingEnabled?"سبب إيقاف":"سبب تفعيل"} حساب زمن الحضور لـ ${user.displayName}:`,"");if(!reason)return;await action("toggle_tracking",{userEmail:user.email,employeeId:user.employee?.id||null,enabled:!user.policy?.trackingEnabled,reason,shiftStart:user.policy?.shiftStart||"08:00",shiftEnd:user.policy?.shiftEnd||"17:00",requiredMinutes:user.policy?.requiredMinutes||480,graceMinutes:user.policy?.graceMinutes||10})}
  async function calculate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await action("calculate_deduction",{employeeId:data.get("employeeId"),periodMonth:data.get("periodMonth")})}
  async function submitDeduction(event:FormEvent<HTMLFormElement>,id:number){event.preventDefault();const form=new FormData(event.currentTarget);await action("submit_deduction",{id,reason:form.get("reason"),legalBasis:form.get("legalBasis"),writtenConsentConfirmed:form.get("consent")==="on"})}
  async function createReview(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action("create_performance_review",Object.fromEntries(form.entries()))}
  const trackedEmployees=useMemo(()=>data.users.filter(user=>user.policy?.trackingEnabled&&user.employee).map(user=>user.employee as Employee),[data.users]);
  return <section className="executive-people-center panel"><header className="executive-command-head"><div><span>حوكمة تشغيلية موحّدة</span><h2>قيادة الموظفين والحضور والأداء</h2><p>قرارات قابلة للتدقيق تربط جلسات العمل بالموارد البشرية والرواتب، مع فصل المراجعة عن الاعتماد.</p></div><b>Asia/Riyadh · إغلاق خامل 20:00</b></header>
    {notice&&<div className="operations-notice" role="status">{notice}</div>}
    <div className="executive-kpis"><article><span>موظفون تحت التتبع</span><strong>{data.metrics.tracked}</strong><small>باختيار المالك فقط</small></article><article><span>جلسات نشطة</span><strong>{data.metrics.online}</strong><small>نشاط خلال آخر 10 دقائق</small></article><article><span>خصومات تحتاج قراراً</span><strong>{data.metrics.deductionReview}</strong><small>لا تُرحّل تلقائياً</small></article><article><span>تقييمات قيد المعايرة</span><strong>{data.metrics.performanceReview}</strong><small>بأدلة وفصل مهام</small></article></div>
    <div className="executive-alert-strip">{data.metrics.unlinked>0&&<span className="critical">{data.metrics.unlinked} سياسة حضور غير مرتبطة بملف موظف</span>}{data.metrics.deductionReview>0&&<span>{data.metrics.deductionReview} مسودة خصم تنتظر المراجعة</span>}{data.metrics.performanceReview>0&&<span>{data.metrics.performanceReview} تقييم يحتاج معايرة مستقلة</span>}{!data.metrics.unlinked&&!data.metrics.deductionReview&&!data.metrics.performanceReview&&<span className="healthy">لا توجد قرارات حرجة معلقة</span>}</div>
    <nav className="executive-tabs"><button className={tab==="attendance"?"active":""} onClick={()=>setTab("attendance")}>الحضور والجلسات</button><button className={tab==="payroll"?"active":""} onClick={()=>setTab("payroll")}>نقص الدوام والرواتب</button><button className={tab==="performance"?"active":""} onClick={()=>setTab("performance")}>تقييم الأداء</button></nav>
    {tab==="attendance"&&<div className="attendance-governance"><div className="governance-user-list">{data.users.filter(user=>!user.functionalRoles.includes("system_admin")).map(user=><article key={user.email}><div><strong>{user.displayName}</strong><small>{roleLabels[user.functionalRoles[0]]||user.functionalRoles[0]||"دون دور"} · {user.employee?`${user.employee.employeeNumber} مرتبط بالموارد البشرية`:"غير مرتبط بملف موظف"}</small></div><span className={user.policy?.trackingEnabled?"enabled":"disabled"}>{user.policy?.trackingEnabled?"الحساب مفعّل":"غير مفعّل"}</span>{isOwner&&<button disabled={Boolean(busy)||!user.employee} onClick={()=>void toggle(user)}>{user.policy?.trackingEnabled?"إيقاف":"تفعيل"}</button>}</article>)}</div><div className="session-timeline"><h3>أحدث جلسات الحضور</h3>{data.sessions.slice(0,12).map(session=><div key={session.sessionId}><span>{session.workDate}</span><strong>{data.users.find(user=>user.email===session.userEmail)?.displayName||session.userEmail}</strong><small>{new Date(session.loginAt).toLocaleTimeString("ar-SA",{timeZone:"Asia/Riyadh",hour:"2-digit",minute:"2-digit"})} — {session.logoutAt?new Date(session.logoutAt).toLocaleTimeString("ar-SA",{timeZone:"Asia/Riyadh",hour:"2-digit",minute:"2-digit"}):"جلسة نشطة"} · {hours(session.durationMinutes)}</small></div>)}</div></div>}
    {tab==="payroll"&&<div className="payroll-governance"><form className="governance-inline-form" onSubmit={calculate}><label>الموظف<select name="employeeId" required defaultValue=""><option value="" disabled>اختر موظفاً مفعّل الحضور</option>{trackedEmployees.map(employee=><option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></label><label>الشهر<input name="periodMonth" type="month" required max={new Date().toISOString().slice(0,7)}/></label><button disabled={Boolean(busy)}>حساب مسودة عادلة</button><p>يُستبعد الغياب المعذور، ويُحتسب النقص بالدقائق، ويُطبق سقف 50%، ثم تمر المسودة بمراجعة بشرية واعتماد مالي مستقل.</p></form><div className="deduction-list">{data.proposals.map(proposal=><article key={proposal.id}><header><div><strong>{proposal.employeeName}</strong><small>{proposal.periodMonth} · {proposalLabels[proposal.status]||proposal.status}</small></div><b>{money(proposal.cappedAmountHalalas)}</b></header><div className="deduction-math"><span>المطلوب {hours(proposal.requiredMinutes)}</span><span>المسجّل {hours(proposal.workedMinutes)}</span><span>النقص {hours(proposal.missingMinutes)}</span></div>{proposal.status==="draft"&&<form onSubmit={event=>void submitDeduction(event,proposal.id)}><textarea name="legalBasis" placeholder="الأساس النظامي أو مرجع موافقة الموظف"/><label><input type="checkbox" name="consent"/> تم توثيق موافقة الموظف الخطية</label><input name="reason" required minLength={10} placeholder="مبرر إحالة المسودة للمراجعة"/><button disabled={Boolean(busy)}>إحالة للمراجعة البشرية</button></form>}{proposal.status==="hr_review"&&<div className="proposal-actions"><button disabled={Boolean(busy)||!isSystemAdmin} onClick={()=>{const reason=window.prompt("مبرر الاعتماد المالي:","");if(reason)void action("approve_deduction",{id:proposal.id,reason})}}>اعتماد مالي وربط بالراتب</button><button className="danger" disabled={Boolean(busy)} onClick={()=>{const reason=window.prompt("سبب رفض المسودة:","");if(reason)void action("reject_deduction",{id:proposal.id,reason})}}>رفض</button></div>}</article>)}</div></div>}
    {tab==="performance"&&<div className="performance-governance"><form className="performance-form" onSubmit={createReview}><label>الموظف<select name="employeeId" required defaultValue=""><option value="" disabled>اختر الموظف</option>{data.employees.filter(item=>item.status==="active").map(employee=><option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></label><label>الدور المرجعي<select name="roleKey" defaultValue="administrative_assistant">{Object.entries(roleLabels).filter(([key])=>!key.startsWith("system_")).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>من<input name="periodStart" type="date" required/></label><label>إلى<input name="periodEnd" type="date" required/></label>{[["goalsScore","الإنجاز والأهداف"],["qualityScore","جودة المخرجات"],["timelinessScore","الالتزام بالمواعيد"],["collaborationScore","التعاون والسلوك"],["complianceScore","الامتثال والدقة"],["attendanceScore","الانتظام (إن كان مفعلاً)"]].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" max="100" defaultValue="80" required/></label>)}<label className="wide">الأدلة الموضوعية<textarea name="evidence" required minLength={20} placeholder="أهداف منجزة، جودة، أخطاء موثقة، ملاحظات عملاء، التزام بالمواعيد..."/></label><label className="wide">ملاحظة المدير<textarea name="managerComment" placeholder="تغذية راجعة قابلة للتنفيذ"/></label><button disabled={Boolean(busy)}>إنشاء تقييم للمراجعة والمعايرة</button></form><div className="performance-list">{data.reviews.map(review=><article key={review.id}><div><strong>{review.employeeName}</strong><small>{review.periodStart} — {review.periodEnd} · {reviewLabels[review.status]||review.status}</small></div><b>{review.overallScore}%</b>{review.status!=="final"&&<button disabled={Boolean(busy)} onClick={()=>{const comment=window.prompt("ملاحظة المعايرة المستقلة:","");if(comment)void action("finalize_performance_review",{id:review.id,comment})}}>معايرة واعتماد</button>}</article>)}</div></div>}
  </section>
}
