"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { readApiJson } from "@/lib/client-api";

type Matter={id:number;referenceCode:string;title:string;counterparty:string;status:string;referralReason:string|null;fileSnapshotJson:string|null;contractId:number|null};
type Activity={id:number;legalRecordId:number;activityType:string;title:string;details:string|null;priority:string;status:string;dueAt:string|null;assignedTo:string|null};
type Attachment={id:number;legalRecordId:number;title:string;fileName:string;contentType:string;sizeBytes:number;createdAt:string};
type Snapshot={contract?:Record<string,unknown>;documents?:Array<Record<string,unknown>>;payments?:Array<Record<string,unknown>>;finances?:Array<Record<string,unknown>>;workers?:Array<Record<string,unknown>>};
type Data={cases:Matter[];activities:Activity[];attachments:Attachment[];canWrite:boolean;canApprove:boolean};
const types:Record<string,string>={task:"مهمة",deadline:"موعد نظامي",note:"ملاحظة",communication:"مراسلة",hearing:"جلسة",settlement:"تسوية"};
const text=(value:unknown)=>value===null||value===undefined||value===""?"غير مسجل":String(value);
const money=(value:unknown)=>new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(Number(value||0)/100);

export default function LegalCaseWorkspace(){
  const[data,setData]=useState<Data|null>(null),[selected,setSelected]=useState(0),[notice,setNotice]=useState(""),[uploading,setUploading]=useState(false);
  const load=useCallback(async()=>{const response=await fetch("/api/portal/legal-cases",{cache:"no-store"});const result=await readApiJson(response)as Data&{error?:string};if(!response.ok)throw new Error(result.error||"تعذر تحميل القضايا");setData(result);setSelected(value=>value||result.cases[0]?.id||0)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(error=>setNotice(error instanceof Error?error.message:"تعذر التحميل")),0);return()=>window.clearTimeout(timer)},[load]);
  const matter=data?.cases.find(item=>item.id===selected);
  const activities=useMemo(()=>data?.activities.filter(item=>item.legalRecordId===selected)||[],[data,selected]);
  const attachments=useMemo(()=>data?.attachments.filter(item=>item.legalRecordId===selected)||[],[data,selected]);
  const snapshot=useMemo(()=>{if(!matter?.fileSnapshotJson)return null;try{return JSON.parse(matter.fileSnapshotJson)as Snapshot}catch{return null}},[matter]);
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const body=Object.fromEntries(new FormData(form).entries());const response=await fetch("/api/portal/legal-cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,legalRecordId:selected})});const result=await readApiJson(response)as{error?:string};if(!response.ok){setNotice(result.error||"تعذر حفظ الإجراء");return}form.reset();setNotice("تمت إضافة الإجراء إلى سجل القضية.");await load()}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,body=new FormData(form);body.set("legalRecordId",String(selected));setUploading(true);const response=await fetch("/api/portal/legal-cases/attachments",{method:"POST",body});const result=await readApiJson(response)as{error?:string};setUploading(false);if(!response.ok){setNotice(result.error||"تعذر رفع المرفق");return}form.reset();setNotice("تم حفظ المرفق داخل الملف القانوني.");await load()}
  async function update(id:number,status:string){const response=await fetch("/api/portal/legal-cases",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});const result=await readApiJson(response)as{error?:string};if(!response.ok){setNotice(result.error||"تعذر تحديث الإجراء");return}await load()}
  if(!data)return <section className="panel legal-matter-workspace"><p>{notice||"جارٍ تحميل إدارة القضايا..."}</p></section>;
  return <section className="panel legal-matter-workspace"><header><div><span>إدارة المسائل القانونية</span><h2>ملف قانوني مترابط بالعقد والعميل</h2><p>العقد ومرفقاته ودفعاته وسجله المالي والعمالة والإجراءات في موضع واحد.</p></div><b>{data.cases.filter(item=>item.status!=="closed").length} ملف مفتوح</b></header>{notice&&<p className="operations-notice">{notice}</p>}
    <div className="legal-matter-layout"><aside>{data.cases.map(item=><button type="button" key={item.id} className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)}><strong>{item.referenceCode}</strong><span>{item.counterparty}</span><small>{item.status}</small></button>)}</aside><main>{matter?<>
      <div className="legal-matter-head"><div><h3>{matter.title}</h3><p>{matter.referralReason||"ملف قانوني مسجل يدويًا"}</p></div><span>{activities.filter(item=>!["completed","cancelled"].includes(item.status)).length} إجراءات مفتوحة</span></div>
      {snapshot&&<section className="legal-linked-file"><h3>العقد والملف المحال</h3><dl><div><dt>مرجع العقد</dt><dd>{text(snapshot.contract?.referenceCode)}</dd></div><div><dt>العميل</dt><dd>{text(snapshot.contract?.clientName||matter.counterparty)}</dd></div><div><dt>حالة العقد</dt><dd>{text(snapshot.contract?.status)}</dd></div><div><dt>قيمة العقد</dt><dd>{money(snapshot.contract?.amountHalalas)}</dd></div></dl><div className="legal-related-counts"><span>المستندات <b>{snapshot.documents?.length||0}</b></span><span>الدفعات <b>{snapshot.payments?.length||0}</b></span><span>السجلات المالية <b>{snapshot.finances?.length||0}</b></span><span>العمالة <b>{snapshot.workers?.length||0}</b></span></div>{snapshot.documents?.map((item,index)=><article key={index}><strong>{text(item.title||item.referenceCode)}</strong><small>{text(item.fileName||item.status)}</small>{item.id&&<a href={`/api/portal/documents/${item.id}?inline=1`} target="_blank" rel="noreferrer">فتح المستند</a>}</article>)}</section>}
      <section className="legal-case-files"><h3>مرفقات الشؤون القانونية</h3>{attachments.map(item=><a key={item.id} href={`/api/portal/legal-cases/attachments/${item.id}?inline=1`} target="_blank" rel="noreferrer"><strong>{item.title}</strong><small>{item.fileName} · {(item.sizeBytes/1024/1024).toFixed(2)} م.ب</small></a>)}{!attachments.length&&<p className="legal-empty">لا توجد مرفقات قانونية إضافية.</p>}{data.canWrite&&<form onSubmit={upload}><input name="title" maxLength={180} placeholder="اسم المرفق"/><input name="file" type="file" required accept="application/pdf,image/png,image/jpeg"/><button disabled={uploading}>{uploading?"جارٍ الرفع...":"إرفاق ملف قانوني"}</button></form>}</section>
      {data.canWrite&&<form className="legal-activity-form" onSubmit={add}><select name="activityType" required defaultValue="task">{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="title" required minLength={3} placeholder="عنوان الإجراء"/><select name="priority" defaultValue="medium"><option value="low">منخفض</option><option value="medium">متوسط</option><option value="high">عالٍ</option><option value="critical">عاجل</option></select><input name="dueAt" type="datetime-local"/><input name="assignedTo" type="email" placeholder="المسؤول بالبريد"/><textarea name="details" placeholder="الملاحظات والخطوة المطلوبة"/><button>إضافة إلى القضية</button></form>}
      <div className="legal-timeline">{activities.map(item=><article key={item.id} className={`${item.priority} ${item.status}`}><i/><div><header><strong>{types[item.activityType]||item.activityType} — {item.title}</strong><span>{item.priority}</span></header><p>{item.details||"دون ملاحظات إضافية"}</p><small>{item.dueAt?`الموعد: ${new Date(item.dueAt).toLocaleString("ar-SA")}`:"دون موعد"}{item.assignedTo?` · المسؤول: ${item.assignedTo}`:""}</small></div>{data.canWrite&&!["completed","cancelled"].includes(item.status)&&<div><button onClick={()=>void update(item.id,"in_progress")}>قيد التنفيذ</button><button onClick={()=>void update(item.id,"completed")}>إكمال</button></div>}</article>)}{!activities.length&&<p className="legal-empty">لا توجد إجراءات مسجلة لهذه القضية.</p>}</div>
    </>:<p className="legal-empty">اختر ملفًا قانونيًا.</p>}</main></div>
  </section>
}
