"use client";
import { useCallback, useEffect, useState } from "react";
import { readApiJson } from "@/lib/client-api";
import type { ClauseReview } from "@/lib/legal-clause-reviews";
import { contractClauseLabel } from "@/lib/workforce-contract-clauses";
const statuses:Record<ClauseReview["status"],string>={pending:"بانتظار المراجعة",approved:"معتمد قانونيًا",rejected:"معاد للتعديل",recommended:"صدرت التوصية",superseded:"استبدل بقالب أحدث"};
export default function LegalClauseReviews({ compact=false, selectedId, kind="contract", direction }: {compact?:boolean;selectedId?:string;kind?:"contract"|"defaults";direction?:string}) {
  const [reviews,setReviews]=useState<ClauseReview[]>([]),[canReview,setCanReview]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState(compact ? "all" : "pending");
  const load=useCallback(async()=>{const response=await fetch("/api/portal/legal-clause-reviews",{cache:"no-store"});const data=await readApiJson(response) as {reviews?:ClauseReview[];canReview?:boolean;error?:string};if(!response.ok)throw new Error(data.error || "تعذر تحميل المراجعات القانونية");setReviews(data.reviews || []);setCanReview(data.canReview === true);setLoaded(true);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(error=>setNotice(error.message)),0);return ()=>window.clearTimeout(timer);},[load]);
  async function decide(event:React.FormEvent<HTMLFormElement>,review:ClauseReview) {
    event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(review.id);setNotice("");
    try {const response=await fetch("/api/portal/legal-clause-reviews",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:review.id,revision:review.revision,action:data.get("action"),recommendation:data.get("recommendation")})});const result=await readApiJson(response) as {error?:string};if(!response.ok)throw new Error(result.error || "تعذر حفظ التوصية");await load();setNotice("تم توثيق المراجعة وإشعار صاحب الطلب.");}catch(error){setNotice(error instanceof Error?error.message:"تعذر حفظ التوصية");}finally{setBusy("");}
  }
  const visible=reviews.filter(item=>!compact || item.kind===kind).filter(item=>!direction || item.direction===direction).filter(item=>item.id===selectedId || filter==="all" || item.status==="pending");
  return <section className="legal-clause-reviews"><div className="legal-section-heading"><div><h3>مراجعة البنود والتوصيات</h3><p>البنود الافتراضية لا تطبق قبل المراجعة القانونية. توصية العقد استشارية ويمكن اعتماده دون انتظارها.</p></div><div className="record-actions"><button type="button" aria-pressed={filter==="pending"} onClick={()=>setFilter("pending")}>بانتظار المراجعة</button><button type="button" aria-pressed={filter==="all"} onClick={()=>setFilter("all")}>جميع المراجعات</button><button type="button" disabled={!!busy} onClick={()=>void load().catch(error=>setNotice(error.message))}>تحديث</button></div></div>
    {notice && <p role="status" className="operations-notice">{notice}</p>}
    {!loaded && !notice && <p role="status">جارٍ تحميل المراجعات...</p>}
    <div className="legal-review-grid">{visible.map(review=><details className="legal-review-card" key={review.id} open={review.id===selectedId ? true:undefined}><summary><span className={`review-status ${review.status}`}>{statuses[review.status]}</span><strong>{review.kind==="defaults" ? "قالب البنود الافتراضية" : "عقد ببنود إضافية"}</strong><span>{review.reference}{review.contractVersion ? ` · نسخة ${review.contractVersion}`:""}</span><small>{review.createdBy} · {new Date(review.createdAt).toLocaleString("ar-SA")}</small></summary>
      <div className="legal-review-body">{review.contractSnapshot && <div className="legal-review-contract"><strong>{review.contractSnapshot.title}</strong><p>{review.contractSnapshot.clientName} · {review.contractSnapshot.workSite}</p><p>{review.contractSnapshot.startDate} — {review.contractSnapshot.endDate}</p><a href={`/api/portal/documents/${review.contractSnapshot.documentId}?inline=1&language=bilingual`} target="_blank" rel="noreferrer">معاينة نسخة العقد الحالية</a></div>}{review.clauses.filter(item=>item.included).map((clause,index)=><details className="legal-review-clause" key={index}><summary>{contractClauseLabel(review.clauses.filter(item=>item.included),index)} / {contractClauseLabel(review.clauses.filter(item=>item.included),index,"en")}</summary><p dir="rtl">{clause.body}</p><p dir="ltr">{clause.bodyEn}</p>{clause.subclauses?.map((sub,number)=><div className="legal-review-subclause" key={number}><p>{number+1}. {sub.body}</p><p dir="ltr">{number+1}. {sub.bodyEn}</p></div>)}</details>)}
      {review.recommendation && <div className="legal-review-recommendation"><strong>التوصية القانونية</strong><p>{review.recommendation}</p><small>{review.reviewer} · {review.reviewedAt && new Date(review.reviewedAt).toLocaleString("ar-SA")}</small></div>}
      {canReview && !compact && review.status==="pending" && <form onSubmit={event=>void decide(event,review)}><fieldset disabled={busy===review.id}><label>التوصية القانونية<textarea name="recommendation" required minLength={10} maxLength={6000} rows={4}/></label>{review.kind==="defaults" ? <label>قرار المراجعة<select name="action" required defaultValue=""><option value="" disabled>اختر القرار</option><option value="approve">اعتماد البنود وتفعيل القالب</option><option value="reject">إعادة للتعديل</option></select></label>:<input type="hidden" name="action" value="recommend"/>}<button type="submit" className="admin-primary">{busy===review.id ? "جارٍ الحفظ...":"إرسال التوصية"}</button></fieldset></form>}
      </div></details>)}</div>{loaded && !visible.length && <p className="legal-empty">لا توجد مراجعات ضمن هذا التصنيف.</p>}
  </section>;
}
