"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initial API hydration selects the first returned case */
import {FormEvent,useCallback,useEffect,useMemo,useState}from"react";
type Matter={id:number;referenceCode:string;title:string;counterparty:string;status:string;referralReason:string|null;fileSnapshotJson:string|null};
type Activity={id:number;legalRecordId:number;activityType:string;title:string;details:string|null;priority:string;status:string;dueAt:string|null;assignedTo:string|null};
type Data={cases:Matter[];activities:Activity[];canWrite:boolean;canApprove:boolean};
const types:Record<string,string>={task:"مهمة",deadline:"موعد نظامي",note:"ملاحظة",communication:"مراسلة",hearing:"جلسة",settlement:"تسوية"};
export default function LegalCaseWorkspace(){const[data,setData]=useState<Data|null>(null);const[selected,setSelected]=useState(0);const[notice,setNotice]=useState("");const load=useCallback(async()=>{const response=await fetch("/api/portal/legal-cases",{cache:"no-store"});const result=await response.json()as Data&{error?:string};if(!response.ok)throw new Error(result.error||"تعذر تحميل القضايا");setData(result);setSelected(value=>value||result.cases[0]?.id||0)},[]);useEffect(()=>{void load().catch(error=>setNotice(error instanceof Error?error.message:"تعذر التحميل"))},[load]);const matter=data?.cases.find(item=>item.id===selected);const activities=useMemo(()=>data?.activities.filter(item=>item.legalRecordId===selected)||[],[data,selected]);async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const body=Object.fromEntries(new FormData(form).entries());const response=await fetch("/api/portal/legal-cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,legalRecordId:selected})});const result=await response.json()as{error?:string};if(!response.ok){setNotice(result.error||"تعذر حفظ الإجراء");return}form.reset();setNotice("تمت إضافة الإجراء إلى سجل القضية.");await load()}async function update(id:number,status:string){const response=await fetch("/api/portal/legal-cases",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});const result=await response.json()as{error?:string};if(!response.ok){setNotice(result.error||"تعذر تحديث الإجراء");return}await load()}
if(!data)return <section className="panel legal-matter-workspace"><p>{notice||"جارٍ تحميل إدارة القضايا..."}</p></section>;return <section className="panel legal-matter-workspace"><header><div><span>إدارة المسائل القانونية</span><h2>لوحة القضايا والإجراءات والمواعيد</h2><p>مصدر موحد للملف والمستندات والمهام والمراسلات والمواعيد وسجل القرار.</p></div><b>{data.cases.filter(item=>item.status!=="closed").length} ملف مفتوح</b></header>{notice&&<p className="operations-notice">{notice}</p>}<div className="legal-matter-layout"><aside>{data.cases.map(item=><button key={item.id} className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)}><strong>{item.referenceCode}</strong><span>{item.counterparty}</span><small>{item.status}</small></button>)}</aside><main>{matter?<><div className="legal-matter-head"><div><h3>{matter.title}</h3><p>{matter.referralReason||"ملف قانوني مسجل يدويًا"}</p></div><span>{activities.filter(item=>!["completed","cancelled"].includes(item.status)).length} إجراءات مفتوحة</span></div>{data.canWrite&&<form className="legal-activity-form" onSubmit={add}><select name="activityType" required defaultValue="task">{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="title" required minLength={3} placeholder="عنوان الإجراء"/><select name="priority" defaultValue="medium"><option value="low">منخفض</option><option value="medium">متوسط</option><option value="high">عالٍ</option><option value="critical">عاجل</option></select><input name="dueAt" type="datetime-local"/><input name="assignedTo" type="email" placeholder="المسؤول بالبريد"/><textarea name="details" placeholder="الملاحظات والخطوة المطلوبة"/><button>إضافة إلى القضية</button></form>}<div className="legal-timeline">{activities.map(item=><article key={item.id} className={`${item.priority} ${item.status}`}><i/><div><header><strong>{types[item.activityType]||item.activityType} — {item.title}</strong><span>{item.priority}</span></header><p>{item.details||"دون ملاحظات إضافية"}</p><small>{item.dueAt?`الموعد: ${new Date(item.dueAt).toLocaleString("ar-SA")}`:"دون موعد"}{item.assignedTo?` · المسؤول: ${item.assignedTo}`:""}</small></div>{data.canWrite&&!["completed","cancelled"].includes(item.status)&&<div><button onClick={()=>void update(item.id,"in_progress")}>قيد التنفيذ</button><button onClick={()=>void update(item.id,"completed")}>إكمال</button></div>}</article>)}{!activities.length&&<p className="legal-empty">لا توجد إجراءات مسجلة لهذه القضية.</p>}</div></>:<p className="legal-empty">اختر ملفًا قانونيًا.</p>}</main></div></section>}
