"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Supplier={id:number;supplierCode:string;legalName:string;vatNumber:string|null;status:string};
type Invoice={id:number;referenceCode:string;supplierInvoiceNumber:string;expenseType:string;supplierId:number|null;employeeId:number|null;contractId:number|null;documentId:number;invoiceDate:string;dueDate:string;description:string;subtotalHalalas:number;vatHalalas:number;totalHalalas:number;status:string;postingStatus:string;journalEntryId:number|null;createdBy:string};
type Data={suppliers:Supplier[];invoices:Invoice[];employees:{id:number;employeeNumber:string;fullName:string}[];contracts:{id:number;referenceCode:string;clientName:string}[];entries:{id:number;status:string;entryNumber:string}[];receivables:{id:number;referenceCode:string;dueDate:string;amountHalalas:number;contractId:number|null}[]};
const labels:Record<string,string>={supplier_invoice:"فاتورة مورد",employee_expense:"مصروف موظف",draft:"مسودة",approved:"معتمدة",posted:"مرحّلة",paid:"مدفوعة",unposted:"غير مربوطة",reversed:"معكوسة"};
const sar=(h:number)=>(h/100).toLocaleString("ar-SA",{style:"currency",currency:"SAR"});
function ageBucket(due:string){const days=Math.floor((Date.now()-new Date(`${due}T00:00:00`).getTime())/86400000);return days<=0?"غير مستحق":days<=30?"1–30 يوم":days<=60?"31–60 يوم":days<=90?"61–90 يوم":"أكثر من 90 يوم";}

export default function PurchasingWorkspace({canWrite}:{canWrite:boolean}){
 const[data,setData]=useState<Data>({suppliers:[],invoices:[],employees:[],contracts:[],entries:[],receivables:[]});const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/portal/purchasing",{cache:"no-store"});const j=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(j.error||"تعذّر تحميل المشتريات");setData(j);},[]);
 useEffect(()=>{void load().catch(e=>setNotice(e instanceof Error?e.message:"تعذّر التحميل"));},[load]);
 async function addSupplier(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const f=new FormData(event.currentTarget);try{const r=await fetch("/api/portal/purchasing",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const j=await r.json() as{error?:string};if(!r.ok)throw new Error(j.error||"تعذّر الحفظ");event.currentTarget.reset();await load();setNotice("تمت إضافة المورد.");}catch(e){setNotice(e instanceof Error?e.message:"تعذّر الحفظ");}finally{setBusy(false)}}
 async function addInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const form=event.currentTarget;try{const r=await fetch("/api/portal/purchasing",{method:"POST",body:new FormData(form)});const j=await r.json() as{error?:string};if(!r.ok)throw new Error(j.error||"تعذّر الحفظ");form.reset();await load();setNotice("حُفظت الفاتورة ومرفقها الإلزامي.");}catch(e){setNotice(e instanceof Error?e.message:"تعذّر الحفظ");}finally{setBusy(false)}}
 async function action(id:number,action:string){setBusy(true);setNotice("");try{const r=await fetch("/api/portal/purchasing",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});const j=await r.json() as{error?:string};if(!r.ok)throw new Error(j.error||"تعذّر التنفيذ");await load();setNotice(action==="approve"?"تم الاعتماد وإنشاء قيد مسودة متوازن. يلزم مستخدم آخر لاعتماد القيد وترحيله.":action==="pay"?"أُنشئ قيد السداد كمسودة. اعتمده ورحّله ثم اضغط مزامنة.":"تمت مزامنة حالة الترحيل والسداد.");}catch(e){setNotice(e instanceof Error?e.message:"تعذّر التنفيذ");}finally{setBusy(false)}}
 const aging=useMemo(()=>data.invoices.filter(x=>["approved","posted","payment_pending"].includes(x.status)).reduce<Record<string,number>>((a,x)=>{const k=ageBucket(x.dueDate);a[k]=(a[k]||0)+x.totalHalalas;return a},{}),[data.invoices]);
 const customerAging=useMemo(()=>data.receivables.reduce<Record<string,number>>((a,x)=>{const k=ageBucket(x.dueDate);a[k]=(a[k]||0)+x.amountHalalas;return a},{}),[data.receivables]);
 return <section className="purchasing-workspace"><div className="panel-head"><div><h2>الموردون والمشتريات</h2><p>فاتورة أو مصروف موظف بمرفق إلزامي، واعتماد منفصل وربط محاسبي.</p></div><span className="panel-count">{data.invoices.length} فاتورة</span></div>{notice&&<div className="operations-notice" role="status">{notice}</div>}
 {canWrite&&<div className="purchase-forms"><form onSubmit={addSupplier}><h3>إضافة مورد</h3><input name="legalName" required minLength={3} placeholder="الاسم القانوني"/><input name="vatNumber" placeholder="الرقم الضريبي"/><input name="commercialRegistration" placeholder="السجل التجاري"/><input name="contactName" placeholder="مسؤول التواصل"/><input name="mobile" placeholder="الجوال"/><button disabled={busy}>حفظ المورد</button></form><form onSubmit={addInvoice}><h3>تسجيل فاتورة أو مصروف</h3><select name="expenseType" required defaultValue="supplier_invoice"><option value="supplier_invoice">فاتورة مورد</option><option value="employee_expense">مصروف موظف</option></select><select name="supplierId" defaultValue=""><option value="">اختر المورد عند فاتورة المورد</option>{data.suppliers.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.legalName}</option>)}</select><select name="employeeId" defaultValue=""><option value="">اختر الموظف عند مصروف الموظف</option>{data.employees.map(x=><option key={x.id} value={x.id}>{x.employeeNumber} — {x.fullName}</option>)}</select><select name="contractId" defaultValue=""><option value="">بدون عقد / مركز تكلفة</option>{data.contracts.map(x=><option key={x.id} value={x.id}>{x.referenceCode} — {x.clientName}</option>)}</select><input name="supplierInvoiceNumber" required placeholder="رقم فاتورة المورد / الإيصال"/><input name="description" required minLength={3} placeholder="البيان"/><label>تاريخ الفاتورة<input name="invoiceDate" type="date" required/></label><label>تاريخ الاستحقاق<input name="dueDate" type="date" required/></label><input name="subtotal" type="number" min="0" step="0.01" required placeholder="المبلغ قبل الضريبة"/><input name="vat" type="number" min="0" step="0.01" defaultValue="0" required placeholder="الضريبة"/><label className="purchase-file">المرفق إلزامي (PDF/JPG/PNG حتى 12MB)<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><button disabled={busy}>حفظ مع المرفق</button></form></div>}
 <div className="posting-table"><table><thead><tr><th>المرجع</th><th>النوع والطرف</th><th>الاستحقاق</th><th>المبلغ</th><th>القيد</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{data.invoices.map(x=>{const supplier=data.suppliers.find(s=>s.id===x.supplierId);const employee=data.employees.find(e=>e.id===x.employeeId);const entry=data.entries.find(e=>e.id===x.journalEntryId);return <tr key={x.id}><td><strong dir="ltr">{x.referenceCode}</strong><small dir="ltr">{x.supplierInvoiceNumber}</small></td><td>{labels[x.expenseType]}<small>{supplier?.legalName||employee?.fullName||"—"}</small></td><td>{x.dueDate}<small>{ageBucket(x.dueDate)}</small></td><td>{sar(x.totalHalalas)}<small>ضريبة {sar(x.vatHalalas)}</small></td><td>{entry?<><strong dir="ltr">{entry.entryNumber}</strong><small>{labels[entry.status]||entry.status}</small></>:"—"}</td><td><span className={`workflow-status ${x.postingStatus}`}>{labels[x.status]||x.status}</span></td><td>{canWrite&&x.status==="draft"?<button disabled={busy} onClick={()=>void action(x.id,"approve")}>اعتماد</button>:canWrite&&x.journalEntryId&&x.postingStatus!=="posted"?<button disabled={busy} onClick={()=>void action(x.id,"sync")}>مزامنة</button>:canWrite&&x.status==="posted"?<button disabled={busy} onClick={()=>void action(x.id,"pay")}>إنشاء سداد</button>:canWrite&&x.status==="payment_pending"?<button disabled={busy} onClick={()=>void action(x.id,"sync")}>مزامنة السداد</button>:"—"}</td></tr>})}</tbody></table>{!data.invoices.length&&<p className="empty-operational">لا توجد فواتير مشتريات بعد.</p>}</div>
 <div className="aging-grids"><div className="aging-summary"><h3>أعمار ديون العملاء</h3>{["غير مستحق","1–30 يوم","31–60 يوم","61–90 يوم","أكثر من 90 يوم"].map(k=><article key={k}><span>{k}</span><strong>{sar(customerAging[k]||0)}</strong></article>)}</div><div className="aging-summary"><h3>أعمار ديون الموردين</h3>{["غير مستحق","1–30 يوم","31–60 يوم","61–90 يوم","أكثر من 90 يوم"].map(k=><article key={k}><span>{k}</span><strong>{sar(aging[k]||0)}</strong></article>)}</div></div></section>
}
