"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type RoleDefinition={roleKey:string;labelAr:string;description:string|null;permissionsJson:string;protected:boolean;active:boolean;updatedAt:string};
const permissionLabels:Record<string,string>={
  "overview.read":"عرض لوحة المتابعة","employees.read":"عرض الموظفين","employees.write":"تعديل الموظفين","employees.approve":"اعتماد إجراءات الموظفين",
  "finance.read":"عرض المالية","finance.write":"إنشاء وتعديل المالية","finance.approve":"اعتماد المعاملات المالية","finance.post":"ترحيل القيود","finance.pay":"إطلاق المدفوعات",
  "legal.read":"عرض الشؤون القانونية","legal.write":"تعديل السجلات القانونية","legal.approve":"الاعتماد القانوني","workforce.read":"عرض العمالة","workforce.write":"تعديل العمالة والتشغيل","workforce.approve":"اعتماد التشغيل والساعات",
  "construction.read":"عرض المقاولات","construction.write":"تعديل المقاولات","construction.approve":"اعتماد المقاولات","documents.read":"عرض المستندات","documents.write":"إصدار وتعديل المستندات","documents.share":"مشاركة المستندات",
  "conversations.read":"عرض المحادثات","conversations.write":"الرد على المحادثات","website.read":"عرض إدارة الموقع","website.write":"تعديل ونشر الموقع","reports.read":"عرض التقارير","reports.export":"تصدير التقارير",
  "video.read":"عرض المقابلات المرئية","video.manage":"استقبال وإدارة المقابلات","video.transfer":"تحويل المقابلات للموظفين",
  "assets.administer":"إدارة الختم والتوقيع والهوية","users.administer":"إدارة المستخدمين والأدوار","integrations.administer":"إدارة التكاملات",
};
const parse=(role:RoleDefinition)=>{try{return JSON.parse(role.permissionsJson)as string[]}catch{return[]}};

export default function RoleDefinitionManager(){
  const[roles,setRoles]=useState<RoleDefinition[]>([]);const[available,setAvailable]=useState<string[]>([]);const[editing,setEditing]=useState<RoleDefinition|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/portal/role-definitions",{cache:"no-store"});const data=await response.json()as{roles?:RoleDefinition[];availablePermissions?:string[];error?:string};if(!response.ok)throw new Error(data.error||"تعذر تحميل الأدوار");setRoles(data.roles||[]);setAvailable(data.availablePermissions||[])},[]);
  useEffect(()=>{let active=true;void fetch("/api/portal/role-definitions",{cache:"no-store"}).then(async response=>{const data=await response.json()as{roles?:RoleDefinition[];availablePermissions?:string[];error?:string};if(!response.ok)throw new Error(data.error||"تعذر تحميل الأدوار");if(active){setRoles(data.roles||[]);setAvailable(data.availablePermissions||[])}}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const formData=new FormData(form);const selected=editing?.protected?["*"]:formData.getAll("permissions").map(String);const payload={roleKey:String(formData.get("roleKey")||""),labelAr:String(formData.get("labelAr")||""),description:String(formData.get("description")||""),permissions:selected,active:editing?(editing.protected?editing.active:formData.get("active")==="on"):true,reason:String(formData.get("reason")||"")};setBusy(true);setNotice("");try{const response=await fetch("/api/portal/role-definitions",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json()as{error?:string};if(!response.ok)throw new Error(result.error||"تعذر حفظ الدور");setEditing(null);form.reset();await load();setNotice(editing?"تم تعديل الدور وتطبيق الصلاحيات الجديدة.":"تم إنشاء الدور وأصبح متاحاً للإسناد.")}catch(error){setNotice(error instanceof Error?error.message:"تعذر الحفظ")}finally{setBusy(false)}}
  async function deleteRole(role:RoleDefinition){const reason=window.prompt(`اكتب سبب حذف دور «${role.labelAr}» (10 أحرف على الأقل):`,"");if(!reason)return;setBusy(true);setNotice("");try{const response=await fetch("/api/portal/role-definitions",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({roleKey:role.roleKey,reason})});const result=await response.json()as{error?:string};if(!response.ok)throw new Error(result.error||"تعذر حذف الدور");if(editing?.roleKey===role.roleKey)setEditing(null);await load();setNotice("تم حذف الدور بعد التحقق من عدم ارتباطه بأي مستخدم نشط.")}catch(error){setNotice(error instanceof Error?error.message:"تعذر الحذف")}finally{setBusy(false)}}
  const selected=new Set(editing?parse(editing):[]);
  return <section className="panel role-definition-manager"><header><div><h2>تعريف الأدوار والصلاحيات</h2><p>يمكن للمالك ومشرف النظام إنشاء الأدوار وتعديلها وحذف غير المرتبط منها. الأدوار الجذرية محمية.</p></div><b>{roles.filter(role=>role.active).length} دور نشط</b></header>{notice&&<div className="operations-notice" role="status">{notice}</div>}<form onSubmit={save} key={editing?.roleKey||"new"} className="role-definition-form"><div className="role-definition-fields"><input name="roleKey" dir="ltr" required pattern="[a-z][a-z0-9_]{2,63}" readOnly={Boolean(editing)} defaultValue={editing?.roleKey||""} placeholder="role_key"/><input name="labelAr" required minLength={3} defaultValue={editing?.labelAr||""} placeholder="اسم الدور بالعربية"/><input name="description" defaultValue={editing?.description||""} placeholder="وصف مسؤوليات الدور"/>{editing&&<label className="role-active"><input name="active" type="checkbox" defaultChecked={editing.active} disabled={editing.protected}/>دور نشط</label>}</div><fieldset><legend>الصلاحيات</legend><div className="role-permission-grid">{available.map(permission=>{const restricted=permission==="users.administer"&&(!editing||!["system_owner","system_admin"].includes(editing.roleKey));return <label key={permission} className={restricted?"restricted":""}><input type="checkbox" name="permissions" value={permission} defaultChecked={selected.has(permission)} disabled={restricted}/><span>{permissionLabels[permission]||permission}</span><small dir="ltr">{restricted?"محصورة في المالك ومشرف النظام":permission}</small></label>})}</div></fieldset>{editing&&<textarea name="reason" required minLength={10} placeholder="سبب تعديل الصلاحيات (10 أحرف على الأقل)"/>}<div className="role-definition-actions"><button disabled={busy}>{busy?"جارٍ الحفظ...":editing?"حفظ تعديل الدور":"إضافة الدور"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>إلغاء</button>}</div></form><div className="role-definition-list">{roles.map(role=><article key={role.roleKey} className={role.active?"":"inactive"}><div><strong>{role.labelAr}</strong><code>{role.roleKey}</code><p>{role.description||"دون وصف"}</p><small>{parse(role).length} صلاحية · {role.active?"نشط":"موقوف"}{role.protected?" · محمي":""}</small></div><div className="role-card-actions"><button disabled={busy} onClick={()=>setEditing(role)}>تعديل</button>{!role.protected&&<button className="danger" disabled={busy} onClick={()=>void deleteRole(role)}>حذف</button>}</div></article>)}</div></section>;
}
