"use client";

import { FormEvent, useEffect, useState } from "react";

type Representative = { id:number; representativeCode:string; fullName:string; mobile:string; email:string|null; region:string; commissionBps:number; status:string; clientCount:number; contractCount:number; contractValueHalalas:number };

export default function SalesRepresentativesWorkspace({ canWrite }: { canWrite:boolean }) {
  const [rows,setRows]=useState<Representative[]>([]); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=()=>{void fetch("/api/portal/sales-representatives",{cache:"no-store"}).then(r=>r.json() as Promise<{representatives?:Representative[];error?:string}>).then(data=>{if(!data.representatives)throw new Error(data.error);setRows(data.representatives)}).catch(e=>setError(e instanceof Error?e.message:"تعذّر تحميل المناديب"));};
  useEffect(()=>{load();},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const payload=Object.fromEntries(new FormData(event.currentTarget).entries());try{const response=await fetch("/api/portal/sales-representatives",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {representative?:Representative;error?:string};if(!response.ok||!data.representative)throw new Error(data.error||"تعذّر الحفظ");setRows(items=>[data.representative!,...items]);setOpen(false)}catch(e){setError(e instanceof Error?e.message:"تعذّر الحفظ")}finally{setBusy(false)}}
  return <><div className="content-heading module-heading"><div><p className="admin-eyebrow">المبيعات الميدانية</p><h1>إدارة المناديب</h1><span>ملف موحد للمندوب وربطه بالعملاء والعقود وقيم المبيعات والعمولات.</span></div>{canWrite&&<button className="admin-primary" onClick={()=>setOpen(true)}>+ إضافة مندوب</button>}</div>{error&&<p className="form-hint">{error}</p>}<section className="panel"><div className="panel-head"><div><h2>سجل المناديب</h2><p>{rows.length} مندوب مسجل</p></div></div><div className="management-table-wrap"><table className="management-table representatives-table"><thead><tr><th>المندوب</th><th>التواصل</th><th>المنطقة</th><th>العملاء</th><th>العقود</th><th>قيمة العقود</th><th>العمولة</th><th>الحالة</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.fullName}</strong><small dir="ltr">{row.representativeCode}</small></td><td><strong dir="ltr">{row.mobile}</strong><small dir="ltr">{row.email||"—"}</small></td><td>{row.region}</td><td>{row.clientCount}</td><td>{row.contractCount}</td><td>{new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(row.contractValueHalalas/100)}</td><td>{(row.commissionBps/100).toFixed(2)}%</td><td><span className={`status-pill ${row.status==="active"?"status-contacted":"status-closed"}`}>{row.status==="active"?"نشط":"غير نشط"}</span></td></tr>)}</tbody></table></div></section>{open&&<div className="modal-layer"><button className="drawer-backdrop" aria-label="إغلاق" onClick={()=>setOpen(false)}/><section className="record-modal" role="dialog" aria-modal="true"><div className="drawer-head"><div><span>المبيعات</span><h2>إضافة مندوب</h2></div><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><label>الاسم الكامل<input name="fullName" required minLength={3}/></label><label>رقم الجوال<input name="mobile" required dir="ltr"/></label><label>البريد الإلكتروني<input name="email" type="email" dir="ltr"/></label><label>رقم الهوية<input name="nationalId" pattern="[0-9]{10}" maxLength={10} dir="ltr"/></label><label>المنطقة<input name="region" defaultValue="مكة المكرمة" required/></label><label>نسبة العمولة %<input name="commissionPercent" type="number" min="0" max="100" step="0.01" defaultValue="0"/></label><div className="modal-actions span-two"><button type="button" onClick={()=>setOpen(false)}>إلغاء</button><button className="admin-primary" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ المندوب"}</button></div></form></section></div>}</>;
}
