"use client";
import {useRef,useState} from "react";
import {readApiJson} from "@/lib/client-api";
import {newWebsiteSection,sectionLayouts,safeWebsiteButtonHref} from "@/lib/website-section-design";
import type {ManagedBlock} from "@/lib/website-content";
const names:Record<string,string>={text:"نص متكامل",split:"صورة ونص",features:"بطاقات المزايا",steps:"خطوات العمل",callout:"دعوة للتواصل",image:"صورة عريضة"};
export default function WebsiteSectionEditor({blocks,disabled,onChange,onUploadStateChange,linkTargets=[]}:{linkTargets?:{label:string;href:string}[];blocks:ManagedBlock[];disabled:boolean;onChange:(blocks:ManagedBlock[])=>void;onUploadStateChange:(busy:boolean)=>void}) {
  const [selected,setSelected]=useState<number|null>(null);
  const [error,setError]=useState("");
  const [uploading,setUploading]=useState(false);
  const textArea=useRef<HTMLTextAreaElement>(null);
  const active=selected===null?null:blocks[selected];
  function update(index:number,patch:Partial<ManagedBlock>){onChange(blocks.map((block,i)=>i===index?{...block,...patch}:block));}
  function add(layout:ManagedBlock["layout"]){if(disabled||blocks.length>=24)return;onChange([...blocks,newWebsiteSection(layout)]);setSelected(blocks.length);}
  function move(index:number,direction:number){const next=structuredClone(blocks);const destination=index+direction;if(destination<0||destination>=next.length)return;[next[index],next[destination]]=[next[destination],next[index]];onChange(next);setSelected(destination);}
  function duplicate(index:number){if(blocks.length>=24)return;const copy=structuredClone(blocks[index]);copy.id=crypto.randomUUID();onChange([...blocks.slice(0,index+1),copy,...blocks.slice(index+1)]);setSelected(index+1);}
  function format(marker:string){if(selected===null||!active||!textArea.current||active.text.length+marker.length*2>4000)return;const area=textArea.current;const start=area.selectionStart,end=area.selectionEnd;const value=active.text;update(selected,{text:value.slice(0,start)+marker+value.slice(start,end)+marker+value.slice(end)});requestAnimationFrame(()=>{area.focus();area.setSelectionRange(start+marker.length,end+marker.length);});}
  async function upload(file:File,index:number){if(disabled||uploading)return;setUploading(true);onUploadStateChange(true);setError("");try{const body=new FormData();body.set("file",file);const response=await fetch("/api/portal/website/assets",{method:"POST",body});const result=await readApiJson(response) as {url?:string;error?:string};if(!response.ok||!result.url)throw new Error(result.error||"تعذّر رفع الصورة");update(index,{image:result.url});}catch(error){setError(error instanceof Error?error.message:"تعذّر رفع الصورة");}finally{setUploading(false);onUploadStateChange(false);}}
  return <section className="section-builder"><header><div><h4>أقسام الصفحة</h4><p>اختر تخطيطًا ثم حرر المحتوى والمظهر والأزرار.</p></div><span>{blocks.length} / 24</span></header><div className="section-template-library">{sectionLayouts.map((layout,index)=><button type="button" key={layout} disabled={disabled||blocks.length>=24} onClick={()=>add(layout)}><span aria-hidden="true">{String(index+1).padStart(2,"0")}</span><strong>{names[layout]}</strong></button>)}</div>
    <div className="section-builder-workspace"><ol className="section-layers">{blocks.map((block,index)=><li key={block.id||index} draggable={!disabled} onDragStart={event=>event.dataTransfer.setData("application/dali-section",String(index))} onDragOver={event=>{if(!disabled)event.preventDefault();}} onDrop={event=>{event.preventDefault();if(disabled)return;const raw=event.dataTransfer.getData("application/dali-section");if(!/^\d+$/.test(raw))return;const from=Number(raw);if(from>=blocks.length||from===index)return;const next=structuredClone(blocks);const [moved]=next.splice(from,1);next.splice(index,0,moved);onChange(next);setSelected(index);}}><button type="button" aria-pressed={selected===index} onClick={()=>setSelected(index)}><small>{index+1}</small><span>{block.title||names[block.layout||"text"]}</span>{block.hidden&&<b>مخفي</b>}</button></li>)}</ol>
    {active&&selected!==null?<div className="section-properties"><div className="section-action-bar"><button type="button" disabled={disabled||selected===0} onClick={()=>move(selected,-1)}>تقديم</button><button type="button" disabled={disabled||selected===blocks.length-1} onClick={()=>move(selected,1)}>تأخير</button><button type="button" disabled={disabled||blocks.length>=24} onClick={()=>duplicate(selected)}>نسخ القسم</button><button type="button" disabled={disabled} onClick={()=>update(selected,{hidden:!active.hidden})}>{active.hidden?"إظهار القسم":"إخفاء القسم"}</button><button type="button" className="danger" disabled={disabled} onClick={()=>{onChange(blocks.filter((_,i)=>i!==selected));setSelected(null);}}>حذف القسم</button></div>
      <details open><summary>المحتوى</summary><label>عنوان القسم<input value={active.title} maxLength={180} disabled={disabled} onChange={event=>update(selected,{title:event.target.value})}/></label><label>محتوى القسم<div className="text-format-toolbar"><button type="button" disabled={disabled} onClick={()=>format("**")}>غامق</button><button type="button" disabled={disabled} onClick={()=>format("*")}>مائل</button></div><textarea ref={textArea} value={active.text} maxLength={4000} rows={6} disabled={disabled} onChange={event=>update(selected,{text:event.target.value})}/></label><label>نقاط القسم<textarea value={active.checklist.join("\n")} rows={4} disabled={disabled} onChange={event=>update(selected,{checklist:event.target.value.split("\n").slice(0,20)})}/></label></details>
      <details><summary>المظهر والتخطيط</summary><div className="section-design-grid"><label>التخطيط<select value={active.layout||"text"} disabled={disabled} onChange={event=>update(selected,{layout:event.target.value as ManagedBlock["layout"]})}>{sectionLayouts.map(layout=><option key={layout} value={layout}>{names[layout]}</option>)}</select></label><label>لوحة الألوان<select value={active.tone||"light"} disabled={disabled} onChange={event=>update(selected,{tone:event.target.value as ManagedBlock["tone"]})}><option value="light">فاتح</option><option value="dark">داكن</option><option value="gold">ذهبي</option></select></label><label>المحاذاة<select value={active.align||"start"} disabled={disabled} onChange={event=>update(selected,{align:event.target.value as ManagedBlock["align"]})}><option value="start">بداية السطر</option><option value="center">وسط</option><option value="end">نهاية السطر</option></select></label><label>المسافات<select value={active.spacing||"normal"} disabled={disabled} onChange={event=>update(selected,{spacing:event.target.value as ManagedBlock["spacing"]})}><option value="compact">مدمجة</option><option value="normal">متوازنة</option><option value="spacious">واسعة</option></select></label></div></details>
      <details><summary>الصورة</summary><label>مسار الصورة<input dir="ltr" value={active.image||""} disabled={disabled} onChange={event=>update(selected,{image:event.target.value})}/></label><label>وصف الصورة البديل<input value={active.imageAlt||""} maxLength={240} disabled={disabled} onChange={event=>update(selected,{imageAlt:event.target.value})}/></label><label className="visual-image-upload">رفع صورة<input type="file" accept="image/png,image/jpeg" disabled={disabled||uploading} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file,selected);event.target.value="";}}/></label><button type="button" disabled={disabled} onClick={()=>update(selected,{image:""})}>إزالة الصورة</button></details>
      <details><summary>الأزرار والروابط</summary><button type="button" disabled={disabled||(active.buttons?.length||0)>=4} onClick={()=>update(selected,{buttons:[...(active.buttons||[]),{label:"تواصل معنا",href:"/contact",style:"solid",newTab:false}]})}>إضافة زر</button>{active.buttons?.map((button,index)=>{function patch(value:Partial<typeof button>){update(selected!,{buttons:active!.buttons!.map((item,i)=>i===index?{...item,...value}:item)});}return <article key={index} className="section-button-editor"><label>نص الزر<input value={button.label} maxLength={100} disabled={disabled} onChange={event=>patch({label:event.target.value})}/></label><label>الصفحة المستهدفة<select disabled={disabled} value={linkTargets.some(target=>target.href===button.href)?button.href:""} onChange={event=>{if(event.target.value)patch({href:event.target.value});}}><option value="">رابط مخصص</option>{linkTargets.map((target,i)=><option key={`${target.href}-${i}`} value={target.href}>{target.label}</option>)}</select></label><label>رابط الزر<input dir="ltr" value={button.href} maxLength={1200} disabled={disabled} onChange={event=>patch({href:event.target.value})} aria-invalid={!safeWebsiteButtonHref(button.href)}/></label>{!safeWebsiteButtonHref(button.href)&&<p role="alert">أدخل رابط صفحة عامة أو رابط HTTPS أو بريدًا أو هاتفًا.</p>}<label>نمط الزر<select value={button.style} disabled={disabled} onChange={event=>patch({style:event.target.value==="outline"?"outline":"solid"})}><option value="solid">ممتلئ</option><option value="outline">محدد</option></select></label><label className="checkbox-field"><input type="checkbox" checked={button.newTab} disabled={disabled} onChange={event=>patch({newTab:event.target.checked})}/>فتح في نافذة جديدة</label><button type="button" className="danger" disabled={disabled} onClick={()=>update(selected,{buttons:active.buttons!.filter((_,i)=>i!==index)})}>حذف الزر</button></article>;})}</details>
    </div>:<div className="section-builder-empty"><h4>اختر قسمًا للتحرير</h4><p>أضف قسمًا من مكتبة التخطيطات أو اختر قسمًا من القائمة.</p></div>}</div>{error&&<p role="alert">{error}</p>}
  </section>;
}
