"use client";

import { useMemo, useState } from "react";

type Contract={id:number;referenceCode:string;clientName:string;title:string;workSite:string;startDate:string;endDate:string;status:string};
type Profession={id:number;contractId:number;profession:string;requiredCount:number};
type Assignment={id:number;contractId:number;contractProfessionId:number;workerId:number;status:string};
type Worker={id:number;fullName:string;profession:string;clientSite:string;status:string};
const statusLabels:Record<string,string>={draft:"مسودة",internal_review:"مراجعة داخلية",legal_review:"مراجعة قانونية",approved:"معتمد",sent:"مرسل",signed:"موقّع",active:"ساري",suspended:"معلّق",expired:"منتهي",terminated:"منهى",cancelled:"ملغى",superseded:"مستبدل"};

export default function WorkforceSupervisionWorkspace({contracts,professions,assignments,workers,onOpenContract}:{contracts:Contract[];professions:Profession[];assignments:Assignment[];workers:Worker[];onOpenContract:(id:number)=>void}){
  const[query,setQuery]=useState(""),[coverage,setCoverage]=useState<"all"|"shortage"|"complete">("all");
  const operational=useMemo(()=>contracts.filter(contract=>!["terminated","cancelled","superseded"].includes(contract.status)).map(contract=>{const requirements=professions.filter(item=>item.contractId===contract.id),required=requirements.reduce((sum,item)=>sum+item.requiredCount,0),active=assignments.filter(item=>item.contractId===contract.id&&item.status==="active"),assignedWorkers=workers.filter(worker=>active.some(item=>item.workerId===worker.id)),shortage=Math.max(0,required-active.length),percent=required?Math.min(100,Math.round(active.length/required*100)):0;return{contract,requirements,required,active,assignedWorkers,shortage,percent}}),[contracts,professions,assignments,workers]);
  const filtered=operational.filter(row=>{const haystack=`${row.contract.referenceCode} ${row.contract.clientName} ${row.contract.title} ${row.contract.workSite}`.toLowerCase();return(!query.trim()||haystack.includes(query.trim().toLowerCase()))&&(coverage==="all"||(coverage==="shortage"?row.shortage>0:row.shortage===0))});
  const totalRequired=operational.reduce((sum,row)=>sum+row.required,0),totalAssigned=operational.reduce((sum,row)=>sum+row.active.length,0),available=workers.filter(worker=>worker.status==="available").length;
  return <section className="workforce-supervision-workspace">
    <header className="feature-heading"><div><span>التشغيل الميداني المرتبط بالعقود</span><h1>إدارة الإشراف على العمالة</h1><p>متابعة التغطية واختيار العمالة المتاحة ثم فتح العقد للإسناد أو الإعادة وتسجيل الغياب وفق الصلاحية.</p></div><b>{operational.length}<small>عقد قابل للإدارة</small></b></header>
    <div className="supervision-kpis"><article><span>المطلوب</span><strong>{totalRequired}</strong></article><article><span>المسند</span><strong>{totalAssigned}</strong></article><article><span>العجز</span><strong>{Math.max(0,totalRequired-totalAssigned)}</strong></article><article><span>عمال متاحون</span><strong>{available}</strong></article></div>
    <section className="panel"><div className="panel-head"><div><h2>العقود ومواقع العمالة</h2><p>البيانات هنا مشتقة من العقد نفسه؛ أي إسناد أو إعادة ينعكس مباشرة على التغطية والموقع.</p></div><div className="supervision-filters"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="بحث بالعميل أو العقد أو الموقع"/><select value={coverage} onChange={event=>setCoverage(event.target.value as typeof coverage)}><option value="all">جميع العقود</option><option value="shortage">عقود بها عجز</option><option value="complete">تغطية مكتملة</option></select></div></div>
      <div className="feature-list supervision-contracts">{filtered.map(({contract,requirements,required,active,assignedWorkers,shortage,percent})=><article key={contract.id}><div className="supervision-contract-main"><header><div><strong>{contract.referenceCode} · {contract.clientName}</strong><small>{contract.title} · {contract.workSite}</small></div><span className={`workflow-status ${contract.status}`}>{statusLabels[contract.status]||contract.status}</span></header><div className="coverage-meter"><span><i style={{width:`${percent}%`}}/></span><b>{active.length}/{required} · {percent}%</b></div><div className="profession-coverage">{requirements.map(item=>{const count=active.filter(row=>row.contractProfessionId===item.id).length,matchingAvailable=workers.filter(worker=>worker.status==="available"&&worker.profession===item.profession).length;return <span key={item.id} className={count<item.requiredCount?"shortage":"complete"}><strong>{item.profession}</strong>{count}/{item.requiredCount}<small>متاح {matchingAvailable}</small></span>})}</div>{assignedWorkers.length>0&&<small>المسندون: {assignedWorkers.map(worker=>worker.fullName).join("، ")}</small>}</div><aside><b className={shortage?"has-shortage":"complete"}>{shortage?"عجز "+shortage:"مكتمل"}</b><small>{contract.startDate} — {contract.endDate}</small><button className="admin-primary" type="button" onClick={()=>onOpenContract(contract.id)}>إدارة العمالة والغياب</button></aside></article>)}{!filtered.length&&<div className="empty-operational">لا توجد عقود مطابقة للبحث أو حالة التغطية.</div>}</div>
    </section>
  </section>;
}
