import { and, desc, eq, isNull } from "drizzle-orm";
import { getDb } from "@/db";
import { complianceObligations, employees, financialRecords, governmentPaymentRequests, governmentSites } from "@/db/schema";
import { auditPortalAction } from "@/lib/audit";
import { decryptCredential, encryptCredential } from "@/lib/credential-vault";
import { emitPortalNotification } from "@/lib/portal-notifications";
import { hasPortalPermission, requirePortalApiRole } from "@/lib/portal-access";
import { jsonNoStore, rejectCrossSiteRequest, requestCorrelationId } from "@/lib/security";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
const id=(value:unknown)=>{const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:0};
const owner=(access:NonNullable<Awaited<ReturnType<typeof requirePortalApiRole>>>)=>access.role==="admin"||access.functionalRoles.some(role=>role==="system_owner"||role==="system_admin");
const reference=()=>`GOV-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,5).toUpperCase()}`;

async function permitted(write=false){const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return null;if(owner(access))return access;return await hasPortalPermission(access,"legal",write?"write":"read")?access:null;}

export async function GET(){const access=await permitted();if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});const db=getDb();const[sites,payments,obligations,staff]=await Promise.all([db.select().from(governmentSites).where(eq(governmentSites.status,"active")).orderBy(governmentSites.name),db.select().from(governmentPaymentRequests).orderBy(desc(governmentPaymentRequests.createdAt)).limit(500),db.select().from(complianceObligations).orderBy(complianceObligations.expiryDate).limit(1000),db.select().from(employees).where(isNull(employees.archivedAt)).orderBy(employees.fullName).limit(2000)]);const renewalItems=staff.flatMap(employee=>[{key:`employee-${employee.id}-iqama`,employeeId:employee.id,employeeNumber:employee.employeeNumber,employeeName:employee.fullName,kind:"iqama",label:"تجديد الإقامة",expiryDate:employee.iqamaExpiry,actionUrl:"https://muqeem.sa/",platform:"مقيم"},...(employee.sponsorshipType==="dali"?[{key:`employee-${employee.id}-contract`,employeeId:employee.id,employeeNumber:employee.employeeNumber,employeeName:employee.fullName,kind:"employment_contract",label:"تجديد عقد العمل",expiryDate:employee.contractEndDate,actionUrl:"https://www.qiwa.sa/",platform:"قوى"},{key:`employee-${employee.id}-work-permit`,employeeId:employee.id,employeeNumber:employee.employeeNumber,employeeName:employee.fullName,kind:"work_permit",label:"تجديد رخصة العمل",expiryDate:employee.workPermitExpiry,actionUrl:"https://www.qiwa.sa/",platform:"قوى"}]:[])]).filter(item=>item.expiryDate).sort((a,b)=>String(a.expiryDate).localeCompare(String(b.expiryDate)));return jsonNoStore({sites:sites.map(site=>({...site,usernameEnvelope:undefined,passwordEnvelope:undefined,hasUsername:Boolean(site.usernameEnvelope),hasPassword:Boolean(site.passwordEnvelope)})),payments,obligations,renewalItems,canReveal:owner(access),canPay:owner(access),canWrite:owner(access)||await hasPortalPermission(access,"legal","write")});}

export async function POST(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await permitted(true);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});try{const payload=await request.json() as Record<string,unknown>;const action=clean(payload.action,40);const db=getDb();const now=new Date().toISOString();
  if(action==="create-site"){const name=clean(payload.name,160),portalUrl=clean(payload.portalUrl,500),username=clean(payload.username,300),password=clean(payload.password,500);if(name.length<2||!/^https:\/\//i.test(portalUrl))return jsonNoStore({error:"اسم الموقع ورابط HTTPS مطلوبان"},{status:400});const[saved]=await db.insert(governmentSites).values({name,portalUrl,usernameEnvelope:username?encryptCredential(username):null,passwordEnvelope:password?encryptCredential(password):null,accountReference:clean(payload.accountReference,200)||null,notes:clean(payload.notes,2000)||null,createdBy:access.user.email,updatedBy:access.user.email,updatedAt:now}).returning();await auditPortalAction({actorEmail:access.user.email,action:"government-site-created",entityType:"government-site",entityId:saved.id,after:{...saved,usernameEnvelope:"[encrypted]",passwordEnvelope:"[encrypted]"},correlationId:requestCorrelationId(request)});return jsonNoStore({site:{...saved,usernameEnvelope:undefined,passwordEnvelope:undefined}},{status:201});}
  if(action==="reveal"){if(!owner(access))return jsonNoStore({error:"عرض بيانات الدخول متاح للمالك أو مشرف النظام فقط"},{status:403});const site=await db.query.governmentSites.findFirst({where:eq(governmentSites.id,id(payload.id))});if(!site)return jsonNoStore({error:"الموقع غير موجود"},{status:404});await auditPortalAction({actorEmail:access.user.email,action:"government-credential-revealed",entityType:"government-site",entityId:site.id,reason:"عرض يدوي مقيد",correlationId:requestCorrelationId(request)});return jsonNoStore({username:decryptCredential(site.usernameEnvelope),password:decryptCredential(site.passwordEnvelope)});}
  if(action==="create-payment"){const serviceName=clean(payload.serviceName,200),amountHalalas=Math.round(Number(payload.amount)*100),sadadNumber=clean(payload.sadadNumber,100),billerNumber=clean(payload.billerNumber,100),dueDate=clean(payload.dueDate,10);if(serviceName.length<2||!Number.isSafeInteger(amountHalalas)||amountHalalas<1||!sadadNumber||!billerNumber||!/^\d{4}-\d{2}-\d{2}$/.test(dueDate))return jsonNoStore({error:"بيانات طلب السداد غير مكتملة"},{status:400});const[saved]=await db.insert(governmentPaymentRequests).values({referenceCode:reference(),governmentSiteId:id(payload.governmentSiteId)||null,serviceName,amountHalalas,sadadNumber,billerNumber,dueDate,notes:clean(payload.notes,1000)||null,requestedBy:access.user.email,updatedAt:now}).returning();await auditPortalAction({actorEmail:access.user.email,action:"government-payment-requested",entityType:"government-payment",entityId:saved.id,after:saved});await emitPortalNotification({eventType:"government-payment-requested",title:"طلب سداد حكومي جديد",message:`${saved.serviceName} — ${(saved.amountHalalas/100).toFixed(2)} ر.س — رقم سداد ${saved.sadadNumber}`,severity:"warning",module:"finance",entityType:"government-payment",entityId:saved.id,actionView:"government",targetRole:"admin"}).catch(()=>undefined);return jsonNoStore({payment:saved},{status:201});}
  return jsonNoStore({error:"العملية غير مدعومة"},{status:400});
}catch(error){return jsonNoStore({error:error instanceof Error?error.message:"تعذر حفظ العملية"},{status:400});}}

export async function PATCH(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access||!owner(access))return jsonNoStore({error:"تأكيد السداد متاح للمالك أو مشرف النظام فقط"},{status:403});try{const payload=await request.json() as Record<string,unknown>;const paymentId=id(payload.id),now=new Date().toISOString(),db=getDb();const payment=await db.query.governmentPaymentRequests.findFirst({where:eq(governmentPaymentRequests.id,paymentId)});if(!payment||payment.status!=="pending")return jsonNoStore({error:"طلب السداد غير متاح للمعالجة"},{status:409});const result=await db.transaction(async tx=>{const[financial]=await tx.insert(financialRecords).values({referenceCode:`FIN-${payment.referenceCode}`,category:"government_fee",subCategory:"government_services",description:`رسوم حكومية — ${payment.serviceName} — مفوتر ${payment.billerNumber} — سداد ${payment.sadadNumber}`,amountHalalas:payment.amountHalalas,subtotalHalalas:payment.amountHalalas,vatHalalas:0,vatRateBps:0,dueDate:payment.dueDate,paymentMethod:"bank_transfer",notes:payment.notes,status:"paid",postingStatus:"unposted",updatedAt:now}).returning();const[updated]=await tx.update(governmentPaymentRequests).set({status:"paid",paidBy:access.user.email,paidAt:now,financialRecordId:financial.id,updatedAt:now}).where(and(eq(governmentPaymentRequests.id,payment.id),eq(governmentPaymentRequests.status,"pending"))).returning();if(!updated)throw new Error("تمت معالجة الطلب من مستخدم آخر");return{payment:updated,financial};});await auditPortalAction({actorEmail:access.user.email,action:"government-payment-paid",entityType:"government-payment",entityId:payment.id,before:payment,after:result,correlationId:requestCorrelationId(request)});await emitPortalNotification({eventType:"government-payment-paid",title:"تم سداد خدمة حكومية",message:`${payment.serviceName} — أُنشئ السجل المالي ${result.financial.referenceCode}`,severity:"success",module:"finance",entityType:"financial-record",entityId:result.financial.id,actionView:"finance",targetDepartment:"finance"}).catch(()=>undefined);return jsonNoStore(result);}catch(error){return jsonNoStore({error:error instanceof Error?error.message:"تعذر تأكيد السداد"},{status:400});}}
