import { sql } from "drizzle-orm";
import { boolean, check, index, integer, pgTable, serial, text, uniqueIndex } from "drizzle-orm/pg-core";

export const workforceRequests = pgTable(
  "workforce_requests",
  {
    id: serial("id").primaryKey(),
    trackingCode: text("tracking_code").notNull().unique(),
    fullName: text("full_name").notNull(),
    mobile: text("mobile").notNull(),
    email: text("email").notNull(),
    requestType: text("request_type").notNull().default("general"),
    companyName: text("company_name"),
    workSite: text("work_site"),
    requiredStartDate: text("required_start_date"),
    duration: text("duration"),
    requestedCount: integer("requested_count"),
    preferredContact: text("preferred_contact"),
    specialization: text("specialization").notNull(),
    details: text("details").notNull(),
    status: text("status").notNull().default("new"),
    source: text("source").notNull().default("public-website"),
    assignedTo: text("assigned_to"),
    clientId: integer("client_id"),
    opportunityId: integer("opportunity_id"),
    idempotencyKey: text("idempotency_key").unique(),
    privacyNoticeVersion: text("privacy_notice_version"),
    privacyAcknowledgedAt: text("privacy_acknowledged_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("workforce_requests_status_idx").on(table.status),
    index("workforce_requests_request_type_idx").on(table.requestType),
    index("workforce_requests_created_at_idx").on(table.createdAt),
  ],
);

export const workforceRequestAttachments = pgTable(
  "workforce_request_attachments",
  {
    id: serial("id").primaryKey(),
    requestId: integer("request_id").notNull().references(() => workforceRequests.id, { onDelete: "cascade" }),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull().unique(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workforce_request_attachments_request_idx").on(table.requestId),
    check("workforce_request_attachments_size_check", sql`${table.sizeBytes} > 0 and ${table.sizeBytes} <= 10485760`),
  ],
);

export const visitorConversations = pgTable(
  "visitor_conversations",
  {
    id: text("id").primaryKey(),
    trackingCode: text("tracking_code").notNull().unique(),
    publicTokenHash: text("public_token_hash").notNull().unique(),
    visitorName: text("visitor_name").notNull(),
    visitorEmail: text("visitor_email"),
    visitorMobile: text("visitor_mobile").notNull(),
    subject: text("subject").notNull(),
    status: text("status").notNull().default("waiting"),
    assignedTo: text("assigned_to"),
    relatedRequestId: integer("related_request_id"),
    sourceHash: text("source_hash"),
    lastVisitorMessageAt: text("last_visitor_message_at").notNull(),
    lastStaffMessageAt: text("last_staff_message_at"),
    lastAutoReplyKey: text("last_auto_reply_key"),
    tokenExpiresAt: text("token_expires_at"),
    firstResponseAt: text("first_response_at"),
    slaDueAt: text("sla_due_at"),
    closedAt: text("closed_at"),
    privacyNoticeVersion: text("privacy_notice_version"),
    privacyAcknowledgedAt: text("privacy_acknowledged_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("visitor_conversations_status_idx").on(table.status),
    index("visitor_conversations_updated_at_idx").on(table.updatedAt),
    index("visitor_conversations_assigned_to_idx").on(table.assignedTo),
    index("visitor_conversations_related_request_idx").on(table.relatedRequestId),
    index("visitor_conversations_source_hash_idx").on(table.sourceHash),
  ],
);

export const visitorMessages = pgTable(
  "visitor_messages",
  {
    id: serial("id").primaryKey(),
    conversationId: text("conversation_id").notNull(),
    senderType: text("sender_type").notNull(),
    senderName: text("sender_name").notNull(),
    senderEmail: text("sender_email"),
    body: text("body").notNull(),
    clientMessageId: text("client_message_id").unique(),
    readByVisitorAt: text("read_by_visitor_at"),
    readByStaffAt: text("read_by_staff_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("visitor_messages_conversation_created_idx").on(table.conversationId, table.createdAt),
    index("visitor_messages_sender_type_idx").on(table.senderType),
    index("visitor_messages_staff_read_idx").on(table.readByStaffAt),
  ],
);

export const portalSettings = pgTable(
  "portal_settings",
  {
    key: text("key").primaryKey(),
    valueJson: text("value_json").notNull(),
    updatedBy: text("updated_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("portal_settings_updated_at_idx").on(table.updatedAt)],
);

export const workforceRequestReplies = pgTable(
  "workforce_request_replies",
  {
    id: serial("id").primaryKey(),
    requestId: integer("request_id").notNull(),
    senderEmail: text("sender_email").notNull(),
    senderName: text("sender_name").notNull(),
    recipientEmail: text("recipient_email").notNull(),
    subject: text("subject").notNull(),
    body: text("body").notNull(),
    deliveryStatus: text("delivery_status").notNull().default("pending"),
    providerMessageId: text("provider_message_id"),
    failureReason: text("failure_reason"),
    sentAt: text("sent_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workforce_request_replies_request_id_idx").on(table.requestId),
    index("workforce_request_replies_status_idx").on(table.deliveryStatus),
    index("workforce_request_replies_created_at_idx").on(table.createdAt),
  ],
);

export const portalUsers = pgTable(
  "portal_users",
  {
    email: text("email").primaryKey(),
    displayName: text("display_name").notNull(),
    role: text("role").notNull().default("employee"),
    department: text("department").notNull().default("general"),
    status: text("status").notNull().default("pending"),
    requestedDepartment: text("requested_department"),
    requestedJobTitle: text("requested_job_title"),
    requestReason: text("request_reason"),
    requestSubmittedAt: text("request_submitted_at"),
    termsAcceptedAt: text("terms_accepted_at"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    suspendedAt: text("suspended_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    lastLoginAt: text("last_login_at"),
    lastActivityAt: text("last_activity_at"),
  },
  (table) => [
    index("portal_users_status_idx").on(table.status),
    index("portal_users_role_idx").on(table.role),
    index("portal_users_department_idx").on(table.department),
  ],
);

export const portalAuthCredentials = pgTable(
  "portal_auth_credentials",
  {
    identifier: text("identifier").primaryKey(),
    email: text("email").notNull().unique(),
    displayName: text("display_name").notNull(),
    passwordHash: text("password_hash").notNull(),
    mfaSecretEncrypted: text("mfa_secret_encrypted"),
    mfaEnabledAt: text("mfa_enabled_at"),
    mfaRecoveryHashesJson: text("mfa_recovery_hashes_json"),
    mfaRecoveryGeneratedAt: text("mfa_recovery_generated_at"),
    mfaLastVerifiedAt: text("mfa_last_verified_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("portal_auth_credentials_email_idx").on(table.email)],
);

export const portalMfaChallenges = pgTable(
  "portal_mfa_challenges",
  {
    id: text("id").primaryKey(),
    tokenHash: text("token_hash").notNull().unique(),
    identifier: text("identifier").notNull().references(() => portalAuthCredentials.identifier, { onDelete: "cascade" }),
    purpose: text("purpose").notNull(),
    pendingSecretEncrypted: text("pending_secret_encrypted"),
    pendingRecoveryHashesJson: text("pending_recovery_hashes_json"),
    pendingRecoveryCodesEncrypted: text("pending_recovery_codes_encrypted"),
    returnTo: text("return_to").notNull().default("/portal"),
    attempts: integer("attempts").notNull().default(0),
    expiresAt: text("expires_at").notNull(),
    usedAt: text("used_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("portal_mfa_challenges_identifier_idx").on(table.identifier),
    index("portal_mfa_challenges_expires_idx").on(table.expiresAt),
    check("portal_mfa_challenges_purpose_check", sql`${table.purpose} in ('verify', 'enroll')`),
    check("portal_mfa_challenges_attempts_check", sql`${table.attempts} >= 0 and ${table.attempts} <= 8`),
  ],
);

export const passwordResetTokens = pgTable(
  "password_reset_tokens",
  {
    tokenHash: text("token_hash").primaryKey(),
    identifier: text("identifier").notNull().references(() => portalAuthCredentials.identifier, { onDelete: "cascade" }),
    email: text("email").notNull(),
    expiresAt: text("expires_at").notNull(),
    usedAt: text("used_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("password_reset_tokens_identifier_idx").on(table.identifier), index("password_reset_tokens_expires_idx").on(table.expiresAt)],
);

export const portalSessions = pgTable(
  "portal_sessions",
  {
    id: text("id").primaryKey(),
    tokenHash: text("token_hash").notNull().unique(),
    userEmail: text("user_email").notNull().references(() => portalUsers.email, { onDelete: "cascade" }),
    status: text("status").notNull().default("active"),
    userAgentHash: text("user_agent_hash").notNull(),
    sourceHash: text("source_hash"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    lastActivityAt: text("last_activity_at").notNull(),
    idleExpiresAt: text("idle_expires_at").notNull(),
    absoluteExpiresAt: text("absolute_expires_at").notNull(),
    revokedAt: text("revoked_at"),
    revocationReason: text("revocation_reason"),
  },
  (table) => [
    index("portal_sessions_user_status_idx").on(table.userEmail, table.status),
    index("portal_sessions_idle_expires_idx").on(table.idleExpiresAt),
    check("portal_sessions_status_check", sql`${table.status} in ('active', 'revoked', 'expired')`),
  ],
);

export const employees = pgTable(
  "employees",
  {
    id: serial("id").primaryKey(),
    employeeNumber: text("employee_number").notNull().unique(),
    fullName: text("full_name").notNull(),
    jobTitle: text("job_title").notNull(),
    department: text("department").notNull(),
    mobile: text("mobile").notNull(),
    email: text("email"),
    nationalId: text("national_id"),
    nationality: text("nationality"),
    bankName: text("bank_name"),
    iban: text("iban"),
    baseSalaryHalalas: integer("base_salary_halalas").notNull().default(0),
    housingAllowanceHalalas: integer("housing_allowance_halalas").notNull().default(0),
    transportAllowanceHalalas: integer("transport_allowance_halalas").notNull().default(0),
    otherAllowanceHalalas: integer("other_allowance_halalas").notNull().default(0),
    annualLeaveDays: integer("annual_leave_days").notNull().default(21),
    leaveBalanceDays: integer("leave_balance_days").notNull().default(21),
    hireDate: text("hire_date").notNull(),
    probationEndDate: text("probation_end_date"),
    contractEndDate: text("contract_end_date"),
    terminationDate: text("termination_date"),
    terminationReason: text("termination_reason"),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("employees_status_idx").on(table.status),
    index("employees_department_idx").on(table.department),
  ],
);

export const employeeMovements = pgTable(
  "employee_movements",
  {
    id: serial("id").primaryKey(),
    employeeId: integer("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }),
    movementType: text("movement_type").notNull(),
    effectiveDate: text("effective_date").notNull(),
    amountHalalas: integer("amount_halalas").notNull().default(0),
    description: text("description").notNull(),
    status: text("status").notNull().default("approved"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("employee_movements_employee_date_idx").on(table.employeeId, table.effectiveDate),
    index("employee_movements_type_status_idx").on(table.movementType, table.status),
    check("employee_movements_type_check", sql`${table.movementType} in ('salary_adjustment','allowance','bonus','advance','deduction','leave','return_from_leave','suspension','termination','note')`),
    check("employee_movements_status_check", sql`${table.status} in ('draft','approved','cancelled')`),
    check("employee_movements_amount_check", sql`${table.amountHalalas} >= 0`),
  ],
);

export const payrollRuns = pgTable(
  "payroll_runs",
  {
    id: serial("id").primaryKey(),
    runNumber: text("run_number").notNull().unique(),
    periodMonth: text("period_month").notNull().unique(),
    paymentDate: text("payment_date").notNull(),
    status: text("status").notNull().default("draft"),
    totalGrossHalalas: integer("total_gross_halalas").notNull().default(0),
    totalDeductionsHalalas: integer("total_deductions_halalas").notNull().default(0),
    totalNetHalalas: integer("total_net_halalas").notNull().default(0),
    journalEntryId: integer("journal_entry_id"),
    paymentJournalEntryId: integer("payment_journal_entry_id"),
    createdBy: text("created_by").notNull(),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    paidBy: text("paid_by"),
    paidAt: text("paid_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("payroll_runs_status_payment_idx").on(table.status, table.paymentDate),
    check("payroll_runs_status_check", sql`${table.status} in ('draft','approved','processing','paid','cancelled')`),
    check("payroll_runs_totals_check", sql`${table.totalGrossHalalas} >= 0 and ${table.totalDeductionsHalalas} >= 0 and ${table.totalNetHalalas} >= 0`),
  ],
);

export const payrollItems = pgTable(
  "payroll_items",
  {
    id: serial("id").primaryKey(),
    payrollRunId: integer("payroll_run_id").notNull().references(() => payrollRuns.id, { onDelete: "cascade" }),
    employeeId: integer("employee_id").notNull().references(() => employees.id, { onDelete: "restrict" }),
    baseSalaryHalalas: integer("base_salary_halalas").notNull(),
    allowancesHalalas: integer("allowances_halalas").notNull().default(0),
    bonusHalalas: integer("bonus_halalas").notNull().default(0),
    deductionsHalalas: integer("deductions_halalas").notNull().default(0),
    netPayHalalas: integer("net_pay_halalas").notNull(),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("payroll_items_run_employee_idx").on(table.payrollRunId, table.employeeId),
    index("payroll_items_employee_idx").on(table.employeeId),
    check("payroll_items_amounts_check", sql`${table.baseSalaryHalalas} >= 0 and ${table.allowancesHalalas} >= 0 and ${table.bonusHalalas} >= 0 and ${table.deductionsHalalas} >= 0 and ${table.netPayHalalas} >= 0`),
  ],
);

export const financialRecords = pgTable(
  "financial_records",
  {
    id: serial("id").primaryKey(),
    referenceCode: text("reference_code").notNull().unique(),
    category: text("category").notNull(),
    description: text("description").notNull(),
    amountHalalas: integer("amount_halalas").notNull(),
    subtotalHalalas: integer("subtotal_halalas"),
    vatHalalas: integer("vat_halalas").notNull().default(0),
    vatRateBps: integer("vat_rate_bps").notNull().default(0),
    dueDate: text("due_date").notNull(),
    workerId: integer("worker_id"),
    contractId: integer("contract_id"),
    documentId: integer("document_id"),
    bankAccountId: integer("bank_account_id"),
    journalEntryId: integer("journal_entry_id"),
    postingStatus: text("posting_status").notNull().default("unposted"),
    postedAt: text("posted_at"),
    periodMonth: text("period_month"),
    subCategory: text("sub_category"),
    paymentMethod: text("payment_method"),
    notes: text("notes"),
    status: text("status").notNull().default("pending"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("financial_records_status_idx").on(table.status),
    index("financial_records_due_date_idx").on(table.dueDate),
    index("financial_records_category_idx").on(table.category),
    index("financial_records_worker_id_idx").on(table.workerId),
    index("financial_records_contract_id_idx").on(table.contractId),
    index("financial_records_document_id_idx").on(table.documentId),
    index("financial_records_bank_account_id_idx").on(table.bankAccountId),
    index("financial_records_period_month_idx").on(table.periodMonth),
    index("financial_records_posting_status_idx").on(table.postingStatus),
    check("financial_records_posting_status_check", sql`${table.postingStatus} in ('unposted','draft','posted','reversed','not_applicable')`),
  ],
);

export const contractPaymentSchedules = pgTable(
  "contract_payment_schedules",
  {
    id: serial("id").primaryKey(),
    contractId: integer("contract_id").notNull().references(() => workforceContracts.id, { onDelete: "cascade" }),
    installmentNumber: integer("installment_number").notNull(),
    title: text("title").notNull(),
    dueDate: text("due_date").notNull(),
    percentageBps: integer("percentage_bps").notNull(),
    amountHalalas: integer("amount_halalas").notNull(),
    status: text("status").notNull().default("scheduled"),
    referredBy: text("referred_by"),
    referredAt: text("referred_at"),
    invoiceDocumentId: integer("invoice_document_id").references(() => companyDocuments.id, { onDelete: "restrict" }),
    financialRecordId: integer("financial_record_id").references(() => financialRecords.id, { onDelete: "restrict" }),
    invoicedBy: text("invoiced_by"),
    invoicedAt: text("invoiced_at"),
    paidAt: text("paid_at"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("contract_payment_schedules_contract_installment_unique").on(table.contractId, table.installmentNumber),
    uniqueIndex("contract_payment_schedules_invoice_unique").on(table.invoiceDocumentId),
    index("contract_payment_schedules_due_status_idx").on(table.dueDate, table.status),
    check("contract_payment_schedules_status_check", sql`${table.status} in ('scheduled','due','referred','invoiced','paid','cancelled')`),
    check("contract_payment_schedules_amount_check", sql`${table.amountHalalas} > 0 and ${table.percentageBps} > 0 and ${table.percentageBps} <= 10000`),
  ],
);

export const legalRecords = pgTable(
  "legal_records",
  {
    id: serial("id").primaryKey(),
    referenceCode: text("reference_code").notNull().unique(),
    category: text("category").notNull(),
    title: text("title").notNull(),
    counterparty: text("counterparty").notNull(),
    expiryDate: text("expiry_date"),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("legal_records_status_idx").on(table.status),
    index("legal_records_expiry_date_idx").on(table.expiryDate),
  ],
);

export const complianceObligations = pgTable(
  "compliance_obligations",
  {
    id: serial("id").primaryKey(),
    obligationCode: text("obligation_code").notNull().unique(),
    title: text("title").notNull(),
    category: text("category").notNull(),
    authority: text("authority").notNull(),
    ownerDepartment: text("owner_department").notNull(),
    issueDate: text("issue_date"),
    expiryDate: text("expiry_date").notNull(),
    reminderDays: integer("reminder_days").notNull().default(30),
    riskLevel: text("risk_level").notNull().default("medium"),
    status: text("status").notNull().default("active"),
    documentId: integer("document_id"),
    legalRecordId: integer("legal_record_id").references(() => legalRecords.id, { onDelete: "set null" }),
    notes: text("notes"),
    createdBy: text("created_by").notNull(),
    reviewedBy: text("reviewed_by"),
    reviewedAt: text("reviewed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("compliance_obligations_expiry_status_idx").on(table.expiryDate, table.status),
    index("compliance_obligations_category_risk_idx").on(table.category, table.riskLevel),
    check("compliance_obligations_category_check", sql`${table.category} in ('license','certificate','insurance','labor','tax','municipal','contractual','data_protection','safety','other')`),
    check("compliance_obligations_risk_check", sql`${table.riskLevel} in ('low','medium','high','critical')`),
    check("compliance_obligations_status_check", sql`${table.status} in ('draft','active','under_review','renewal','expired','suspended','closed')`),
    check("compliance_obligations_reminder_check", sql`${table.reminderDays} between 1 and 365`),
  ],
);

export const complianceReviews = pgTable(
  "compliance_reviews",
  {
    id: serial("id").primaryKey(),
    obligationId: integer("obligation_id").notNull().references(() => complianceObligations.id, { onDelete: "cascade" }),
    reviewDate: text("review_date").notNull(),
    outcome: text("outcome").notNull(),
    notes: text("notes").notNull(),
    nextReviewDate: text("next_review_date"),
    reviewedBy: text("reviewed_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("compliance_reviews_obligation_date_idx").on(table.obligationId, table.reviewDate),
    check("compliance_reviews_outcome_check", sql`${table.outcome} in ('compliant','action_required','renewal_required','non_compliant','closed')`),
  ],
);

export const workers = pgTable(
  "workers",
  {
    id: serial("id").primaryKey(),
    workerNumber: text("worker_number").notNull().unique(),
    iqamaNumber: text("iqama_number").unique(),
    fullName: text("full_name").notNull(),
    nationality: text("nationality").notNull(),
    profession: text("profession").notNull(),
    mobile: text("mobile"),
    beneficiaryName: text("beneficiary_name"),
    clientSite: text("client_site").notNull(),
    assignmentStartDate: text("assignment_start_date"),
    iqamaExpiry: text("iqama_expiry"),
    status: text("status").notNull().default("available"),
    clientId: integer("client_id"),
    workOrderId: integer("work_order_id"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workers_status_idx").on(table.status),
    index("workers_profession_idx").on(table.profession),
    index("workers_beneficiary_name_idx").on(table.beneficiaryName),
    index("workers_iqama_expiry_idx").on(table.iqamaExpiry),
  ],
);

export const workerAttachments = pgTable(
  "worker_attachments",
  {
    id: serial("id").primaryKey(),
    workerId: integer("worker_id").notNull(),
    documentType: text("document_type").notNull(),
    requirementCode: text("requirement_code"),
    title: text("title").notNull(),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull().unique(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    validationStatus: text("validation_status").notNull().default("legacy"),
    validationDetails: text("validation_details"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("worker_attachments_worker_id_idx").on(table.workerId),
    index("worker_attachments_requirement_code_idx").on(table.requirementCode),
  ],
);

export const portalActivity = pgTable(
  "portal_activity",
  {
    id: serial("id").primaryKey(),
    actorEmail: text("actor_email").notNull(),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    beforeJson: text("before_json"),
    afterJson: text("after_json"),
    reason: text("reason"),
    correlationId: text("correlation_id"),
    source: text("source").notNull().default("portal"),
    ipHash: text("ip_hash"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("portal_activity_created_at_idx").on(table.createdAt)],
);

export const portalNotifications = pgTable(
  "portal_notifications",
  {
    id: serial("id").primaryKey(),
    eventType: text("event_type").notNull(),
    title: text("title").notNull(),
    message: text("message").notNull(),
    severity: text("severity").notNull().default("info"),
    module: text("module").notNull().default("overview"),
    entityType: text("entity_type"),
    entityId: text("entity_id"),
    targetRole: text("target_role"),
    targetDepartment: text("target_department"),
    targetEmail: text("target_email"),
    actionView: text("action_view"),
    dedupeKey: text("dedupe_key").unique(),
    source: text("source").notNull().default("event"),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("portal_notifications_status_created_idx").on(table.status, table.createdAt),
    index("portal_notifications_module_idx").on(table.module),
    index("portal_notifications_target_department_idx").on(table.targetDepartment),
    index("portal_notifications_target_email_idx").on(table.targetEmail),
  ],
);

export const portalNotificationReads = pgTable(
  "portal_notification_reads",
  {
    id: serial("id").primaryKey(),
    notificationId: integer("notification_id").notNull(),
    userEmail: text("user_email").notNull(),
    readAt: text("read_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    dismissedAt: text("dismissed_at"),
  },
  (table) => [
    uniqueIndex("portal_notification_reads_user_notification_unique").on(table.notificationId, table.userEmail),
    index("portal_notification_reads_user_idx").on(table.userEmail),
  ],
);

export const companyDocuments = pgTable(
  "company_documents",
  {
    id: serial("id").primaryKey(),
    referenceCode: text("reference_code").notNull().unique(),
    title: text("title").notNull(),
    category: text("category").notNull(),
    documentType: text("document_type"),
    counterparty: text("counterparty"),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull().unique(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    expiryDate: text("expiry_date"),
    source: text("source").notNull().default("uploaded"),
    status: text("status").notNull().default("active"),
    metadataJson: text("metadata_json"),
    validationStatus: text("validation_status").notNull().default("legacy"),
    validationDetails: text("validation_details"),
    retentionUntil: text("retention_until"),
    lockedUntil: text("locked_until"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("company_documents_category_idx").on(table.category),
    index("company_documents_expiry_date_idx").on(table.expiryDate),
    index("company_documents_created_at_idx").on(table.createdAt),
  ],
);

export const documentShareLinks = pgTable(
  "document_share_links",
  {
    id: text("id").primaryKey(),
    documentId: integer("document_id").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: text("expires_at").notNull(),
    revokedAt: text("revoked_at"),
    maxDownloads: integer("max_downloads").notNull().default(20),
    downloadCount: integer("download_count").notNull().default(0),
    lastAccessedAt: text("last_accessed_at"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("document_share_links_document_id_idx").on(table.documentId),
    index("document_share_links_expires_at_idx").on(table.expiresAt),
  ],
);

export const companyAssets = pgTable(
  "company_assets",
  {
    slot: text("slot").primaryKey(),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    validationStatus: text("validation_status").notNull().default("legacy"),
    validationDetails: text("validation_details"),
    uploadedBy: text("uploaded_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("company_assets_updated_at_idx").on(table.updatedAt)],
);

export const workforceContracts = pgTable(
  "workforce_contracts",
  {
    id: serial("id").primaryKey(),
    referenceCode: text("reference_code").notNull().unique(),
    documentId: integer("document_id").notNull().unique(),
    clientName: text("client_name").notNull(),
    clientCr: text("client_cr"),
    clientVat: text("client_vat"),
    title: text("title").notNull(),
    workSite: text("work_site").notNull(),
    issueDate: text("issue_date").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    amountHalalas: integer("amount_halalas").notNull().default(0),
    details: text("details").notNull(),
    status: text("status").notNull().default("draft"),
    versionNumber: integer("version_number").notNull().default(1),
    parentContractId: integer("parent_contract_id"),
    amendmentType: text("amendment_type"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    signedAt: text("signed_at"),
    effectiveAt: text("effective_at"),
    suspendedAt: text("suspended_at"),
    terminatedAt: text("terminated_at"),
    cancellationReason: text("cancellation_reason"),
    clientId: integer("client_id"),
    opportunityId: integer("opportunity_id"),
    quoteVersionId: integer("quote_version_id"),
    sourceRequestId: integer("source_request_id").references(() => workforceRequests.id, { onDelete: "set null" }),
    salesRepresentativeId: integer("sales_representative_id"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workforce_contracts_client_name_idx").on(table.clientName),
    index("workforce_contracts_status_idx").on(table.status),
    index("workforce_contracts_end_date_idx").on(table.endDate),
    index("workforce_contracts_parent_idx").on(table.parentContractId),
    index("workforce_contracts_source_request_idx").on(table.sourceRequestId),
    index("workforce_contracts_sales_representative_idx").on(table.salesRepresentativeId),
    check("workforce_contracts_status_check", sql`${table.status} in ('draft','internal_review','legal_review','approved','sent','signed','active','suspended','expired','terminated','cancelled','superseded')`),
  ],
);

export const contractClauses = pgTable(
  "contract_clauses",
  {
    id: serial("id").primaryKey(),
    contractId: integer("contract_id").notNull().references(() => workforceContracts.id, { onDelete: "cascade" }),
    clauseNumber: integer("clause_number").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    isOptional: boolean("is_optional").notNull().default(false),
    isIncluded: boolean("is_included").notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("contract_clauses_number_unique").on(table.contractId, table.clauseNumber),
    index("contract_clauses_contract_idx").on(table.contractId),
  ],
);

export const contractProfessions = pgTable(
  "contract_professions",
  {
    id: serial("id").primaryKey(),
    contractId: integer("contract_id").notNull(),
    profession: text("profession").notNull(),
    requiredCount: integer("required_count").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("contract_professions_contract_profession_unique").on(table.contractId, table.profession),
    index("contract_professions_contract_id_idx").on(table.contractId),
    index("contract_professions_profession_idx").on(table.profession),
  ],
);

export const contractWorkerAssignments = pgTable(
  "contract_worker_assignments",
  {
    id: serial("id").primaryKey(),
    contractId: integer("contract_id").notNull(),
    contractProfessionId: integer("contract_profession_id").notNull(),
    workerId: integer("worker_id").notNull(),
    status: text("status").notNull().default("active"),
    assignedBy: text("assigned_by").notNull(),
    assignedAt: text("assigned_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    releasedAt: text("released_at"),
  },
  (table) => [
    uniqueIndex("contract_worker_assignments_contract_worker_unique").on(table.contractId, table.workerId),
    index("contract_worker_assignments_contract_id_idx").on(table.contractId),
    index("contract_worker_assignments_profession_id_idx").on(table.contractProfessionId),
    index("contract_worker_assignments_worker_id_idx").on(table.workerId),
    index("contract_worker_assignments_status_idx").on(table.status),
  ],
);

export const clients = pgTable(
  "clients",
  {
    id: serial("id").primaryKey(),
    clientCode: text("client_code").notNull().unique(),
    legalName: text("legal_name").notNull(),
    tradeName: text("trade_name"),
    commercialRegistration: text("commercial_registration").unique(),
    vatNumber: text("vat_number"),
    sector: text("sector"),
    city: text("city").notNull().default("مكة المكرمة"),
    address: text("address"),
    status: text("status").notNull().default("prospect"),
    ownerEmail: text("owner_email"),
    sourceRequestId: integer("source_request_id").references(() => workforceRequests.id, { onDelete: "set null" }),
    salesRepresentativeId: integer("sales_representative_id"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("clients_legal_name_idx").on(table.legalName),
    index("clients_status_idx").on(table.status),
    index("clients_owner_idx").on(table.ownerEmail),
    index("clients_source_request_idx").on(table.sourceRequestId),
    index("clients_sales_representative_idx").on(table.salesRepresentativeId),
    check("clients_status_check", sql`${table.status} in ('prospect', 'active', 'inactive', 'blocked')`),
  ],
);

export const salesRepresentatives = pgTable(
  "sales_representatives",
  {
    id: serial("id").primaryKey(),
    representativeCode: text("representative_code").notNull().unique(),
    fullName: text("full_name").notNull(),
    mobile: text("mobile").notNull(),
    email: text("email"),
    nationalId: text("national_id").unique(),
    region: text("region").notNull().default("مكة المكرمة"),
    commissionBps: integer("commission_bps").notNull().default(0),
    status: text("status").notNull().default("active"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("sales_representatives_status_idx").on(table.status),
    index("sales_representatives_name_idx").on(table.fullName),
    check("sales_representatives_commission_check", sql`${table.commissionBps} between 0 and 10000`),
    check("sales_representatives_status_check", sql`${table.status} in ('active','inactive','suspended')`),
  ],
);

export const suppliers = pgTable(
  "suppliers",
  {
    id: serial("id").primaryKey(),
    supplierCode: text("supplier_code").notNull().unique(),
    legalName: text("legal_name").notNull(),
    commercialRegistration: text("commercial_registration"),
    vatNumber: text("vat_number"),
    contactName: text("contact_name"),
    mobile: text("mobile"),
    email: text("email"),
    address: text("address"),
    status: text("status").notNull().default("active"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("suppliers_name_idx").on(table.legalName),
    index("suppliers_status_idx").on(table.status),
    check("suppliers_status_check", sql`${table.status} in ('active','inactive','blocked')`),
  ],
);

export const purchaseInvoices = pgTable(
  "purchase_invoices",
  {
    id: serial("id").primaryKey(),
    referenceCode: text("reference_code").notNull().unique(),
    supplierInvoiceNumber: text("supplier_invoice_number").notNull(),
    expenseType: text("expense_type").notNull().default("supplier_invoice"),
    supplierId: integer("supplier_id").references(() => suppliers.id, { onDelete: "restrict" }),
    employeeId: integer("employee_id").references(() => employees.id, { onDelete: "restrict" }),
    contractId: integer("contract_id").references(() => workforceContracts.id, { onDelete: "restrict" }),
    documentId: integer("document_id").notNull().references(() => companyDocuments.id, { onDelete: "restrict" }),
    invoiceDate: text("invoice_date").notNull(),
    dueDate: text("due_date").notNull(),
    description: text("description").notNull(),
    subtotalHalalas: integer("subtotal_halalas").notNull(),
    vatHalalas: integer("vat_halalas").notNull().default(0),
    totalHalalas: integer("total_halalas").notNull(),
    status: text("status").notNull().default("draft"),
    journalEntryId: integer("journal_entry_id").references(() => journalEntries.id, { onDelete: "restrict" }),
    paymentJournalEntryId: integer("payment_journal_entry_id").references(() => journalEntries.id, { onDelete: "restrict" }),
    postingStatus: text("posting_status").notNull().default("unposted"),
    createdBy: text("created_by").notNull(),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    paidBy: text("paid_by"),
    paidAt: text("paid_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("purchase_invoice_supplier_number_unique").on(table.supplierId, table.supplierInvoiceNumber),
    index("purchase_invoices_due_status_idx").on(table.dueDate, table.status),
    index("purchase_invoices_supplier_idx").on(table.supplierId),
    index("purchase_invoices_employee_idx").on(table.employeeId),
    check("purchase_invoices_type_check", sql`${table.expenseType} in ('supplier_invoice','employee_expense')`),
    check("purchase_invoices_status_check", sql`${table.status} in ('draft','approved','posted','payment_pending','paid','cancelled')`),
    check("purchase_invoices_posting_check", sql`${table.postingStatus} in ('unposted','draft','posted','reversed')`),
    check("purchase_invoices_amount_check", sql`${table.subtotalHalalas} >= 0 and ${table.vatHalalas} >= 0 and ${table.totalHalalas} = ${table.subtotalHalalas} + ${table.vatHalalas}`),
  ],
);

export const clientContacts = pgTable(
  "client_contacts",
  {
    id: serial("id").primaryKey(),
    clientId: integer("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
    fullName: text("full_name").notNull(),
    jobTitle: text("job_title"),
    mobile: text("mobile"),
    email: text("email"),
    preferredChannel: text("preferred_channel").notNull().default("either"),
    isPrimary: boolean("is_primary").notNull().default(false),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("client_contacts_client_idx").on(table.clientId),
    index("client_contacts_email_idx").on(table.email),
    check("client_contacts_channel_check", sql`${table.preferredChannel} in ('phone', 'email', 'either')`),
  ],
);

export const salesOpportunities = pgTable(
  "sales_opportunities",
  {
    id: serial("id").primaryKey(),
    opportunityCode: text("opportunity_code").notNull().unique(),
    clientId: integer("client_id").references(() => clients.id, { onDelete: "set null" }),
    contactId: integer("contact_id").references(() => clientContacts.id, { onDelete: "set null" }),
    sourceRequestId: integer("source_request_id").references(() => workforceRequests.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    stage: text("stage").notNull().default("new"),
    expectedValueHalalas: integer("expected_value_halalas").notNull().default(0),
    expectedCloseDate: text("expected_close_date"),
    probability: integer("probability").notNull().default(10),
    ownerEmail: text("owner_email").notNull(),
    lossReason: text("loss_reason"),
    notes: text("notes"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("sales_opportunities_client_idx").on(table.clientId),
    index("sales_opportunities_stage_idx").on(table.stage),
    index("sales_opportunities_owner_idx").on(table.ownerEmail),
    uniqueIndex("sales_opportunities_source_request_unique").on(table.sourceRequestId),
    check("sales_opportunities_stage_check", sql`${table.stage} in ('new', 'qualified', 'proposal', 'negotiation', 'won', 'lost')`),
    check("sales_opportunities_probability_check", sql`${table.probability} between 0 and 100`),
  ],
);

export const quoteVersions = pgTable(
  "quote_versions",
  {
    id: serial("id").primaryKey(),
    quoteCode: text("quote_code").notNull(),
    opportunityId: integer("opportunity_id").notNull().references(() => salesOpportunities.id, { onDelete: "cascade" }),
    versionNumber: integer("version_number").notNull().default(1),
    status: text("status").notNull().default("draft"),
    issueDate: text("issue_date").notNull(),
    validUntil: text("valid_until").notNull(),
    subtotalHalalas: integer("subtotal_halalas").notNull().default(0),
    discountHalalas: integer("discount_halalas").notNull().default(0),
    totalHalalas: integer("total_halalas").notNull().default(0),
    assumptions: text("assumptions"),
    terms: text("terms"),
    approvalReason: text("approval_reason"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    acceptedAt: text("accepted_at"),
    clientDecisionBy: text("client_decision_by"),
    clientDecisionReason: text("client_decision_reason"),
    clientDecisionAt: text("client_decision_at"),
    documentId: integer("document_id").references(() => companyDocuments.id, { onDelete: "set null" }),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    recordVersion: integer("record_version").notNull().default(1),
  },
  (table) => [
    uniqueIndex("quote_versions_code_version_unique").on(table.quoteCode, table.versionNumber),
    index("quote_versions_opportunity_idx").on(table.opportunityId),
    index("quote_versions_status_idx").on(table.status),
    index("quote_versions_valid_until_idx").on(table.validUntil),
    check("quote_versions_status_check", sql`${table.status} in ('draft', 'pending_approval', 'approved', 'sent', 'accepted', 'rejected', 'expired', 'superseded')`),
  ],
);

export const quoteItems = pgTable(
  "quote_items",
  {
    id: serial("id").primaryKey(),
    quoteVersionId: integer("quote_version_id").notNull().references(() => quoteVersions.id, { onDelete: "cascade" }),
    profession: text("profession").notNull(),
    quantity: integer("quantity").notNull(),
    durationMonths: integer("duration_months").notNull().default(1),
    unitPriceHalalas: integer("unit_price_halalas").notNull(),
    lineTotalHalalas: integer("line_total_halalas").notNull(),
    notes: text("notes"),
    sortOrder: integer("sort_order").notNull().default(0),
  },
  (table) => [
    index("quote_items_quote_idx").on(table.quoteVersionId),
    check("quote_items_quantity_check", sql`${table.quantity} > 0`),
    check("quote_items_duration_check", sql`${table.durationMonths} > 0`),
  ],
);

export const workOrders = pgTable(
  "work_orders",
  {
    id: serial("id").primaryKey(),
    workOrderCode: text("work_order_code").notNull().unique(),
    clientId: integer("client_id").notNull().references(() => clients.id, { onDelete: "restrict" }),
    contractId: integer("contract_id").references(() => workforceContracts.id, { onDelete: "set null" }),
    quoteVersionId: integer("quote_version_id").references(() => quoteVersions.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    workSite: text("work_site").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date"),
    supervisorEmail: text("supervisor_email"),
    status: text("status").notNull().default("planned"),
    notes: text("notes"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("work_orders_client_idx").on(table.clientId),
    index("work_orders_contract_idx").on(table.contractId),
    index("work_orders_status_idx").on(table.status),
    index("work_orders_dates_idx").on(table.startDate, table.endDate),
    check("work_orders_status_check", sql`${table.status} in ('planned', 'staffing', 'active', 'paused', 'completed', 'cancelled')`),
  ],
);

export const workOrderRequirements = pgTable(
  "work_order_requirements",
  {
    id: serial("id").primaryKey(),
    workOrderId: integer("work_order_id").notNull().references(() => workOrders.id, { onDelete: "cascade" }),
    profession: text("profession").notNull(),
    requiredCount: integer("required_count").notNull(),
    filledCount: integer("filled_count").notNull().default(0),
    shiftName: text("shift_name"),
    startTime: text("start_time"),
    endTime: text("end_time"),
  },
  (table) => [
    uniqueIndex("work_order_requirements_unique").on(table.workOrderId, table.profession, table.shiftName),
    index("work_order_requirements_order_idx").on(table.workOrderId),
    check("work_order_requirements_count_check", sql`${table.requiredCount} > 0 and ${table.filledCount} >= 0`),
  ],
);

export const timesheets = pgTable(
  "timesheets",
  {
    id: serial("id").primaryKey(),
    timesheetCode: text("timesheet_code").notNull().unique(),
    workOrderId: integer("work_order_id").notNull().references(() => workOrders.id, { onDelete: "restrict" }),
    clientId: integer("client_id").notNull().references(() => clients.id, { onDelete: "restrict" }),
    periodStart: text("period_start").notNull(),
    periodEnd: text("period_end").notNull(),
    status: text("status").notNull().default("draft"),
    submittedBy: text("submitted_by"),
    submittedAt: text("submitted_at"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    rejectionReason: text("rejection_reason"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    uniqueIndex("timesheets_order_period_unique").on(table.workOrderId, table.periodStart, table.periodEnd),
    index("timesheets_client_idx").on(table.clientId),
    index("timesheets_status_idx").on(table.status),
    check("timesheets_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'rejected', 'invoiced')`),
  ],
);

export const timeEntries = pgTable(
  "time_entries",
  {
    id: serial("id").primaryKey(),
    timesheetId: integer("timesheet_id").notNull().references(() => timesheets.id, { onDelete: "cascade" }),
    workerId: integer("worker_id").notNull().references(() => workers.id, { onDelete: "restrict" }),
    workDate: text("work_date").notNull(),
    regularMinutes: integer("regular_minutes").notNull().default(0),
    overtimeMinutes: integer("overtime_minutes").notNull().default(0),
    attendanceStatus: text("attendance_status").notNull().default("present"),
    notes: text("notes"),
  },
  (table) => [
    uniqueIndex("time_entries_sheet_worker_date_unique").on(table.timesheetId, table.workerId, table.workDate),
    index("time_entries_worker_idx").on(table.workerId),
    check("time_entries_minutes_check", sql`${table.regularMinutes} >= 0 and ${table.overtimeMinutes} >= 0`),
    check("time_entries_attendance_check", sql`${table.attendanceStatus} in ('present', 'absent', 'leave', 'sick', 'holiday')`),
  ],
);

export const workflowApprovals = pgTable(
  "workflow_approvals",
  {
    id: serial("id").primaryKey(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    step: text("step").notNull(),
    status: text("status").notNull().default("pending"),
    requestedBy: text("requested_by").notNull(),
    assignedRole: text("assigned_role"),
    assignedEmail: text("assigned_email"),
    decisionBy: text("decision_by"),
    decisionReason: text("decision_reason"),
    decidedAt: text("decided_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workflow_approvals_entity_idx").on(table.entityType, table.entityId),
    index("workflow_approvals_status_idx").on(table.status),
    check("workflow_approvals_status_check", sql`${table.status} in ('pending', 'approved', 'rejected', 'cancelled')`),
  ],
);

export const workflowStatusHistory = pgTable(
  "workflow_status_history",
  {
    id: serial("id").primaryKey(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    fromStatus: text("from_status"),
    toStatus: text("to_status").notNull(),
    reason: text("reason"),
    actorEmail: text("actor_email").notNull(),
    correlationId: text("correlation_id").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("workflow_status_history_entity_idx").on(table.entityType, table.entityId, table.createdAt),
    index("workflow_status_history_correlation_idx").on(table.correlationId),
  ],
);

export const integrationOutbox = pgTable(
  "integration_outbox",
  {
    id: text("id").primaryKey(),
    eventType: text("event_type").notNull(),
    aggregateType: text("aggregate_type").notNull(),
    aggregateId: text("aggregate_id").notNull(),
    payloadJson: text("payload_json").notNull(),
    status: text("status").notNull().default("pending"),
    attempts: integer("attempts").notNull().default(0),
    availableAt: text("available_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    processedAt: text("processed_at"),
    lastError: text("last_error"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("integration_outbox_status_available_idx").on(table.status, table.availableAt),
    index("integration_outbox_aggregate_idx").on(table.aggregateType, table.aggregateId),
    check("integration_outbox_status_check", sql`${table.status} in ('pending', 'processing', 'processed', 'failed')`),
  ],
);

export const publicRateLimits = pgTable(
  "public_rate_limits",
  {
    key: text("key").primaryKey(),
    windowStartedAt: text("window_started_at").notNull(),
    requestCount: integer("request_count").notNull().default(0),
    blockedUntil: text("blocked_until"),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("public_rate_limits_updated_idx").on(table.updatedAt)],
);

export const operationRequests = pgTable(
  "operation_requests",
  {
    key: text("key").primaryKey(),
    actorEmail: text("actor_email").notNull(),
    action: text("action").notNull(),
    status: text("status").notNull().default("processing"),
    responseJson: text("response_json"),
    errorMessage: text("error_message"),
    expiresAt: text("expires_at").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("operation_requests_actor_idx").on(table.actorEmail, table.createdAt),
    index("operation_requests_expiry_idx").on(table.expiresAt),
    check("operation_requests_status_check", sql`${table.status} in ('processing', 'completed', 'failed')`),
  ],
);

export const clientPortalUsers = pgTable(
  "client_portal_users",
  {
    email: text("email").primaryKey(),
    clientId: integer("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    status: text("status").notNull().default("pending"),
    canApproveQuotes: boolean("can_approve_quotes").notNull().default(false),
    canApproveTimesheets: boolean("can_approve_timesheets").notNull().default(false),
    invitedBy: text("invited_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    lastLoginAt: text("last_login_at"),
  },
  (table) => [
    index("client_portal_users_client_idx").on(table.clientId),
    index("client_portal_users_status_idx").on(table.status),
    check("client_portal_users_status_check", sql`${table.status} in ('pending', 'active', 'suspended')`),
  ],
);

export const workerPortalUsers = pgTable(
  "worker_portal_users",
  {
    email: text("email").primaryKey(),
    workerId: integer("worker_id").notNull().references(() => workers.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    status: text("status").notNull().default("pending"),
    invitedBy: text("invited_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    lastLoginAt: text("last_login_at"),
  },
  (table) => [
    uniqueIndex("worker_portal_users_worker_unique").on(table.workerId),
    index("worker_portal_users_status_idx").on(table.status),
    check("worker_portal_users_status_check", sql`${table.status} in ('pending', 'active', 'suspended')`),
  ],
);

export const portalUserPermissions = pgTable(
  "portal_user_permissions",
  {
    id: serial("id").primaryKey(),
    userEmail: text("user_email").notNull().references(() => portalUsers.email, { onDelete: "cascade" }),
    resource: text("resource").notNull(),
    action: text("action").notNull(),
    scope: text("scope").notNull().default("department"),
    allowed: boolean("allowed").notNull().default(true),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("portal_user_permissions_unique").on(table.userEmail, table.resource, table.action, table.scope),
    index("portal_user_permissions_user_idx").on(table.userEmail),
    check("portal_user_permissions_scope_check", sql`${table.scope} in ('own', 'department', 'all')`),
  ],
);

export const portalRoles = pgTable(
  "portal_roles",
  {
    roleKey: text("role_key").primaryKey(),
    labelAr: text("label_ar").notNull(),
    description: text("description"),
    permissionsJson: text("permissions_json").notNull().default("[]"),
    protected: boolean("protected").notNull().default(false),
    active: boolean("active").notNull().default(true),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("portal_roles_active_idx").on(table.active),
    check("portal_roles_key_check", sql`${table.roleKey} ~ '^[a-z][a-z0-9_]{2,63}$'`),
  ],
);

export const dataSubjectRequests = pgTable(
  "data_subject_requests",
  {
    id: serial("id").primaryKey(),
    trackingCode: text("tracking_code").notNull().unique(),
    requestType: text("request_type").notNull(),
    fullName: text("full_name").notNull(),
    email: text("email").notNull(),
    mobile: text("mobile"),
    details: text("details"),
    status: text("status").notNull().default("received"),
    assignedTo: text("assigned_to"),
    dueAt: text("due_at").notNull(),
    completedAt: text("completed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("data_subject_requests_status_due_idx").on(table.status, table.dueAt),
    check("data_subject_requests_type_check", sql`${table.requestType} in ('access', 'correction', 'deletion', 'withdraw_consent', 'complaint')`),
    check("data_subject_requests_status_check", sql`${table.status} in ('received', 'verifying', 'processing', 'completed', 'rejected')`),
  ],
);

export const capacityPlans = pgTable(
  "capacity_plans",
  {
    id: serial("id").primaryKey(),
    planCode: text("plan_code").notNull().unique(),
    seasonName: text("season_name").notNull(),
    location: text("location").notNull(),
    profession: text("profession").notNull(),
    requiredCount: integer("required_count").notNull(),
    availableCount: integer("available_count").notNull().default(0),
    reservedCount: integer("reserved_count").notNull().default(0),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    status: text("status").notNull().default("planning"),
    ownerEmail: text("owner_email").notNull(),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("capacity_plans_season_idx").on(table.seasonName),
    index("capacity_plans_dates_idx").on(table.startDate, table.endDate),
    check("capacity_plans_counts_check", sql`${table.requiredCount} > 0 and ${table.availableCount} >= 0 and ${table.reservedCount} >= 0`),
    check("capacity_plans_status_check", sql`${table.status} in ('planning', 'approved', 'active', 'completed', 'cancelled')`),
  ],
);

// Enterprise accounting foundation. Source documents remain operational records;
// only posted journal lines are allowed to change ledger balances.
export const chartOfAccounts = pgTable(
  "chart_of_accounts",
  {
    id: serial("id").primaryKey(),
    code: text("code").notNull().unique(),
    nameAr: text("name_ar").notNull(),
    accountType: text("account_type").notNull(),
    normalBalance: text("normal_balance").notNull(),
    parentId: integer("parent_id"),
    isPosting: boolean("is_posting").notNull().default(true),
    isSystem: boolean("is_system").notNull().default(false),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("chart_of_accounts_parent_idx").on(table.parentId),
    index("chart_of_accounts_type_status_idx").on(table.accountType, table.status),
    check("chart_of_accounts_type_check", sql`${table.accountType} in ('asset','liability','equity','revenue','expense')`),
    check("chart_of_accounts_balance_check", sql`${table.normalBalance} in ('debit','credit')`),
    check("chart_of_accounts_status_check", sql`${table.status} in ('active','inactive')`),
  ],
);

export const fiscalPeriods = pgTable(
  "fiscal_periods",
  {
    id: serial("id").primaryKey(),
    periodCode: text("period_code").notNull().unique(),
    nameAr: text("name_ar").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    status: text("status").notNull().default("open"),
    closedBy: text("closed_by"),
    closedAt: text("closed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("fiscal_periods_dates_idx").on(table.startDate, table.endDate),
    check("fiscal_periods_status_check", sql`${table.status} in ('future','open','soft_closed','closed')`),
    check("fiscal_periods_date_check", sql`${table.endDate} >= ${table.startDate}`),
  ],
);

export const costCenters = pgTable(
  "cost_centers",
  {
    id: serial("id").primaryKey(),
    code: text("code").notNull().unique(),
    nameAr: text("name_ar").notNull(),
    centerType: text("center_type").notNull().default("contract"),
    contractId: integer("contract_id").references(() => workforceContracts.id, { onDelete: "restrict" }),
    status: text("status").notNull().default("active"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("cost_centers_type_status_idx").on(table.centerType, table.status),
    uniqueIndex("cost_centers_contract_unique").on(table.contractId),
    check("cost_centers_type_check", sql`${table.centerType} in ('contract','department','project','administrative')`),
    check("cost_centers_status_check", sql`${table.status} in ('active','inactive','closed')`),
  ],
);

export const journalEntries = pgTable(
  "journal_entries",
  {
    id: serial("id").primaryKey(),
    entryNumber: text("entry_number").notNull().unique(),
    entryDate: text("entry_date").notNull(),
    fiscalPeriodId: integer("fiscal_period_id").notNull().references(() => fiscalPeriods.id, { onDelete: "restrict" }),
    description: text("description").notNull(),
    sourceType: text("source_type").notNull(),
    sourceId: text("source_id"),
    reversalOfId: integer("reversal_of_id"),
    status: text("status").notNull().default("draft"),
    createdBy: text("created_by").notNull(),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    postedBy: text("posted_by"),
    postedAt: text("posted_at"),
    voidReason: text("void_reason"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("journal_entries_period_status_idx").on(table.fiscalPeriodId, table.status),
    index("journal_entries_source_idx").on(table.sourceType, table.sourceId),
    index("journal_entries_date_idx").on(table.entryDate),
    check("journal_entries_status_check", sql`${table.status} in ('draft','approved','posted','reversed','void')`),
  ],
);

export const journalLines = pgTable(
  "journal_lines",
  {
    id: serial("id").primaryKey(),
    journalEntryId: integer("journal_entry_id").notNull().references(() => journalEntries.id, { onDelete: "cascade" }),
    lineNumber: integer("line_number").notNull(),
    accountId: integer("account_id").notNull().references(() => chartOfAccounts.id, { onDelete: "restrict" }),
    bankAccountId: integer("bank_account_id"),
    description: text("description"),
    debitHalalas: integer("debit_halalas").notNull().default(0),
    creditHalalas: integer("credit_halalas").notNull().default(0),
    clientId: integer("client_id").references(() => clients.id, { onDelete: "restrict" }),
    contractId: integer("contract_id").references(() => workforceContracts.id, { onDelete: "restrict" }),
    workerId: integer("worker_id").references(() => workers.id, { onDelete: "restrict" }),
    employeeId: integer("employee_id").references(() => employees.id, { onDelete: "restrict" }),
    costCenterCode: text("cost_center_code"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("journal_lines_entry_line_unique").on(table.journalEntryId, table.lineNumber),
    index("journal_lines_account_idx").on(table.accountId),
    index("journal_lines_bank_account_idx").on(table.bankAccountId),
    index("journal_lines_contract_idx").on(table.contractId),
    check("journal_lines_amount_check", sql`${table.debitHalalas} >= 0 and ${table.creditHalalas} >= 0 and ((${table.debitHalalas} > 0 and ${table.creditHalalas} = 0) or (${table.creditHalalas} > 0 and ${table.debitHalalas} = 0))`),
  ],
);

export const bankAccounts = pgTable(
  "bank_accounts",
  {
    id: serial("id").primaryKey(),
    accountCode: text("account_code").notNull().unique(),
    bankName: text("bank_name").notNull(),
    accountName: text("account_name").notNull(),
    iban: text("iban").notNull().unique(),
    currency: text("currency").notNull().default("SAR"),
    ledgerAccountId: integer("ledger_account_id").notNull().references(() => chartOfAccounts.id, { onDelete: "restrict" }),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("bank_accounts_status_idx").on(table.status),
    check("bank_accounts_status_check", sql`${table.status} in ('active','inactive','closed')`),
  ],
);

export const bankReconciliations = pgTable(
  "bank_reconciliations",
  {
    id: serial("id").primaryKey(),
    reconciliationNumber: text("reconciliation_number").notNull().unique(),
    bankAccountId: integer("bank_account_id").notNull().references(() => bankAccounts.id, { onDelete: "restrict" }),
    statementDate: text("statement_date").notNull(),
    statementBalanceHalalas: integer("statement_balance_halalas").notNull(),
    ledgerBalanceHalalas: integer("ledger_balance_halalas").notNull(),
    outstandingDepositsHalalas: integer("outstanding_deposits_halalas").notNull().default(0),
    outstandingPaymentsHalalas: integer("outstanding_payments_halalas").notNull().default(0),
    differenceHalalas: integer("difference_halalas").notNull(),
    status: text("status").notNull().default("draft"),
    notes: text("notes"),
    createdBy: text("created_by").notNull(),
    reviewedBy: text("reviewed_by"),
    reviewedAt: text("reviewed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("bank_reconciliations_bank_date_unique").on(table.bankAccountId, table.statementDate),
    index("bank_reconciliations_status_date_idx").on(table.status, table.statementDate),
    check("bank_reconciliations_status_check", sql`${table.status} in ('draft','reviewed','closed','cancelled')`),
    check("bank_reconciliations_outstanding_check", sql`${table.outstandingDepositsHalalas} >= 0 and ${table.outstandingPaymentsHalalas} >= 0`),
  ],
);

export const accountingPostingRules = pgTable(
  "accounting_posting_rules",
  {
    id: serial("id").primaryKey(),
    eventType: text("event_type").notNull().unique(),
    debitAccountId: integer("debit_account_id").notNull().references(() => chartOfAccounts.id, { onDelete: "restrict" }),
    creditAccountId: integer("credit_account_id").notNull().references(() => chartOfAccounts.id, { onDelete: "restrict" }),
    taxAccountId: integer("tax_account_id").references(() => chartOfAccounts.id, { onDelete: "restrict" }),
    active: boolean("active").notNull().default(true),
    updatedBy: text("updated_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("accounting_posting_rules_active_idx").on(table.active)],
);

// Multi-business and nationwide operating model. These records are operational,
// not marketing claims: publication remains an explicit reviewed decision.
export const businessLines = pgTable(
  "business_lines",
  {
    id: serial("id").primaryKey(),
    code: text("code").notNull().unique(),
    nameAr: text("name_ar").notNull(),
    description: text("description").notNull(),
    status: text("status").notNull().default("active"),
    publicStatus: text("public_status").notNull().default("draft"),
    complianceApprovedBy: text("compliance_approved_by"),
    complianceApprovedAt: text("compliance_approved_at"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("business_lines_status_idx").on(table.status, table.publicStatus),
    check("business_lines_status_check", sql`${table.status} in ('active','inactive')`),
    check("business_lines_public_status_check", sql`${table.publicStatus} in ('draft','review','published','blocked')`),
  ],
);

export const serviceRegions = pgTable(
  "service_regions",
  {
    id: serial("id").primaryKey(),
    code: text("code").notNull().unique(),
    nameAr: text("name_ar").notNull().unique(),
    nameEn: text("name_en").notNull(),
    status: text("status").notNull().default("active"),
    sortOrder: integer("sort_order").notNull().default(0),
  },
  (table) => [index("service_regions_status_sort_idx").on(table.status, table.sortOrder)],
);

export const serviceCities = pgTable(
  "service_cities",
  {
    id: serial("id").primaryKey(),
    regionId: integer("region_id").notNull().references(() => serviceRegions.id, { onDelete: "restrict" }),
    code: text("code").notNull().unique(),
    nameAr: text("name_ar").notNull(),
    nameEn: text("name_en").notNull(),
    latitudeE6: integer("latitude_e6"),
    longitudeE6: integer("longitude_e6"),
    status: text("status").notNull().default("active"),
    seoStatus: text("seo_status").notNull().default("not_ready"),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("service_cities_region_name_unique").on(table.regionId, table.nameAr),
    index("service_cities_region_status_idx").on(table.regionId, table.status),
    check("service_cities_seo_status_check", sql`${table.seoStatus} in ('not_ready','draft','review','publishable')`),
  ],
);

export const serviceCoverage = pgTable(
  "service_coverage",
  {
    id: serial("id").primaryKey(),
    cityId: integer("city_id").notNull().references(() => serviceCities.id, { onDelete: "restrict" }),
    businessLineId: integer("business_line_id").notNull().references(() => businessLines.id, { onDelete: "restrict" }),
    availability: text("availability").notNull().default("conditional"),
    mobilizationDays: integer("mobilization_days"),
    capacityLevel: text("capacity_level").notNull().default("review_required"),
    ownerEmail: text("owner_email"),
    operatingNotes: text("operating_notes"),
    publicApproved: boolean("public_approved").notNull().default(false),
    reviewedBy: text("reviewed_by"),
    reviewedAt: text("reviewed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("service_coverage_city_line_unique").on(table.cityId, table.businessLineId),
    index("service_coverage_availability_idx").on(table.availability, table.publicApproved),
    check("service_coverage_availability_check", sql`${table.availability} in ('available','conditional','unavailable')`),
    check("service_coverage_capacity_check", sql`${table.capacityLevel} in ('high','medium','limited','review_required')`),
    check("service_coverage_mobilization_check", sql`${table.mobilizationDays} is null or ${table.mobilizationDays} >= 0`),
  ],
);

export const constructionOpportunities = pgTable(
  "construction_opportunities",
  {
    id: serial("id").primaryKey(),
    opportunityCode: text("opportunity_code").notNull().unique(),
    clientId: integer("client_id").references(() => clients.id, { onDelete: "restrict" }),
    clientName: text("client_name").notNull(),
    contactName: text("contact_name"),
    contactMobile: text("contact_mobile"),
    contactEmail: text("contact_email"),
    title: text("title").notNull(),
    cityId: integer("city_id").references(() => serviceCities.id, { onDelete: "restrict" }),
    projectType: text("project_type").notNull(),
    scopeSummary: text("scope_summary").notNull(),
    estimatedValueHalalas: integer("estimated_value_halalas"),
    expectedStartDate: text("expected_start_date"),
    bidDueDate: text("bid_due_date"),
    stage: text("stage").notNull().default("new"),
    probabilityBps: integer("probability_bps").notNull().default(1000),
    ownerEmail: text("owner_email").notNull(),
    source: text("source").notNull().default("portal"),
    lossReason: text("loss_reason"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("construction_opportunities_stage_due_idx").on(table.stage, table.bidDueDate),
    index("construction_opportunities_city_idx").on(table.cityId),
    index("construction_opportunities_client_idx").on(table.clientId),
    check("construction_opportunities_stage_check", sql`${table.stage} in ('new','qualified','survey','estimating','review','submitted','negotiation','won','lost','declined')`),
    check("construction_opportunities_probability_check", sql`${table.probabilityBps} >= 0 and ${table.probabilityBps} <= 10000`),
    check("construction_opportunities_value_check", sql`${table.estimatedValueHalalas} is null or ${table.estimatedValueHalalas} >= 0`),
  ],
);

export const constructionProjects = pgTable(
  "construction_projects",
  {
    id: serial("id").primaryKey(),
    projectCode: text("project_code").notNull().unique(),
    opportunityId: integer("opportunity_id").references(() => constructionOpportunities.id, { onDelete: "restrict" }),
    clientId: integer("client_id").references(() => clients.id, { onDelete: "restrict" }),
    clientName: text("client_name").notNull(),
    title: text("title").notNull(),
    cityId: integer("city_id").references(() => serviceCities.id, { onDelete: "restrict" }),
    projectType: text("project_type").notNull(),
    contractValueHalalas: integer("contract_value_halalas").notNull().default(0),
    budgetHalalas: integer("budget_halalas").notNull().default(0),
    startDate: text("start_date").notNull(),
    plannedEndDate: text("planned_end_date").notNull(),
    actualEndDate: text("actual_end_date"),
    progressBps: integer("progress_bps").notNull().default(0),
    status: text("status").notNull().default("mobilizing"),
    riskLevel: text("risk_level").notNull().default("low"),
    managerEmail: text("manager_email").notNull(),
    costCenterCode: text("cost_center_code").notNull().unique(),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("construction_projects_status_end_idx").on(table.status, table.plannedEndDate),
    index("construction_projects_city_idx").on(table.cityId),
    index("construction_projects_opportunity_idx").on(table.opportunityId),
    index("construction_projects_client_idx").on(table.clientId),
    check("construction_projects_status_check", sql`${table.status} in ('mobilizing','active','on_hold','substantial_completion','defects_liability','closed','cancelled')`),
    check("construction_projects_risk_check", sql`${table.riskLevel} in ('low','medium','high','critical')`),
    check("construction_projects_progress_check", sql`${table.progressBps} >= 0 and ${table.progressBps} <= 10000`),
    check("construction_projects_value_check", sql`${table.contractValueHalalas} >= 0 and ${table.budgetHalalas} >= 0`),
    check("construction_projects_dates_check", sql`${table.plannedEndDate} >= ${table.startDate}`),
  ],
);

export const portalAccessScopes = pgTable(
  "portal_access_scopes",
  {
    id: serial("id").primaryKey(),
    userEmail: text("user_email").notNull().references(() => portalUsers.email, { onDelete: "cascade" }),
    functionalRole: text("functional_role").notNull(),
    businessLineId: integer("business_line_id").references(() => businessLines.id, { onDelete: "restrict" }),
    regionId: integer("region_id").references(() => serviceRegions.id, { onDelete: "restrict" }),
    cityId: integer("city_id").references(() => serviceCities.id, { onDelete: "restrict" }),
    projectId: integer("project_id").references(() => constructionProjects.id, { onDelete: "cascade" }),
    financialLimitHalalas: integer("financial_limit_halalas"),
    approvalLimitHalalas: integer("approval_limit_halalas"),
    canApproveOwn: boolean("can_approve_own").notNull().default(false),
    validFrom: text("valid_from"),
    validUntil: text("valid_until"),
    active: boolean("active").notNull().default(true),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("portal_access_scopes_user_active_idx").on(table.userEmail, table.active),
    index("portal_access_scopes_project_idx").on(table.projectId),
    index("portal_access_scopes_city_idx").on(table.cityId),
    uniqueIndex("portal_access_scopes_assignment_unique").on(table.userEmail, table.functionalRole, table.businessLineId, table.regionId, table.cityId, table.projectId),
    check("portal_access_scopes_financial_limit_check", sql`${table.financialLimitHalalas} is null or ${table.financialLimitHalalas} >= 0`),
    check("portal_access_scopes_approval_limit_check", sql`${table.approvalLimitHalalas} is null or ${table.approvalLimitHalalas} >= 0`),
    check("portal_access_scopes_dates_check", sql`${table.validUntil} is null or ${table.validFrom} is null or ${table.validUntil} >= ${table.validFrom}`),
  ],
);

export const constructionRecords = pgTable(
  "construction_records",
  {
    id: serial("id").primaryKey(),
    recordCode: text("record_code").notNull().unique(),
    recordType: text("record_type").notNull(),
    opportunityId: integer("opportunity_id").references(() => constructionOpportunities.id, { onDelete: "restrict" }),
    projectId: integer("project_id").references(() => constructionProjects.id, { onDelete: "restrict" }),
    title: text("title").notNull(),
    description: text("description").notNull(),
    status: text("status").notNull().default("draft"),
    priority: text("priority").notNull().default("normal"),
    responsibleEmail: text("responsible_email").notNull(),
    dueDate: text("due_date"),
    amountHalalas: integer("amount_halalas"),
    retentionBps: integer("retention_bps").notNull().default(0),
    progressBps: integer("progress_bps").notNull().default(0),
    siteLatitudeE6: integer("site_latitude_e6"),
    siteLongitudeE6: integer("site_longitude_e6"),
    siteAccuracyMeters: integer("site_accuracy_meters"),
    weatherSummary: text("weather_summary"),
    workforceCount: integer("workforce_count"),
    equipmentNotes: text("equipment_notes"),
    revision: integer("revision").notNull().default(1),
    parentRecordId: integer("parent_record_id"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    version: integer("version").notNull().default(1),
  },
  (table) => [
    index("construction_records_type_status_idx").on(table.recordType, table.status),
    index("construction_records_project_type_idx").on(table.projectId, table.recordType),
    index("construction_records_opportunity_idx").on(table.opportunityId),
    index("construction_records_due_idx").on(table.dueDate),
    check("construction_records_type_check", sql`${table.recordType} in ('survey','estimate','boq','contract','wbs','daily_log','document','rfi','submittal','inspection','ncr','safety','procurement','subcontract','change_order','payment_certificate','handover','risk')`),
    check("construction_records_priority_check", sql`${table.priority} in ('low','normal','high','critical')`),
    check("construction_records_amount_check", sql`${table.amountHalalas} is null or ${table.amountHalalas} >= 0`),
    check("construction_records_percentage_check", sql`${table.retentionBps} between 0 and 10000 and ${table.progressBps} between 0 and 10000`),
    check("construction_records_location_check", sql`(${table.siteLatitudeE6} is null or ${table.siteLatitudeE6} between -90000000 and 90000000) and (${table.siteLongitudeE6} is null or ${table.siteLongitudeE6} between -180000000 and 180000000)`),
    check("construction_records_field_values_check", sql`(${table.siteAccuracyMeters} is null or ${table.siteAccuracyMeters} >= 0) and (${table.workforceCount} is null or ${table.workforceCount} >= 0)`),
  ],
);

export const constructionRecordAttachments = pgTable(
  "construction_record_attachments",
  {
    id: serial("id").primaryKey(),
    recordId: integer("record_id").notNull().references(() => constructionRecords.id, { onDelete: "cascade" }),
    revision: integer("revision").notNull().default(1),
    transmittalCode: text("transmittal_code").notNull(),
    title: text("title").notNull(),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull().unique(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    status: text("status").notNull().default("submitted"),
    reviewerEmail: text("reviewer_email"),
    reviewNotes: text("review_notes"),
    rejectionReason: text("rejection_reason"),
    submittedAt: text("submitted_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    reviewedAt: text("reviewed_at"),
    approvedAt: text("approved_at"),
    isCurrent: boolean("is_current").notNull().default(true),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("construction_record_attachments_record_idx").on(table.recordId, table.revision),
    uniqueIndex("construction_record_attachments_revision_unique").on(table.recordId, table.revision),
    index("construction_record_attachments_transmittal_idx").on(table.transmittalCode),
    check("construction_record_attachments_revision_check", sql`${table.revision} > 0`),
    check("construction_record_attachments_size_check", sql`${table.sizeBytes} > 0 and ${table.sizeBytes} <= 20971520`),
    check("construction_record_attachments_status_check", sql`${table.status} in ('submitted','under_review','approved','approved_as_noted','revise_resubmit','rejected','superseded')`),
  ],
);

export const constructionRecordLines = pgTable(
  "construction_record_lines",
  {
    id: serial("id").primaryKey(),
    recordId: integer("record_id").notNull().references(() => constructionRecords.id, { onDelete: "cascade" }),
    lineNumber: integer("line_number").notNull(),
    itemCode: text("item_code"),
    description: text("description").notNull(),
    unit: text("unit"),
    quantityMilli: integer("quantity_milli").notNull().default(0),
    unitRateHalalas: integer("unit_rate_halalas").notNull().default(0),
    totalHalalas: integer("total_halalas").notNull().default(0),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    uniqueIndex("construction_record_lines_record_number_unique").on(table.recordId, table.lineNumber),
    index("construction_record_lines_record_idx").on(table.recordId),
    check("construction_record_lines_values_check", sql`${table.quantityMilli} >= 0 and ${table.unitRateHalalas} >= 0 and ${table.totalHalalas} >= 0`),
  ],
);

export const constructionCostEntries = pgTable(
  "construction_cost_entries",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id").notNull().references(() => constructionProjects.id, { onDelete: "cascade" }),
    costCode: text("cost_code").notNull(),
    costTitle: text("cost_title").notNull(),
    costCategory: text("cost_category").notNull().default("other"),
    entryType: text("entry_type").notNull(),
    amountHalalas: integer("amount_halalas").notNull().default(0),
    effectiveDate: text("effective_date").notNull(),
    sourceRecordId: integer("source_record_id").references(() => constructionRecords.id, { onDelete: "restrict" }),
    referenceCode: text("reference_code"),
    notes: text("notes"),
    status: text("status").notNull().default("approved"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("construction_cost_entries_project_code_idx").on(table.projectId, table.costCode),
    index("construction_cost_entries_project_type_idx").on(table.projectId, table.entryType),
    index("construction_cost_entries_effective_date_idx").on(table.effectiveDate),
    check("construction_cost_entries_type_check", sql`${table.entryType} in ('baseline','commitment','actual','forecast_to_complete','approved_change','payment_certificate','retention')`),
    check("construction_cost_entries_category_check", sql`${table.costCategory} in ('labor','materials','equipment','subcontract','overhead','other')`),
    check("construction_cost_entries_status_check", sql`${table.status} in ('draft','approved','cancelled')`),
    check("construction_cost_entries_amount_check", sql`${table.amountHalalas} >= 0`),
  ],
);
