import { and, desc, eq, inArray, or } from "drizzle-orm";
import { getDb } from "@/db";
import { portalTaskAssignees, portalTasks, portalUsers } from "@/db/schema";
import { auditPortalAction } from "@/lib/audit";
import { emitPortalNotification } from "@/lib/portal-notifications";
import { requirePortalApiRole } from "@/lib/portal-access";
import { normalizePortalEmail } from "@/lib/portal-auth-config";
import { jsonNoStore, rejectCrossSiteRequest, requestCorrelationId } from "@/lib/security";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
const id=(value:unknown)=>{const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:0};
const owner=(access:NonNullable<Awaited<ReturnType<typeof requirePortalApiRole>>>)=>access.role==="admin"||access.functionalRoles.some(role=>role==="system_owner"||role==="system_admin");

export async function GET(){const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});const db=getDb(),email=normalizePortalEmail(access.user.email);const assigned=await db.select().from(portalTaskAssignees).where(eq(portalTaskAssignees.userEmail,email));const assignedIds=assigned.map(row=>row.taskId);const conditions=[eq(portalTasks.createdBy,email)];if(assignedIds.length)conditions.push(inArray(portalTasks.id,assignedIds));const tasks=await db.select().from(portalTasks).where(or(...conditions)).orderBy(desc(portalTasks.dueAt)).limit(1000);const taskIds=tasks.map(task=>task.id);const assignees=taskIds.length?await db.select().from(portalTaskAssignees).where(inArray(portalTaskAssignees.taskId,taskIds)):[];const users=owner(access)?await db.select({email:portalUsers.email,displayName:portalUsers.displayName}).from(portalUsers).where(eq(portalUsers.status,"active")):[];return jsonNoStore({tasks,assignees,users,canAssign:owner(access),currentEmail:email});}

export async function POST(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});try{const payload=await request.json() as Record<string,unknown>,title=clean(payload.title,200),description=clean(payload.description,2000),dueAt=clean(payload.dueAt,40),priority=clean(payload.priority,20)||"normal",email=normalizePortalEmail(access.user.email),canAssign=owner(access);const requested=Array.isArray(payload.assignees)?payload.assignees.map(value=>normalizePortalEmail(String(value))).filter(Boolean) as string[]:[];const visibility=requested.length?"assigned":"private";if(title.length<2||!dueAt||Number.isNaN(Date.parse(dueAt))||!["low","normal","high","urgent"].includes(priority))return jsonNoStore({error:"بيانات المهمة غير مكتملة"},{status:400});if(requested.length&&!canAssign)return jsonNoStore({error:"إسناد المهام للمستخدمين متاح للمالك أو مشرف النظام فقط"},{status:403});const db=getDb(),now=new Date().toISOString();const assigneeEmails=[...new Set(requested)];if(assigneeEmails.length){const valid=await db.select({email:portalUsers.email}).from(portalUsers).where(and(inArray(portalUsers.email,assigneeEmails),eq(portalUsers.status,"active")));if(valid.length!==assigneeEmails.length)return jsonNoStore({error:"أحد المستخدمين المحددين غير نشط أو غير موجود"},{status:400});}const saved=await db.transaction(async tx=>{const[task]=await tx.insert(portalTasks).values({title,description:description||null,dueAt:new Date(dueAt).toISOString(),priority,visibility,createdBy:email,updatedAt:now}).returning();if(assigneeEmails.length)await tx.insert(portalTaskAssignees).values(assigneeEmails.map(userEmail=>({taskId:task.id,userEmail})));return task;});await auditPortalAction({actorEmail:email,action:"portal-task-created",entityType:"portal-task",entityId:saved.id,after:{...saved,assignees:assigneeEmails},correlationId:requestCorrelationId(request)});for(const targetEmail of assigneeEmails)await emitPortalNotification({eventType:"portal-task-assigned",title:"أُسندت إليك مهمة جديدة",message:`${saved.title} — الموعد ${new Date(saved.dueAt).toLocaleString("ar-SA")}`,severity:priority==="urgent"?"critical":priority==="high"?"warning":"info",module:"tasks",entityType:"portal-task",entityId:saved.id,actionView:"tasks",targetEmail}).catch(()=>undefined);return jsonNoStore({task:saved},{status:201});}catch(error){return jsonNoStore({error:error instanceof Error?error.message:"تعذر إنشاء المهمة"},{status:400});}}

export async function PATCH(request:Request){if(rejectCrossSiteRequest(request))return jsonNoStore({error:"مصدر الطلب غير مسموح"},{status:403});const access=await requirePortalApiRole(["admin","manager","employee"]);if(!access)return jsonNoStore({error:"غير مصرح"},{status:403});try{const payload=await request.json() as Record<string,unknown>,taskId=id(payload.id),action=clean(payload.action,30),email=normalizePortalEmail(access.user.email),db=getDb(),now=new Date().toISOString();const task=await db.query.portalTasks.findFirst({where:eq(portalTasks.id,taskId)});if(!task)return jsonNoStore({error:"المهمة غير موجودة"},{status:404});const assignment=await db.query.portalTaskAssignees.findFirst({where:and(eq(portalTaskAssignees.taskId,taskId),eq(portalTaskAssignees.userEmail,email))});if(task.createdBy!==email&&!assignment)return jsonNoStore({error:"غير مصرح بهذه المهمة"},{status:403});if(action==="acknowledge"){if(assignment)await db.update(portalTaskAssignees).set({reminderAcknowledgedAt:now}).where(eq(portalTaskAssignees.id,assignment.id));return jsonNoStore({acknowledged:true});}if(action!=="complete")return jsonNoStore({error:"العملية غير مدعومة"},{status:400});if(task.visibility==="private"){if(task.createdBy!==email)return jsonNoStore({error:"غير مصرح"},{status:403});const[updated]=await db.update(portalTasks).set({status:"completed",completedBy:email,completedAt:now,updatedAt:now}).where(and(eq(portalTasks.id,taskId),eq(portalTasks.status,"open"))).returning();await auditPortalAction({actorEmail:email,action:"portal-task-completed",entityType:"portal-task",entityId:taskId,before:task,after:updated});return jsonNoStore({task:updated});}if(!assignment)return jsonNoStore({error:"مالك المهمة يراجع الإنجاز من خلال حالة المستلمين"},{status:409});await db.update(portalTaskAssignees).set({status:"completed",completedAt:now}).where(and(eq(portalTaskAssignees.id,assignment.id),eq(portalTaskAssignees.status,"open")));const open=await db.select({id:portalTaskAssignees.id}).from(portalTaskAssignees).where(and(eq(portalTaskAssignees.taskId,taskId),eq(portalTaskAssignees.status,"open")));const updated=open.length?task:(await db.update(portalTasks).set({status:"completed",completedBy:email,completedAt:now,updatedAt:now}).where(eq(portalTasks.id,taskId)).returning())[0];await auditPortalAction({actorEmail:email,action:"portal-task-assignee-completed",entityType:"portal-task",entityId:taskId,before:task,after:{task:updated,assignee:email}});await emitPortalNotification({eventType:"portal-task-completed",title:"تم إنجاز مهمة مرسلة",message:`${task.title} — أنجزها ${access.user.displayName}`,severity:"success",module:"tasks",entityType:"portal-task",entityId:taskId,actionView:"tasks",targetEmail:task.createdBy}).catch(()=>undefined);return jsonNoStore({task:updated});}catch(error){return jsonNoStore({error:error instanceof Error?error.message:"تعذر تحديث المهمة"},{status:400});}}
